import { CatalogMission } from "./missions.types";

export const WEEKLY_POOL: CatalogMission[] = [
  {
    "period": "weekly",
    "id": "w_01",
    "title": "Haftalık Maraton",
    "desc": "Hafta boyunca 15 düello tamamla",
    "actionType": "duel_play",
    "target": 15,
    "rewardXp": 300,
    "rewardCoins": 45,
    "difficulty": "medium"
  },
  {
    "period": "weekly",
    "id": "w_02",
    "title": "Büyük Zaferler",
    "desc": "Hafta boyunca 8 düello kazan",
    "actionType": "duel_win",
    "target": 8,
    "rewardXp": 480,
    "rewardCoins": 75,
    "rewardShields": 1,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_03",
    "title": "Kelime Fabrikası",
    "desc": "Toplam 120 kelime patlat",
    "actionType": "word_count",
    "target": 120,
    "rewardXp": 320,
    "rewardCoins": 50,
    "difficulty": "medium"
  },
  {
    "period": "weekly",
    "id": "w_04",
    "title": "Sözlük Dehası",
    "desc": "En az 7 harfli 10 kelime bul",
    "actionType": "word_length",
    "target": 10,
    "param": 7,
    "rewardXp": 500,
    "rewardCoins": 80,
    "rewardShields": 1,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_05",
    "title": "Arcade Şöleni",
    "desc": "Arcade modunda 5.000 kümülatif puan kazan",
    "actionType": "arcade_score",
    "target": 5000,
    "rewardXp": 460,
    "rewardCoins": 70,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_06",
    "title": "Vintage Arşiv Müfettişi",
    "desc": "15 Gazete Eki bulmacası çöz",
    "actionType": "vintage_solve",
    "target": 15,
    "rewardXp": 320,
    "rewardCoins": 50,
    "difficulty": "medium"
  },
  {
    "period": "weekly",
    "id": "w_07",
    "title": "Altın Haftası",
    "desc": "Oyunlardan 400 Çip topla",
    "actionType": "earn_chips",
    "target": 400,
    "rewardXp": 480,
    "rewardCoins": 75,
    "rewardShields": 1,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_08",
    "title": "Klasik Fatih",
    "desc": "15 Solo Klasik seviye geç",
    "actionType": "solo_progress",
    "target": 15,
    "rewardXp": 300,
    "rewardCoins": 45,
    "difficulty": "medium"
  },
  {
    "period": "weekly",
    "id": "w_09",
    "title": "Devasa Tahta Hakimi",
    "desc": "10x10 Devasa Arenada 5 düello oyna",
    "actionType": "duel_play",
    "target": 5,
    "param": 10,
    "rewardXp": 460,
    "rewardCoins": 70,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_10",
    "title": "Büyük Kombo Resitali",
    "desc": "Toplam 25 seri (combo) yap",
    "actionType": "combo_count",
    "target": 25,
    "rewardXp": 480,
    "rewardCoins": 75,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_11",
    "title": "Haftalık Meydan Okuma",
    "desc": "Hafta boyunca 20 düello tamamla",
    "actionType": "duel_play",
    "target": 20,
    "rewardXp": 480,
    "rewardCoins": 75,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_12",
    "title": "Yenilmez Lig Şampiyonu",
    "desc": "Hafta boyunca 12 düello kazan",
    "actionType": "duel_win",
    "target": 12,
    "rewardXp": 650,
    "rewardCoins": 110,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_13",
    "title": "Kelime Çağlayanı",
    "desc": "Toplam 180 kelime patlat",
    "actionType": "word_count",
    "target": 180,
    "rewardXp": 520,
    "rewardCoins": 80,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_14",
    "title": "8 Harflik Şaheserler",
    "desc": "En az 8 harfli 5 kelime bul",
    "actionType": "word_length",
    "target": 5,
    "param": 8,
    "rewardXp": 680,
    "rewardCoins": 120,
    "rewardShields": 1,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_15",
    "title": "Arcade Ustası",
    "desc": "Arcade modunda 8.000 puan topla",
    "actionType": "arcade_score",
    "target": 8000,
    "rewardXp": 520,
    "rewardCoins": 80,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_16",
    "title": "Vintage Koleksiyoneri",
    "desc": "25 Gazete Eki bulmacası çöz",
    "actionType": "vintage_solve",
    "target": 25,
    "rewardXp": 520,
    "rewardCoins": 80,
    "rewardShields": 1,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_17",
    "title": "Milyonerler Kulübü",
    "desc": "Oyunlardan 600 Çip topla",
    "actionType": "earn_chips",
    "target": 600,
    "rewardXp": 700,
    "rewardCoins": 125,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_18",
    "title": "Solo Kaşif",
    "desc": "25 Solo Klasik seviye geç",
    "actionType": "solo_progress",
    "target": 25,
    "rewardXp": 480,
    "rewardCoins": 75,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_19",
    "title": "8x8 Hakimiyeti",
    "desc": "8x8 Arenada 8 düello kazan",
    "actionType": "duel_win",
    "target": 8,
    "param": 8,
    "rewardXp": 680,
    "rewardCoins": 120,
    "rewardShields": 1,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_20",
    "title": "Devasa Seri",
    "desc": "Toplam 40 seri kombo oluştur",
    "actionType": "combo_count",
    "target": 40,
    "rewardXp": 520,
    "rewardCoins": 80,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_21",
    "title": "Haftalık Sadakat",
    "desc": "4 farklı gün Günün Gizemli Kelimesini çöz",
    "actionType": "daily_route",
    "target": 4,
    "rewardXp": 500,
    "rewardCoins": 78,
    "rewardShields": 1,
    "difficulty": "hard"
  },
  {
    "period": "weekly",
    "id": "w_22",
    "title": "Mini Tahta Ustası",
    "desc": "4x4 Mini Düelloda 10 galibiyet al",
    "actionType": "duel_win",
    "target": 10,
    "param": 4,
    "rewardXp": 350,
    "rewardCoins": 55,
    "difficulty": "medium"
  },
  {
    "period": "weekly",
    "id": "w_23",
    "title": "Kelime Okyanusu",
    "desc": "Toplam 250 kelime bul",
    "actionType": "word_count",
    "target": 250,
    "rewardXp": 720,
    "rewardCoins": 130,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_24",
    "title": "9 Harfli Devler",
    "desc": "En az 9 harfli 3 kelime üret",
    "actionType": "word_length",
    "target": 3,
    "param": 9,
    "rewardXp": 720,
    "rewardCoins": 130,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_25",
    "title": "Arcade Şampiyonlar Ligi",
    "desc": "Arcade modunda 12.000 puana ulaş",
    "actionType": "arcade_score",
    "target": 12000,
    "rewardXp": 750,
    "rewardCoins": 135,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_26",
    "title": "Eski Gazete Duayeni",
    "desc": "35 Gazete Eki bulmacası tamamla",
    "actionType": "vintage_solve",
    "target": 35,
    "rewardXp": 720,
    "rewardCoins": 130,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_27",
    "title": "Hazine Sandığı",
    "desc": "Oyunlardan 900 Çip elde et",
    "actionType": "earn_chips",
    "target": 900,
    "rewardXp": 780,
    "rewardCoins": 140,
    "rewardShields": 3,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_28",
    "title": "Solo Efsane",
    "desc": "35 Solo Klasik seviye geç",
    "actionType": "solo_progress",
    "target": 35,
    "rewardXp": 720,
    "rewardCoins": 130,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_29",
    "title": "Düello Fırtınası",
    "desc": "Hafta boyunca 30 düello tamamla",
    "actionType": "duel_play",
    "target": 30,
    "rewardXp": 750,
    "rewardCoins": 135,
    "rewardShields": 2,
    "difficulty": "epic"
  },
  {
    "period": "weekly",
    "id": "w_30",
    "title": "Büyük Tahta İmparatoru",
    "desc": "10x10 Devasa Düelloda 5 galibiyet al",
    "actionType": "duel_win",
    "target": 5,
    "param": 10,
    "rewardXp": 800,
    "rewardCoins": 150,
    "rewardShields": 3,
    "difficulty": "epic"
  }
];
