import { StyleSheet } from "react-native";

export const vintageStyles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    backgroundColor: "#F0F5ED",
    paddingTop: 4,
    paddingHorizontal: 0,
  },
  headerContainer: {
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 8,
    gap: 8,
  },
  headerNavRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 36,
  },
  headerNavLeft: {
    flex: 1,
    alignItems: "flex-start",
  },
  headerNavRight: {
    flex: 1,
    alignItems: "flex-end",
  },
  backBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  backBtnText: {
    color: "#2a9c7a",
    fontSize: 12,
    fontWeight: "900",
  },
  titleWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  newspaperKicker: {
    color: "#98732c",
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  newspaperTitle: {
    color: "#293541",
    fontSize: 14.5,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  statusBarRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1.5,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
    minHeight: 30,
  },
  pressedPill: {
    opacity: 0.75,
    transform: [{ scale: 0.96 }],
  },
  statusPillIcon: {
    fontSize: 12,
  },
  statusPillText: {
    fontSize: 11.5,
    fontWeight: "900",
  },
  livesPill: {
    backgroundColor: "#f0fdf4",
    borderColor: "#bbf7d0",
  },
  livesPillText: {
    color: "#16a34a",
  },
  infiniteLivesPill: {
    backgroundColor: "#fef3c7",
    borderColor: "#f59e0b",
  },
  infiniteLivesPillText: {
    color: "#b45309",
    fontWeight: "900",
    fontSize: 14,
  },
  hintPill: {
    backgroundColor: "#fefce8",
    borderColor: "#fef08a",
  },
  hintPillText: {
    color: "#ca8a04",
  },
  resetPill: {
    backgroundColor: "#f8fafc",
    borderColor: "#cbd5e1",
  },
  resetPillText: {
    color: "#475569",
  },
  scorePill: {
    backgroundColor: "#fffbeb",
    borderColor: "#fde68a",
  },
  scorePillText: {
    color: "#b45309",
  },
  paperBoardScroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  paperBoard: {
    flex: 1,
    backgroundColor: "#faf7ef",
    borderRadius: 0,
    borderWidth: 0,
    borderTopWidth: 2,
    borderColor: "#DCE1D7",
    padding: 10,
    position: "relative",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  paperTextureOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "transparent",
    opacity: 0.04,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  errorBanner: {
    backgroundColor: "#fff3f3",
    borderWidth: 1.5,
    borderColor: "#fca5a5",
    padding: 6,
    borderRadius: 10,
    marginBottom: 6,
  },
  successBanner: {
    backgroundColor: "#f0fdf4",
    borderColor: "#86efac",
  },
  errorText: {
    color: "#991b1b",
    fontSize: 11,
    fontWeight: "800",
    textAlign: "center",
  },
  successText: {
    color: "#166534",
  },
  centerWordBannerCard: {
    backgroundColor: "#fffae7",
    borderWidth: 2,
    borderColor: "#DCE1D7",
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
  },
  centerBadgeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  centerBadgeTag: {
    backgroundColor: "#fbd699",
    color: "#293541",
    fontSize: 9.5,
    fontWeight: "900",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  centerLengthText: {
    color: "#b45309",
    fontSize: 9.5,
    fontWeight: "900",
  },
  centerClueText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 4,
  },
  centerHelperText: {
    color: "#293541",
    fontSize: 8.5,
    fontStyle: "italic",
  },
  activeClueBannerCard: {
    backgroundColor: "#fffae7",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    borderRadius: 10,
    padding: 8,
    marginBottom: 6,
    minHeight: 52,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  activeClueBannerCardSolved: {
    backgroundColor: "#f0fdf4",
    borderColor: "#10b981",
  },
  activeClueBannerCardEmpty: {
    backgroundColor: "#f5f1e8",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 10,
    padding: 8,
    marginBottom: 6,
    justifyContent: "center",
    alignItems: "center",
    minHeight: 52,
  },
  emptyClueText: {
    color: "#293541",
    fontSize: 10,
    fontWeight: "800",
    fontStyle: "italic",
  },
  activeClueBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 2,
  },
  activeClueBadgeTag: {
    backgroundColor: "#fbd699",
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "900",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
  },
  activeClueBadgeTagSolved: {
    backgroundColor: "#10b981",
    color: "#ffffff",
  },
  activeClueLengthText: {
    color: "#b45309",
    fontSize: 8.5,
    fontWeight: "900",
  },
  activeClueText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "800",
  },
  dirRowCompactInline: {
    flexDirection: "row",
    gap: 4,
    marginLeft: "auto",
  },
  dirBtnMini: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  dirBtnActive: {
    backgroundColor: "#FFF0E8",
    borderColor: "#DCE1D7",
  },
  dirBtnTextMini: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "800",
  },
  dirBtnTextActive: {
    color: "#293541",
  },
  sectionLabelCompact: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginVertical: 2,
  },
  horizontalTargetList: {
    maxHeight: 36,
    marginBottom: 6,
  },
  targetChipHorizontal: {
    backgroundColor: "#f5f1e8",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 6,
    justifyContent: "center",
  },
  targetChip: {
    width: "48.5%",
    backgroundColor: "#f5f1e8",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    borderRadius: 8,
    padding: 6,
  },
  targetChipCenterWord: {
    backgroundColor: "#fffae7",
    borderColor: "#DCE1D7",
  },
  targetChipSelected: {
    borderColor: "#DCE1D7",
    borderWidth: 2,
    backgroundColor: "#f2faff",
  },
  targetChipCompleted: {
    backgroundColor: "#ecfdf4",
    borderColor: "#DCE1D7",
  },
  targetWordText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
  },
  targetWordTextCompleted: {
    color: "#293541",
  },
  targetHintText: {
    color: "#293541",
    fontSize: 9,
    marginTop: 2,
  },
  gridContainer: {
    alignSelf: "center",
    backgroundColor: "#FFF0E8",
    padding: 2,
    borderRadius: 8,
    marginBottom: 8,
  },
  gridRow: {
    flexDirection: "row",
  },
  gridCell: {
    width: 34,
    height: 34,
    backgroundColor: "#fdfbf5",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  gridCellBlocked: {
    backgroundColor: "#FFF0E8",
    borderColor: "#DCE1D7",
  },
  blockedHatch: {
    width: "40%",
    height: "40%",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 2,
  },
  cellNumberBadge: {
    position: "absolute",
    top: 1,
    left: 2,
    fontSize: 7.5,
    fontWeight: "900",
    color: "#293541",
  },
  cellNumberBadgeSelected: {
    color: "#293541",
  },
  gridCellCenterArea: {
    backgroundColor: "#fffae7",
    borderColor: "#DCE1D7",
  },
  gridCellCenterWord: {
    backgroundColor: "#fef08a",
    borderColor: "#eab308",
    borderWidth: 2,
    shadowColor: "#ca8a04",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  gridCellPlaced: {
    backgroundColor: "#c2f5e1",
    borderColor: "#10b981",
  },
  gridCellDraft: {
    backgroundColor: "#ffffff",
    borderColor: "#64748b",
  },
  gridCellCompleted: {
    backgroundColor: "#d1fae5",
    borderColor: "#10b981",
    borderWidth: 2,
    shadowColor: "#059669",
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  gridCellTargetWord: {
    backgroundColor: "#fffdf7",
    borderColor: "#DCE1D7",
    borderWidth: 2,
  },
  gridCellSelected: {
    borderColor: "#DCE1D7",
    borderWidth: 2.5,
    backgroundColor: "#aef5e0",
  },
  gridCellError: {
    backgroundColor: "#FEE2E2",
    borderColor: "#EF4444",
    borderWidth: 2.5,
    shadowColor: "#EF4444",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.45,
    shadowRadius: 5,
    elevation: 4,
  },
  centerStarIcon: {
    fontSize: 10,
    position: "absolute",
    opacity: 0.6,
  },
  cellCharText: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
  },
  cellCharCompletedText: {
    color: "#293541",
    fontWeight: "900",
  },
  cellCharSelectedText: {
    color: "#293541",
  },
  cellCharErrorText: {
    color: "#DC2626",
    fontWeight: "900",
  },
  cellNumberBadgeError: {
    color: "#EF4444",
  },
  letterPoolContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "center",
    padding: 8,
    backgroundColor: "#F7F5EE",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  emptyPoolText: {
    color: "#293541",
    fontSize: 11,
    fontStyle: "italic",
  },
  letterTile: {
    width: 36,
    height: 36,
    backgroundColor: "#ffffff",
    borderWidth: 1.5,
    borderBottomWidth: 3,
    borderColor: "#DCE1D7",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  letterTilePressed: {
    transform: [{ scale: 0.92 }],
    backgroundColor: "#fffae7",
  },
  letterTileText: {
    color: "#293541",
    fontSize: 15,
    fontWeight: "900",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  winOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(35, 48, 59, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    zIndex: 999,
  },
  winCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 2,
    borderColor: "#DCE1D7",
    padding: 24,
    alignItems: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  winTitle: {
    color: "#2a9c7a",
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginTop: 8,
    marginBottom: 6,
  },
  winDesc: {
    color: "#293541",
    fontSize: 11.5,
    textAlign: "center",
    lineHeight: 17,
    marginBottom: 16,
  },
  winReward: {
    color: "#98732c",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 20,
  },
  completedAllBanner: {
    backgroundColor: "rgba(255, 194, 74, 0.15)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    width: "100%",
    alignItems: "center",
    marginBottom: 10,
  },
  completedAllText: {
    color: "#98732c",
    fontSize: 11.5,
    fontWeight: "900",
    textAlign: "center",
  },
  nextBtn: {
    backgroundColor: "#aef5e0",
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 20,
    width: "100%",
    alignItems: "center",
    marginBottom: 10,
  },
  nextBtnText: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  mapReturnBtn: {
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingVertical: 12,
    paddingHorizontal: 20,
    width: "100%",
    alignItems: "center",
  },
  mapReturnBtnText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "800",
  },
  mapHeroCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    marginHorizontal: 12,
    marginBottom: 12,
    padding: 14,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  mapHeroTitle: {
    color: "#98732c",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 4,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  mapHeroSubtitle: {
    color: "#293541",
    fontSize: 11,
    lineHeight: 16,
    marginBottom: 12,
  },
  mapStatsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#F7F5EE",
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  mapStatItem: {
    alignItems: "center",
    flex: 1,
  },
  mapStatValue: {
    color: "#2a9c7a",
    fontSize: 15,
    fontWeight: "900",
  },
  mapStatLabel: {
    color: "#293541",
    fontSize: 9.5,
    fontWeight: "800",
    marginTop: 2,
  },
  levelMapGridContainer: {
    paddingHorizontal: 12,
    paddingBottom: 24,
  },
  mapGridRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  levelCardNode: {
    width: "48%",
    backgroundColor: "#F0F5ED",
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    padding: 12,
    minHeight: 90,
    justifyContent: "space-between",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  levelCardCompleted: {
    borderColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
  },
  levelCardLocked: {
    opacity: 0.45,
    borderColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
  },
  levelCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  levelDiffBadge: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "900",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    overflow: "hidden",
  },
  completedStarText: {
    fontSize: 9,
  },
  lockIconText: {
    fontSize: 11,
  },
  unlockedBadgeText: {
    color: "#2a9c7a",
    fontSize: 9,
    fontWeight: "800",
  },
  levelNumberText: {
    color: "#293541",
    fontSize: 15,
    fontWeight: "900",
    marginVertical: 4,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  levelNumberLockedText: {
    color: "#293541",
  },
  levelCardFooterText: {
    color: "#2a9c7a",
    fontSize: 10,
    fontWeight: "800",
  },
  exitModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(35, 48, 59, 0.55)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  exitModalCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  exitModalIcon: {
    fontSize: 42,
    marginBottom: 8,
  },
  exitModalTitle: {
    color: "#293541",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  exitModalSub: {
    color: "#293541",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
    marginBottom: 20,
  },
  exitModalResumeBtn: {
    width: "100%",
    height: 44,
    backgroundColor: "#aef5e0",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  exitModalResumeText: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  exitModalConfirmBtn: {
    width: "100%",
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    backgroundColor: "rgba(255, 100, 124, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  exitModalConfirmText: {
    color: "#ca4f62",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
});
