import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({

  container: {
    flexGrow: 1,
    paddingTop: 4,
    paddingBottom: 195,
    paddingHorizontal: 2,
  },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  back: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  backText: { color: "#293541", fontSize: 26, lineHeight: 28 },
  headerTextWrap: { flex: 1, marginLeft: 10 },
  overline: { color: "#8c7540", fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  title: { color: "#293541", fontSize: 26, fontWeight: "900", marginTop: 2, letterSpacing: 0.3 },
  headerChipsBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F5ED",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    gap: 4,
  },
  headerChipsIcon: { fontSize: 13 },
  headerChipsVal: { color: "#98732c", fontSize: 13, fontWeight: "900" },

  /* Tab Navigation */
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 4,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    marginBottom: 12,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 9,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  tabBtnActive: {
    backgroundColor: "#FFD66E",
    borderWidth: 1,
    borderColor: "#F0C855",
  },
  tabBtnText: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  tabBtnTextActive: {
    color: "#293541",
    fontWeight: "900",
  },

  /* 1. HERO OPERATÖR KARTI */
  heroCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    marginBottom: 12,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 0,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarWrapper: {
    position: "relative",
    marginRight: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarRing: {
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 2.5,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "#F0F5ED",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 34,
    resizeMode: "cover",
  },
  avatarInnerFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarGlyph: {
    fontSize: 32,
    fontWeight: "900",
  },
  levelBadge: {
    position: "absolute",
    top: -4,
    left: -4,
    backgroundColor: "#e8d8a4",
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
  },
  levelBadgeText: {
    color: "#293541",
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  flameBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EA580C",
    borderRadius: 10,
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderWidth: 1.5,
    borderColor: "#FFEDD5",
    shadowColor: "#EA580C",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 3,
    elevation: 4,
    zIndex: 10,
  },
  flameBadgeText: {
    color: "#FFFFFF",
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  avatarActionsRow: {
    flexDirection: "row",
    gap: 4,
    position: "absolute",
    bottom: -8,
  },
  cameraIconBtn: {
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  cameraIconText: {
    color: "#2a9c7a",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  resetGlyphBtn: {
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  resetGlyphText: {
    color: "#ca4f62",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  heroInfo: {
    flex: 1,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  namePressable: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  heroName: {
    color: "#293541",
    fontSize: 19,
    fontWeight: "900",
    letterSpacing: 0.5,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  editPenBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: "rgba(212, 180, 90, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  editPen: {
    fontSize: 11,
  },
  nameEditWrap: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 8,
  },
  nameTextInput: {
    flex: 1,
    backgroundColor: "#F0F5ED",
    color: "#2a9c7a",
    fontSize: 16,
    fontWeight: "900",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
  },
  saveNameBtn: {
    backgroundColor: "#aef5e0",
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  saveNameBtnText: {
    color: "#293541",
    fontWeight: "900",
    fontSize: 16,
  },
  metaBadgesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 6,
    marginTop: 6,
  },
  titleBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(212, 180, 90, 0.15)",
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    gap: 4,
  },
  titleBadgeIcon: { fontSize: 10 },
  titleBadgeText: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  leagueBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
  },
  leagueBadgeIcon: { fontSize: 10 },
  leagueBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },

  /* XP Progress */
  xpSection: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#DCE1D7",
  },
  xpHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  xpTagWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  xpTagIcon: { fontSize: 11 },
  xpLabel: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  xpValues: {
    fontSize: 10.5,
    fontWeight: "900",
  },
  xpCurrent: {
    color: "#2a9c7a",
  },
  xpTotal: {
    color: "#293541",
  },
  xpTrack: {
    height: 7,
    backgroundColor: "#F0F5ED",
    borderRadius: 6,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  xpFill: {
    height: "100%",
    backgroundColor: "#aef5e0",
    borderRadius: 6,
  },
  xpFooterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  xpPercentText: {
    color: "#2a9c7a",
    fontSize: 8.5,
    fontWeight: "800",
  },
  xpNextHint: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "700",
  },

  /* Section Headers */
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  sectionTitle: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  sectionMeta: {
    color: "#8c7540",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  badgeCounterWrap: {
    backgroundColor: "rgba(212, 180, 90, 0.15)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },

  /* 2. STATS GRID (Compact 2x2) */
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
  },
  statTile: {
    width: "48.5%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    gap: 8,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  statTileWins: { borderColor: "#FFE2A0", backgroundColor: "#FFFFFF" },
  statTileMatches: { borderColor: "#CCE5FF", backgroundColor: "#FFFFFF" },
  statTileWinRate: { borderColor: "#E5D9FD", backgroundColor: "#FFFFFF" },
  statTileScore: { borderColor: "#BCE9D7", backgroundColor: "#FFFFFF" },
  statIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    elevation: 0,
  },
  statIcon: { fontSize: 15 },
  statDataWrap: { flex: 1 },
  statNumber: {
    color: "#293541",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.3,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  statCaption: {
    color: "#293541",
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.5,
    marginTop: 1,
  },

  /* Mini Intel HUD Strip */
  intelStrip: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    marginTop: 10,
    alignItems: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  intelCell: { flex: 1, alignItems: "center" },
  intelLabel: {
    color: "#293541",
    fontSize: 7.5,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  intelValue: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 3,
    textAlign: "center",
  },
  intelSub: { fontSize: 8, color: "#293541" },
  intelDivider: { width: 1, height: 24, backgroundColor: "#E2E8F0" },

  /* Horizontal Row (Carousels) */
  horizontalRow: {
    gap: 10,
    paddingVertical: 4,
  },

  /* Profile Frames Showcase */
  frameTile: {
    width: 90,
    height: 102,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    padding: 6,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  frameTileLocked: {
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  framePreviewCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  framePreviewInner: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },

  /* Titles & Badges Tiles */
  titleTile: {
    width: 88,
    height: 94,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    padding: 6,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  titleTileUnlocked: {
    borderColor: "#DCE1D7",
    backgroundColor: "#FFFFFF",
  },
  titleTileLocked: {
    borderColor: "#E2E8F0",
    backgroundColor: "#FFFFFF",
  },
  titleTileSelected: {
    borderColor: "#2A9C7A",
    borderWidth: 2,
    backgroundColor: "#F0FAF5",
  },
  titleMiniStatusPill: {
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
    backgroundColor: "#F7F5EE",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    marginTop: 3,
  },
  titleMiniStatusSelected: {
    backgroundColor: "#FFD66E",
    borderColor: "#F0C855",
  },
  titleMiniStatusLocked: {
    backgroundColor: "#F1F3EE",
    borderColor: "#DCE1D7",
  },
  titleMiniStatusText: {
    fontSize: 7.5,
    fontWeight: "900",
    letterSpacing: 0.4,
    color: "#293541",
  },

  badgeTile: {
    width: 88,
    height: 92,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    padding: 6,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  badgeTileLocked: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
  },
  badgeIconBubble: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
    backgroundColor: "#FFFFFF",
  },
  badgeIconText: { fontSize: 16 },
  badgeTileTitle: {
    color: "#293541",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.3,
    textAlign: "center",
  },

  /* Settings & Danger Zone */
  settingsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 0,
    marginBottom: 12,
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#DCE1D7",
  },
  settingLabelWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  settingIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    backgroundColor: "#F7F5EE",
  },
  settingRowIcon: { fontSize: 16 },
  settingLabel: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  settingSubLabel: {
    color: "#64748B",
    fontSize: 9,
    fontWeight: "700",
    marginTop: 2,
  },

  genderTitle: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  genderSub: {
    color: "#64748B",
    fontSize: 9,
    fontWeight: "600",
    marginTop: 2,
    marginBottom: 10,
  },
  genderRow: {
    flexDirection: "row",
    gap: 8,
  },
  genderPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 12,
    paddingVertical: 9,
  },
  genderPillSelected: {
    backgroundColor: "#E6F7F0",
    borderColor: "#3EE8B5",
    borderWidth: 1.5,
  },
  genderPillText: {
    color: "#64748B",
    fontSize: 9.5,
    fontWeight: "800",
  },
  genderPillTextSelected: {
    color: "#2A9C7A",
    fontWeight: "900",
  },

  themePill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  themePillSelected: {
    backgroundColor: "#E6F7F0",
    borderColor: "#3EE8B5",
    borderWidth: 1.5,
  },
  themePillText: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "800",
  },
  themePillTextSelected: {
    color: "#2A9C7A",
    fontWeight: "900",
  },

  appInfoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    padding: 12,
    alignItems: "center",
    marginBottom: 12,
  },
  appInfoTitle: {
    color: "#8c7540",
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  appInfoSub: {
    color: "#64748B",
    fontSize: 8.5,
    fontWeight: "700",
    marginTop: 2,
  },

  dangerZoneCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    gap: 10,
    marginBottom: 10,
  },
  actionButtonSecondary: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(212, 180, 90, 0.1)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    paddingVertical: 13,
    borderRadius: 16,
    gap: 8,
  },
  actionBtnSecondaryText: {
    color: "#293541",
    fontSize: 11.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  actionButtonDanger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    paddingVertical: 13,
    borderRadius: 16,
    gap: 8,
  },
  actionBtnDangerText: {
    color: "#bf5757",
    fontSize: 11.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  actionBtnIcon: { fontSize: 13 },
  privacyBtn: {
    marginTop: 4,
    paddingVertical: 8,
    alignItems: "center",
  },
  privacyBtnText: {
    color: "#293541",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  pressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },

  /* Modals */
  modalIconTopWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(212, 180, 90, 0.15)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 10,
  },
  modalIconTop: { fontSize: 20 },
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(35, 48, 59, 0.55)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  deleteModalCard: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#EF4444",
    padding: 22,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  deleteModalTitle: {
    color: "#EF4444",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
    marginBottom: 10,
  },
  deleteModalDesc: {
    color: "#293541",
    fontSize: 12.5,
    lineHeight: 18,
    textAlign: "center",
    marginBottom: 12,
  },
  deleteModalPrompt: {
    color: "#64748B",
    fontSize: 11.5,
    textAlign: "center",
    marginBottom: 10,
  },
  deleteModalInput: {
    backgroundColor: "#F7F5EE",
    borderWidth: 1.5,
    borderColor: "#EF4444",
    borderRadius: 14,
    color: "#EF4444",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    paddingVertical: 10,
    letterSpacing: 2,
    marginBottom: 16,
  },
  deleteModalActions: {
    flexDirection: "row",
    gap: 10,
  },
  deleteModalCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "#F7F5EE",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
  },
  deleteModalCancelText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  deleteModalConfirmBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "#EF4444",
    alignItems: "center",
  },
  deleteModalConfirmDisabled: {
    opacity: 0.35,
    backgroundColor: "rgba(239, 68, 68, 0.3)",
  },
  deleteModalConfirmText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
});
