import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  cardContainer: {
    width: "100%",
    maxWidth: 380,
    maxHeight: "88%",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    padding: 18,
    position: "relative",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    overflow: "hidden",
  },
  accentLine: {
    position: "absolute",
    top: 0,
    left: 24,
    right: 24,
    height: 3,
    backgroundColor: "#aef5e0",
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
  },
  closeBtn: {
    position: "absolute",
    top: 14,
    right: 14,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  closeBtnText: {
    color: "#293541",
    fontSize: 14,
    fontWeight: "900",
  },
  scrollContent: {
    paddingTop: 6,
    paddingBottom: 4,
  },
  identityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 16,
  },
  avatarBox: {
    width: 68,
    height: 68,
    borderRadius: 20,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 18,
  },
  avatarIconText: {
    fontSize: 28,
  },
  levelBadge: {
    position: "absolute",
    bottom: -6,
    alignSelf: "center",
    backgroundColor: "#eddfba",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  levelBadgeText: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  nameBlock: {
    flex: 1,
  },
  titleBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(62, 232, 181, 0.12)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    gap: 4,
    marginBottom: 4,
  },
  titleBadgeIcon: {
    fontSize: 10,
  },
  titleBadgeText: {
    color: "#2a9c7a",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  userNameText: {
    color: "#293541",
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 4,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  subMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  tierTag: {
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  tierTagText: {
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  botTag: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderColor: "#DCE1D7",
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  botTagText: {
    color: "#ed4343",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  lpText: {
    color: "#293541",
    fontSize: 9.5,
    fontWeight: "800",
  },
  sectionHeader: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  statsContainer: {
    marginBottom: 12,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 8,
  },
  statTile: {
    width: "48.5%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 10,
    gap: 10,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  statIcon: {
    fontSize: 18,
  },
  statNumber: {
    color: "#293541",
    fontSize: 15,
    fontWeight: "900",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  statCaption: {
    color: "#293541",
    fontSize: 7.5,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  intelStrip: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    marginBottom: 16,
    alignItems: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  intelCell: {
    flex: 1,
    alignItems: "center",
  },
  intelLabel: {
    color: "#293541",
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  intelValue: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 2,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  intelDivider: {
    width: 1,
    height: 20,
    backgroundColor: "#E2E8F0",
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
  },
  addFriendBtn: {
    flex: 1,
    backgroundColor: "#FFD66E",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  addFriendBtnText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  alreadyFriendBadge: {
    flex: 1,
    backgroundColor: "#E6F7F0",
    borderColor: "#34D399",
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  alreadyFriendText: {
    color: "#279f73",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  challengeBtn: {
    flex: 1,
    backgroundColor: "#3EE8B5",
    borderColor: "#20C997",
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  challengeBtnText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  pressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
});
