import { StyleSheet } from "react-native";
import { palette } from "@/shared/palette";

export const styles = StyleSheet.create({
  content: { flexGrow: 1, paddingBottom: 185 },
  header: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 14 },
  back: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  backText: { color: "#293541", fontSize: 26, lineHeight: 28, marginTop: -2, fontWeight: "400" },
  overline: { color: "#8c7540", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  pageTitle: { fontSize: 22, lineHeight: 24, marginTop: 1, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  totalBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: "rgba(255, 214, 110, 0.2)",
    borderWidth: 1.5,
    borderColor: "#F0C855",
    alignItems: "flex-end",
  },
  totalBadgeLabel: { color: "#98732c", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  totalBadgeText: { color: "#293541", fontSize: 11, fontWeight: "900" },

  toastCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: palette.gold,
    marginBottom: 14,
    gap: 10,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  toastTitle: { color: palette.gold, fontSize: 11, fontWeight: "900", letterSpacing: 0.5 },
  toastDesc: { color: palette.text, fontSize: 12, fontWeight: "800", marginTop: 2 },
  toastPillsRow: { flexDirection: "row", gap: 6, marginTop: 6, flexWrap: "wrap" },
  toastRewardPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "#FFF9E6",
    borderWidth: 1,
    borderColor: "#F0C855",
  },
  toastRewardText: { color: palette.gold, fontSize: 10, fontWeight: "900" },
  toastCloseBtn: { padding: 6 },
  toastCloseText: { color: palette.muted, fontSize: 18, fontWeight: "900" },

  summaryInner: { padding: 14 },
  summaryHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
  summaryKicker: { color: palette.gold, fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  summaryTitle: { color: palette.text, fontSize: 14, fontWeight: "900", marginTop: 2, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  progressTrack: { height: 8, borderRadius: 4, backgroundColor: "#E2E8F0", overflow: "hidden", marginBottom: 10, borderWidth: 1, borderColor: palette.bronzeBorder },
  progressFill: { height: "100%", borderRadius: 4 },
  summaryHint: { color: palette.muted, fontSize: 11, lineHeight: 15, fontWeight: "600" },

  tabFrame: {
    marginTop: 14,
    marginBottom: 14,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: palette.bronzeBorder,
    overflow: "hidden",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabContainer: {
    flexDirection: "row",
    gap: 4,
    padding: 4,
  },
  tabHit: { flex: 1 },
  tabButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: 12,
  },
  tabButtonActive: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.bronzeDark,
  },
  tabButtonText: { color: palette.muted, fontSize: 11, fontWeight: "900", letterSpacing: 0.3, flexShrink: 1 },
  tabButtonTextOn: { color: "#293541", fontSize: 11, fontWeight: "900", letterSpacing: 0.3, flexShrink: 1 },
  tabBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
  },
  tabBadgeOn: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: "#FFF0E8",
  },
  tabBadgeText: { color: palette.mutedGold, fontSize: 9, fontWeight: "900" },
  tabBadgeTextOn: { color: "#293541", fontSize: 9, fontWeight: "900" },

  sectionHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10, gap: 8 },
  sectionTitle: { color: palette.goldBright, fontSize: 12, fontWeight: "900", letterSpacing: 0.5, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  sectionMeta: { color: palette.muted, fontSize: 10, fontWeight: "900", letterSpacing: 0.4, flexShrink: 1, textAlign: "right" },

  missionList: { gap: 10, marginBottom: 20 },
  missionWrap: {
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  missionFrame: { borderRadius: 20, padding: 2.5 },
  missionCard: {
    padding: 12,
    borderRadius: 18,
    flexDirection: "row",
    gap: 10,
    borderWidth: 1,
  },

  infoBox: { flex: 1, minWidth: 0 },
  cardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 4, gap: 6 },
  missionTitle: { flex: 1, color: palette.text, fontSize: 14, fontWeight: "900", letterSpacing: 0.2, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  diffBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 7, borderWidth: 1 },
  diffBadgeText: { fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  missionDesc: { color: palette.muted, fontSize: 11, marginBottom: 8, lineHeight: 15, fontWeight: "600" },

  rewardBadgesRow: { flexDirection: "row", gap: 6, marginBottom: 10, flexWrap: "wrap" },
  rewardChipPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "rgba(62, 232, 181, 0.12)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  rewardChipText: { color: palette.emerald, fontSize: 9.5, fontWeight: "900" },
  rewardChipGold: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "#FFF9E6",
    borderWidth: 1,
    borderColor: "#F0C855",
  },
  rewardChipGoldText: { color: palette.gold, fontSize: 9.5, fontWeight: "900" },
  rewardChipShield: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "#E0F2FE",
    borderWidth: 1,
    borderColor: "#38BDF8",
  },
  rewardChipShieldText: { color: palette.gemBlue, fontSize: 9.5, fontWeight: "900" },

  cardTrack: { height: 7, borderRadius: 4, backgroundColor: "#E2E8F0", overflow: "hidden", marginBottom: 8, borderWidth: 1, borderColor: palette.bronzeBorder },
  cardFill: { height: "100%", borderRadius: 4 },

  cardFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  statusText: { color: palette.mutedGold, fontSize: 10.5, fontWeight: "800" },
  claimedBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "#F1F3EE",
    borderWidth: 1,
    borderColor: palette.bronzeBorder,
  },
  claimedText: { color: palette.muted, fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  inProgressPill: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "#F8FAF5",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  inProgressText: { color: palette.mutedGold, fontSize: 9.5, fontWeight: "800" },
  claimBtn: { minWidth: 128 },
  pressed: { opacity: 0.8, transform: [{ scale: 0.96 }] },
});
