import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  gameScroll: { flexGrow: 1, paddingBottom: 50 },
  gameHeader: {
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 5,
  },
  exitButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F5ED",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  soundToggleBtn: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F5ED",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  exitText: { color: "#293541", fontSize: 25, lineHeight: 25 },
  gameMode: { color: "#293541", fontSize: 11.5, fontWeight: "900", letterSpacing: 0.5 },
  gameCode: { color: "#54646B", fontSize: 9.5, marginTop: 2, fontWeight: "800", letterSpacing: 0.5 },
  liveChip: {
    backgroundColor: "rgba(6, 182, 212, 0.15)",
    borderRadius: 99,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 9,
    paddingVertical: 6,
    gap: 5,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  liveDot: { width: 6, height: 6, borderRadius: 5, backgroundColor: "#F0F5ED" },
  liveText: { color: "#2a9c7a", fontSize: 10, fontWeight: "900", letterSpacing: 0.5 },
  offlineBanner: {
    marginTop: 6,
    marginBottom: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#FEE2E2",
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#FCA5A5",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  offlineText: { color: "#991B1B", fontSize: 11.5, fontWeight: "900" },
  statusRail: {
    marginTop: 7,
    minHeight: 48,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusRailFinal: { backgroundColor: "#FFF0E8", borderColor: "#DCE1D7" },
  railLabel: { color: "#54646B", fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  timerValue: {
    color: "#293541",
    fontSize: 19,
    lineHeight: 21,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginTop: 1,
  },
  timerValueFinal: { color: "#9c656c" },
  battleBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 5,
    maxWidth: "64%",
  },
  multiplierBadge: {
    backgroundColor: "rgba(234, 179, 8, 0.15)",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  multiplierText: { color: "#817a46", fontSize: 9.5, fontWeight: "900", letterSpacing: 0.4 },
  streakBadge: {
    backgroundColor: "#F0F5ED",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  streakText: { color: "#5b8571", fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  scoreRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 7 },
  floatingEmoteBadge: {
    position: "absolute",
    zIndex: 99,
    top: -14,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  floatingEmoteText: { fontSize: 22 },
  vsMark: { width: 28, alignItems: "center" },
  vsText: { color: "#293541", fontSize: 10, fontWeight: "900" },
  duelBattleHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    marginBottom: 6,
    gap: 6,
    width: "100%",
  },
  duelPlayerBadge: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1.5,
    paddingVertical: 6,
    paddingHorizontal: 8,
    gap: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  duelPlayerBadgeMe: {
    borderColor: "#A7F3D0",
  },
  duelPlayerBadgeOpponent: {
    borderColor: "#FECDD3",
  },
  duelAvatarCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F8FAFC",
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  duelAvatarEmoji: {
    fontSize: 16,
  },
  duelPlayerInfo: {
    flex: 1,
    justifyContent: "center",
  },
  duelPlayerInfoRight: {
    flex: 1,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  duelPlayerName: {
    fontSize: 10.5,
    fontWeight: "900",
    color: "#1E293B",
    letterSpacing: 0.2,
    marginBottom: 1,
  },
  duelScoreRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
  },
  duelScoreText: {
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 20,
  },
  duelWordBadge: {
    fontSize: 9,
    fontWeight: "800",
    color: "#64748B",
  },
  duelCenterHub: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 70,
  },
  duelTimerPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CBD5E1",
    gap: 3,
  },
  duelTimerPillFinal: {
    backgroundColor: "#FEE2E2",
    borderColor: "#FCA5A5",
  },
  duelTimerIcon: {
    fontSize: 11,
  },
  duelTimerValue: {
    fontSize: 13,
    fontWeight: "900",
    color: "#0F172A",
  },
  duelTimerValueFinal: {
    color: "#DC2626",
  },
  duelLeadBadge: {
    marginTop: 2,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
  },
  duelLeadAhead: {
    backgroundColor: "#ECFDF5",
  },
  duelLeadBehind: {
    backgroundColor: "#FEF2F2",
  },
  duelLeadText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.3,
  },
  duelSubBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    marginBottom: 6,
    width: "100%",
  },
  duelTargetPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  duelTargetIcon: {
    fontSize: 13,
  },
  duelTargetText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#475569",
    letterSpacing: 0.3,
  },
  compactEmoteMiniBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#E2E8F0",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  miniEmoteBtn: {
    padding: 2,
  },
  miniEmoteText: {
    fontSize: 15,
  },
  targetCard: { alignItems: "center", paddingTop: 15, paddingBottom: 11 },
  targetLabel: { color: "#293541", fontSize: 10, fontWeight: "900", letterSpacing: 0.5 },
  targetWord: {
    color: "#0faa77",
    fontSize: 29,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginTop: 2,
  },
  disconnectBox: {
    marginTop: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: "rgba(239, 68, 68, 0.2)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
  },
  targetTip: {
    color: "#293541",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 4,
    maxWidth: "100%",
    paddingHorizontal: 12,
    textAlign: "center",
  },
  board: {
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: "#F0F5ED",
    borderRadius: 26,
    padding: 4,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    overflow: "hidden",
    userSelect: "none",
    touchAction: "none",
  } as any,
  wordTray: {
    minHeight: 82,
    marginTop: 12,
    borderRadius: 20,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  wordTrayInvalid: { borderColor: "#DCE1D7", backgroundColor: "#FFF0E8" },
  wordTrayAccepted: { borderColor: "#DCE1D7", backgroundColor: "#F0F5ED" },
  wordTrayBonus: { borderColor: "#FACC15", backgroundColor: "#FEF9C3" },
  wordLabel: { color: "#293541", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  drawnWord: {
    color: "#293541",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginTop: 3,
  },
  drawnWordEmpty: { color: "#293541", fontSize: 10, letterSpacing: 0.5 },
  routeHint: { color: "#293541", fontSize: 8, fontWeight: "800", marginTop: 3 },
  wordActions: { position: "absolute", right: 10, top: 19, gap: 8, alignItems: "flex-end" },
  clearWord: { paddingVertical: 2 },
  clearWordText: { color: "#ef3e5c", fontSize: 9, fontWeight: "900" },
  submitWord: {
    backgroundColor: "#aef5e0",
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  submitWordText: { color: "#293541", fontSize: 9, fontWeight: "900" },
  disabledButton: { opacity: 0.46 },
  activeRouteCard: {
    marginTop: 10,
    borderRadius: 18,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    padding: 14,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  activeRouteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  activeRouteTitle: { color: "#293541", fontSize: 12, fontWeight: "900", letterSpacing: 0.5 },
  activeRouteBadge: {
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  activeRouteBadgeText: { fontSize: 10, fontWeight: "900" },
  activeRouteClose: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  activeRouteCloseText: { color: "#9c6666", fontSize: 10, fontWeight: "800" },
  activeRouteFlow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 5,
    paddingVertical: 4,
  },
  activeRouteChip: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF4FC",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 10,
    minWidth: 36,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  activeRouteChipStart: { backgroundColor: "#F0F5ED", borderColor: "#DCE1D7", borderWidth: 1.5 },
  activeRouteChipEnd: {
    backgroundColor: "rgba(220, 38, 38, 0.25)",
    borderColor: "#DCE1D7",
    borderWidth: 1.5,
  },
  activeRouteChipText: { color: "#293541", fontSize: 14, fontWeight: "900" },
  activeRouteChipTextStart: { color: "#279f73" },
  activeRouteChipTextEnd: { color: "#bf5757" },
  activeRouteChipSub: { color: "#293541", fontSize: 8, fontWeight: "800", marginTop: 1 },
  activeRouteArrow: { fontSize: 14, fontWeight: "900", marginHorizontal: 1 },
  activeRouteDefBox: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#DCE1D7",
  },
  activeRouteDefLabel: {
    color: "#219d8d",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  activeRouteDefText: {
    color: "#293541",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 2,
    fontWeight: "500",
  },
  foundPanel: {
    marginTop: 9,
    borderRadius: 16,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    padding: 12,
  },
  foundLabel: { color: "#293541", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  routeExploreHint: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 4,
    marginBottom: 2,
    textAlign: "center",
  },
  foundTags: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 4 },
  foundTag: {
    backgroundColor: "#EDF4FC",
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  foundTagText: { color: "#293541", fontSize: 11, fontWeight: "900" },
  foundTagMissedText: { color: "#9c6666", fontSize: 11, fontWeight: "900" },
  foundEmpty: { color: "#293541", fontSize: 11 },
  resultPanel: { alignItems: "center", marginTop: 10 },
  resultTitle: { color: "#293541", fontSize: 17, fontWeight: "900", letterSpacing: 0.2 },
  resultCopy: { color: "#293541", fontSize: 12, marginTop: 3 },
  viewResultsButton: {
    marginTop: 10,
    marginBottom: 6,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "rgba(62, 232, 181, 0.15)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    alignSelf: "stretch",
  },
  viewResultsButtonText: {
    color: "#2a9c7a",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  primaryButton: {
    marginTop: 18,
    height: 58,
    backgroundColor: "#faebc3",
    borderRadius: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 2,
    borderColor: "#DCE1D7",
  },
  rematchButton: { alignSelf: "stretch", marginTop: 8, height: 46 },
  primaryButtonText: { color: "#293541", fontSize: 14, fontWeight: "900", letterSpacing: 0.5 },
  primaryButtonArrow: { color: "#293541", fontSize: 24, fontWeight: "600" },
  returnHomeButton: {
    marginTop: 10,
    height: 48,
    alignSelf: "stretch",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  returnHomeButtonText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  notice: {
    color: "#293541",
    textAlign: "center",
    fontSize: 12,
    lineHeight: 18,
    marginTop: 15,
    paddingHorizontal: 15,
  },
  pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
});
