import { Pressable, StyleSheet, Text, View } from "react-native";

import { AVATARS, badgesFor, type AvatarId, type PlayerProgress } from "@/shared/progression";

export function PlayerCollection({ progress, onSelectAvatar }: { progress: PlayerProgress; onSelectAvatar: (avatar: AvatarId) => void }) {
  const badges = badgesFor(progress);
  return <View style={styles.root}>
    <View style={styles.sectionTop}><View><Text style={styles.kicker}>KİMLİK KASASI</Text><Text style={styles.title}>AVATARIN</Text></View><Text style={styles.count}>{badges.filter((badge) => badge.unlocked).length}/{badges.length} ROZET</Text></View>
    <View style={styles.avatarGrid}>{AVATARS.map((avatar) => { const selected = avatar.id === progress.selectedAvatar; return <Pressable key={avatar.id} onPress={() => onSelectAvatar(avatar.id)} style={({ pressed }) => [styles.avatarCard, { backgroundColor: avatar.surface, borderColor: selected ? avatar.color : "#403664" }, selected && { shadowColor: avatar.color, shadowOpacity: 0.38, shadowRadius: 10, elevation: 5 }, pressed && styles.pressed]}><Text style={[styles.avatarGlyph, { color: avatar.color }]}>{avatar.icon}</Text><Text style={[styles.avatarLabel, selected && { color: avatar.color }]}>{avatar.label}</Text>{selected && <View style={[styles.check, { backgroundColor: avatar.color }]}><Text style={styles.checkText}>✓</Text></View>}</Pressable>; })}</View>
    <Text style={styles.kicker}>BAŞARI ROZETLERİ</Text>
    <View style={styles.badgeGrid}>{badges.map((badge) => <View key={badge.id} style={[styles.badge, badge.unlocked ? { borderColor: badge.accent, backgroundColor: "#211B3E" } : styles.badgeLocked]}><Text style={[styles.badgeIcon, { color: badge.unlocked ? badge.accent : "#766D89" }]}>{badge.unlocked ? badge.icon : "◇"}</Text><View style={styles.badgeCopy}><Text style={[styles.badgeTitle, !badge.unlocked && styles.badgeTitleLocked]}>{badge.title}</Text><Text style={styles.badgeDescription}>{badge.unlocked ? badge.description : "Kilitli · görevi tamamla"}</Text></View></View>)}</View>
  </View>;
}

const styles = StyleSheet.create({
  root: { marginTop: 14 }, sectionTop: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 10 }, kicker: { color: "#AFA3C5", fontSize: 8, fontWeight: "900", letterSpacing: 1.1 }, title: { color: "#FFF9FC", fontSize: 17, fontWeight: "900", marginTop: 3 }, count: { color: "#55E6B2", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 }, avatarGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 17 }, avatarCard: { width: "31.6%", minHeight: 83, borderRadius: 16, borderWidth: 1, alignItems: "center", justifyContent: "center", position: "relative" }, avatarGlyph: { fontSize: 25, fontWeight: "900" }, avatarLabel: { color: "#DAD3E8", fontSize: 7, fontWeight: "900", letterSpacing: 0.5, marginTop: 6 }, check: { position: "absolute", top: 6, right: 6, width: 15, height: 15, borderRadius: 7.5, alignItems: "center", justifyContent: "center" }, checkText: { color: "#121025", fontSize: 9, fontWeight: "900" }, badgeGrid: { gap: 8, marginTop: 9 }, badge: { minHeight: 58, borderRadius: 15, borderWidth: 1, padding: 10, flexDirection: "row", alignItems: "center", gap: 10 }, badgeLocked: { backgroundColor: "#19152D", borderColor: "#393151", opacity: 0.72 }, badgeIcon: { width: 29, textAlign: "center", fontSize: 19, fontWeight: "900" }, badgeCopy: { flex: 1 }, badgeTitle: { color: "#F6F1FF", fontSize: 10, fontWeight: "900", letterSpacing: 0.5 }, badgeTitleLocked: { color: "#A79CB7" }, badgeDescription: { color: "#B8ADD1", fontSize: 9, marginTop: 3 }, pressed: { opacity: 0.78, transform: [{ scale: 0.97 }] },
});
