import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  content: { paddingHorizontal: 14, paddingTop: 10, paddingBottom: 210, flexGrow: 1 },
  header: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 20 },
  back: { width: 38, height: 38, borderRadius: 14, backgroundColor: "#F0F5ED", borderWidth: 1, borderColor: "#DCE1D7", alignItems: "center", justifyContent: "center" },
  backText: { color: "#293541", fontSize: 26, lineHeight: 28 },
  overline: { color: "#8c7540", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  title: { color: "#293541", fontSize: 26, fontWeight: "900", marginTop: 2, letterSpacing: 0.5, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },

  sectionTitle: { color: "#293541", fontSize: 12, fontWeight: "900", letterSpacing: 0.5, marginTop: 10, marginBottom: 16 },

  // Grid Map
  gridContainer: {
    paddingHorizontal: 8,
    marginBottom: 24,
  },
  gridRowWrap: {
    position: "relative",
    marginBottom: 28,
  },
  gridRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 8,
    zIndex: 10,
  },
  rowConnector: {
    position: "absolute",
    left: 40,
    right: 40,
    top: 25,
    height: 2,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    zIndex: 1,
  },
  verticalConnector: {
    position: "absolute",
    top: 25,
    bottom: -32,
    width: 2,
    left: "50%",
    marginLeft: -1,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    zIndex: 1,
  },
  nodeWrapper: {
    alignItems: "center",
  },
  nodeCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#EDF4FC",
    borderWidth: 2,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    zIndex: 5,
  },
  nodeCompleted: {
    backgroundColor: "rgba(80, 227, 194, 0.08)",
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  nodeCurrent: {
    backgroundColor: "rgba(255, 194, 74, 0.1)",
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    transform: [{ scale: 1.05 }],
  },
  nodeSelected: {
    borderColor: "#DCE1D7",
    borderWidth: 3,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    transform: [{ scale: 1.1 }],
  },
  nodeLocked: {
    backgroundColor: "#EDF4FC",
    borderColor: "#DCE1D7",
    opacity: 0.6,
  },
  nodeText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#687796",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  nodeTextCompleted: {
    color: "#349d5a",
  },
  nodeTextCurrent: {
    color: "#98732c",
  },
  nodeTextSelected: {
    color: "#2a9c7a",
  },
  nodeTextLocked: {
    fontSize: 12,
  },
  nodeLabel: {
    fontSize: 8,
    fontWeight: "900",
    color: "#293541",
    marginTop: 6,
    letterSpacing: 0.5,
  },
  nodeLabelSelected: {
    color: "#2a9c7a",
  },
  nodeLabelLocked: {
    color: "#293541",
  },

  // Docked Mission Deck Details Card
  dockedDeck: {
    backgroundColor: "#F0F5ED",
    borderTopWidth: 1.5,
    borderTopColor: "#DCE1D7",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 92,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  deckHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  deckKicker: {
    color: "#98732c",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  deckTitle: {
    color: "#293541",
    fontSize: 14,
    fontWeight: "900",
    marginTop: 4,
    letterSpacing: 0.5,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    borderWidth: 1,
  },
  badgeLocked: {
    backgroundColor: "#EDF4FC",
    borderColor: "#DCE1D7",
  },
  badgeActive: {
    backgroundColor: "#FFF0E8",
    borderColor: "#DCE1D7",
  },
  badgeCompleted: {
    backgroundColor: "#F0F5ED",
    borderColor: "#DCE1D7",
  },
  statusBadgeText: {
    fontSize: 7,
    fontWeight: "900",
    color: "#293541",
    letterSpacing: 0.5,
  },
  deckInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    paddingVertical: 12,
    paddingHorizontal: 8,
    marginBottom: 20,
  },
  infoCol: {
    flex: 1,
    alignItems: "center",
  },
  infoLabel: {
    color: "#293541",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  infoValue: {
    color: "#293541",
    fontSize: 14,
    fontWeight: "900",
    marginTop: 4,
  },
  infoDivider: {
    width: 1,
    height: 20,
    backgroundColor: "rgba(212, 180, 90, 0.2)",
  },
  launchButton: {
    height: 48,
    borderRadius: 16,
    backgroundColor: "#aef5e0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  launchButtonLocked: {
    backgroundColor: "#F0F5ED",
    borderColor: "#DCE1D7",
    borderWidth: 1.5,
    shadowOpacity: 0,
    elevation: 0,
  },
  launchText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  launchTextLocked: {
    color: "#293541",
  },
  launchArrow: {
    color: "#293541",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 22,
  },
  pressed: {
    opacity: 0.86,
    transform: [{ scale: 0.98 }],
  },
  milestoneWrap: {
    marginVertical: 10,
    width: "100%",
  },
  milestoneBox: {
    backgroundColor: "#EDF4FC",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  milestoneBoxReady: {
    borderColor: "#F0C855",
    backgroundColor: "#FFF9E6",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  milestoneBoxClaimed: {
    borderColor: "#A7F3D0",
    backgroundColor: "#E8F8F0",
  },
  milestoneIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#F7F5EE",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 0,
  },
  milestoneIcon: {
    fontSize: 22,
  },
  milestoneTitle: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  milestoneBadge: {
    color: "#349d5a",
    fontSize: 9,
    fontWeight: "900",
    backgroundColor: "rgba(80, 227, 194, 0.15)",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
  },
  milestoneDesc: {
    color: "#293541",
    fontSize: 10,
    marginTop: 2,
  },
  milestoneRewardText: {
    color: "#98732c",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 3,
  },
  milestoneBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  milestoneBtnReady: {
    backgroundColor: "#ffe5b3",
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  milestoneBtnClaimed: {
    backgroundColor: "rgba(80, 227, 194, 0.1)",
    borderColor: "#DCE1D7",
  },
  milestoneBtnText: {
    color: "#293541",
    fontSize: 10,
    fontWeight: "900",
  },

  livesPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
  },
  livesIcon: { fontSize: 13 },
  livesText: { color: "#1daa51", fontSize: 12, fontWeight: "900" },
  livesInfoBadge: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#a2e7bb",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 2,
  },
  livesInfoText: { color: "#293541", fontSize: 10, fontWeight: "900", marginTop: -1 },
});
