import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: { flexGrow: 1, paddingHorizontal: 14, paddingTop: 8, paddingBottom: 28 },
  header: { height: 52, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  exit: {
    width: 35,
    height: 35,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  exitText: { color: "#293541", fontSize: 23, lineHeight: 23 },
  kicker: { fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  title: { color: "#1E293B", fontSize: 14, fontWeight: "900", marginTop: 2 },
  timer: {
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1.5,
    position: "relative",
    overflow: "visible",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  timerUrgent: {
    backgroundColor: "#FEE2E2",
    borderColor: "#EF4444",
    shadowColor: "#EF4444",
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 4,
  },
  timerText: { color: "#DC2626", fontSize: 13, fontWeight: "900" },
  radarButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1.5,
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  radarUsedBtn: { opacity: 0.6 },
  radarText: { fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  bonusText: {
    position: "absolute",
    top: -18,
    right: 0,
    color: "#10B981",
    fontSize: 11,
    fontWeight: "900",
  },
  progress: { alignItems: "center", paddingVertical: 12 },
  progressLabel: { fontSize: 20, fontWeight: "900", letterSpacing: 0.5 },
  progressMeta: { fontSize: 9, fontWeight: "800", marginTop: 3 },
  board: {
    alignSelf: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    borderWidth: 2,
    borderRadius: 24,
    padding: 4,
    userSelect: "none",
    touchAction: "none",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  } as any,
  boardUrgent: {
    borderColor: "#EF4444",
    shadowColor: "#EF4444",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  cellWrap: { padding: 5 },
  cell: {
    flex: 1,
    borderRadius: 12,
    borderBottomWidth: 3.5,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    aspectRatio: 1,
  },
  cellSelected: {
    backgroundColor: "#FEF3C7",
    borderColor: "#F59E0B",
    borderBottomColor: "#D97706",
    borderWidth: 2,
    shadowColor: "#F59E0B",
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  cellTail: {
    backgroundColor: "#FDE68A",
    borderColor: "#D97706",
    borderBottomColor: "#B45309",
    borderWidth: 2.5,
    shadowColor: "#D97706",
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 6,
  },
  cellInvalid: {
    backgroundColor: "#FEE2E2",
    borderColor: "#EF4444",
    borderBottomColor: "#DC2626",
    borderWidth: 2,
    shadowColor: "#EF4444",
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 4,
  },
  cellAccepted: {
    backgroundColor: "#D1FAE5",
    borderColor: "#10B981",
    borderBottomColor: "#059669",
    borderWidth: 2,
    shadowColor: "#10B981",
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 5,
  },
  cellBonus: {
    backgroundColor: "#FEF9C3",
    borderColor: "#FACC15",
    borderBottomColor: "#EAB308",
    borderWidth: 2.5,
    shadowColor: "#EAB308",
    shadowOpacity: 0.65,
    shadowRadius: 8,
    elevation: 6,
  },
  cellFound: {
    backgroundColor: "#F1F5F9",
    borderColor: "#CBD5E1",
    borderBottomColor: "#94A3B8",
  },
  cellRadar: { backgroundColor: "#FEF3C7", borderColor: "#F59E0B", borderWidth: 2 },
  check: {
    position: "absolute",
    left: 4,
    bottom: 2,
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
  },
  solutionMark: {
    position: "absolute",
    left: 5,
    bottom: 1,
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
  },
  letter: { color: "#1E293B", fontSize: 25, fontWeight: "900" },
  letterMedium: { fontSize: 21 },
  letterSmall: { fontSize: 17 },
  letterExtraSmall: { fontSize: 13 },
  letterRadar: { color: "#B45309" },
  order: {
    position: "absolute",
    top: 3,
    right: 4,
    color: "#B45309",
    fontSize: 8,
    fontWeight: "900",
  },
  tray: {
    minHeight: 77,
    marginTop: 12,
    borderRadius: 20,
    borderWidth: 2,
    borderBottomWidth: 4,
    borderColor: "#E2E8F0",
    borderBottomColor: "#CBD5E1",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  trayInvalid: {
    backgroundColor: "#FEE2E2",
    borderColor: "#EF4444",
    borderBottomColor: "#DC2626",
  },
  trayAccepted: {
    backgroundColor: "#D1FAE5",
    borderColor: "#10B981",
    borderBottomColor: "#059669",
  },
  trayBonus: {
    backgroundColor: "#FEF9C3",
    borderColor: "#FACC15",
    borderBottomColor: "#EAB308",
  },
  trayLabel: { color: "#64748B", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  word: { color: "#0F172A", fontSize: 20, fontWeight: "900", letterSpacing: 0.5, marginTop: 3 },
  hint: { color: "#64748B", fontSize: 9, textAlign: "center", marginTop: 3 },
  found: {
    marginTop: 10,
    padding: 11,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E2E8F0",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  foundLabel: { fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  tags: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 7 },
  tag: {
    borderRadius: 9,
    paddingHorizontal: 9,
    paddingVertical: 4,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  tagText: { color: "#1E293B", fontSize: 10, fontWeight: "900" },
  empty: { color: "#64748B", fontSize: 10 },
  result: {
    marginTop: 10,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#FEF2F2",
    borderWidth: 1.5,
    borderColor: "#FCA5A5",
    alignItems: "center",
  },
  resultTitle: { color: "#991B1B", fontSize: 16, fontWeight: "900" },
  resultCopy: { color: "#7F1D1D", fontSize: 11, textAlign: "center", marginTop: 4 },
  solutionLegend: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
    marginTop: 9,
  },
  solutionTag: { borderRadius: 8, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 4 },
  solutionTagText: { color: "#1E293B", fontSize: 9, fontWeight: "900", letterSpacing: 0.4 },
  action: {
    height: 44,
    alignSelf: "stretch",
    marginTop: 12,
    borderRadius: 14,
    paddingHorizontal: 14,
    backgroundColor: "#FEE2E2",
    borderWidth: 1,
    borderColor: "#FCA5A5",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  actionText: { color: "#991B1B", fontSize: 11, fontWeight: "900", letterSpacing: 0.5 },
  actionArrow: { color: "#991B1B", fontSize: 20, fontWeight: "900" },
  activeRouteCard: {
    marginTop: 10,
    borderRadius: 18,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    padding: 14,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  activeRouteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  activeRouteTitle: { color: "#293541", fontSize: 12, fontWeight: "900", letterSpacing: 0.5 },
  activeRouteBadge: {
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  activeRouteBadgeText: { fontSize: 10, fontWeight: "900" },
  activeRouteClose: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  activeRouteCloseText: { color: "#9c6666", fontSize: 10, fontWeight: "800" },
  activeRouteFlow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 5,
    paddingVertical: 4,
  },
  activeRouteChip: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EDF4FC",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 10,
    minWidth: 36,
    paddingHorizontal: 6,
    paddingVertical: 4,
  },
  activeRouteChipStart: { backgroundColor: "#F0F5ED", borderColor: "#DCE1D7", borderWidth: 1.5 },
  activeRouteChipEnd: {
    backgroundColor: "rgba(220, 38, 38, 0.25)",
    borderColor: "#DCE1D7",
    borderWidth: 1.5,
  },
  activeRouteChipText: { color: "#293541", fontSize: 14, fontWeight: "900" },
  activeRouteChipTextStart: { color: "#279f73" },
  activeRouteChipTextEnd: { color: "#bf5757" },
  activeRouteChipSub: { color: "#293541", fontSize: 8, fontWeight: "800", marginTop: 1 },
  activeRouteArrow: { fontSize: 14, fontWeight: "900", marginHorizontal: 1 },
  activeRouteDefBox: { marginTop: 10, paddingTop: 8, borderTopWidth: 1, borderTopColor: "#DCE1D7" },
  activeRouteDefLabel: { color: "#219d8d", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  activeRouteDefText: { color: "#293541", fontSize: 12, lineHeight: 18, marginTop: 2, fontWeight: "500" },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  modalContent: {
    width: "86%",
    borderRadius: 20,
    borderWidth: 1.5,
    padding: 22,
    alignItems: "center",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  modalTitle: { fontSize: 22, fontWeight: "900", letterSpacing: 0.5, marginBottom: 12 },
  modalBody: {
    color: "#293541",
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
    marginBottom: 20,
    fontWeight: "600",
  },
  modalCloseButton: {
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  modalCloseText: { color: "#293541", fontSize: 12, fontWeight: "900", letterSpacing: 0.5 },
  chestCard: {
    width: "100%",
    marginTop: 12,
    padding: 16,
    borderRadius: 16,
    borderStyle: "dashed",
    borderWidth: 1.5,
    borderColor: "#E6D5A8",
    backgroundColor: "#FFFBF0",
    alignItems: "center",
  },
  chestIcon: { fontSize: 36, marginBottom: 8 },
  chestTitle: { color: "#293541", fontSize: 11, fontWeight: "900", letterSpacing: 0.5, textAlign: "center" },
  chestCopy: {
    color: "#293541",
    fontSize: 8,
    textAlign: "center",
    marginTop: 4,
    lineHeight: 11,
    paddingHorizontal: 12,
  },
  chestButton: { marginTop: 12, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 10 },
  chestButtonText: { color: "#293541", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  chestProgress: {
    color: "#98732c",
    fontSize: 10,
    fontWeight: "900",
    fontFamily: "monospace",
    marginTop: 8,
    letterSpacing: 0.5,
  },
  chestSuccessReward: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.4,
    textAlign: "center",
    marginTop: 6,
  },
  pauseBtn: {
    width: 35,
    height: 35,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 6,
  },
  pauseOverlay: {
    flex: 1,
    backgroundColor: "rgba(35, 48, 59, 0.55)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  pauseCard: {
    width: "100%",
    maxWidth: 360,
    maxHeight: "85%",
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    overflow: "hidden",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  pauseTitle: { color: "#293541", fontSize: 18, fontWeight: "900", letterSpacing: 0.5, marginBottom: 8 },
  pauseSub: { color: "#293541", fontSize: 12, textAlign: "center", lineHeight: 18, marginBottom: 20 },
  resumeBtn: {
    width: "100%",
    height: 46,
    borderRadius: 14,
    backgroundColor: "#FFD66E",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  resumeBtnText: { color: "#293541", fontSize: 12, fontWeight: "900", letterSpacing: 0.5 },
  pauseSoundBtn: {
    width: "100%",
    height: 42,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  pauseSoundBtnText: { color: "#293541", fontSize: 11, fontWeight: "900", letterSpacing: 0.4 },
  pauseExitBtn: {
    width: "100%",
    height: 42,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    backgroundColor: "#F7F5EE",
    alignItems: "center",
    justifyContent: "center",
  },
  pauseExitBtnText: { color: "#293541", fontSize: 11, fontWeight: "800", letterSpacing: 0.4 },
  adOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 300,
  },
  adTitle: { color: "#8c763b", fontSize: 10, fontWeight: "900", letterSpacing: 0.5, marginBottom: 12 },
  adSpinner: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
    paddingHorizontal: 28,
    lineHeight: 18,
  },
  adCountdown: {
    color: "#2a9c7a",
    fontSize: 48,
    fontWeight: "900",
    marginTop: 24,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
});
