import { StyleSheet } from "react-native";

export const onboardingStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 20,
  },
  container: {
    width: "100%",
    height: "92%",
    maxHeight: 720,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
    overflow: "hidden",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
  },
  headerKickerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  badgeText: {
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  sectionPill: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 8,
    borderWidth: 1,
  },
  sectionPillText: {
    fontSize: 8.5,
    fontWeight: "900",
  },
  headerTitle: {
    color: "#293541",
    fontSize: 13.5,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginTop: 3,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255, 100, 124, 0.15)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  closeText: {
    color: "#ca4f62",
    fontSize: 14,
    fontWeight: "900",
  },

  tabsContainer: {
    backgroundColor: "#F0F5ED",
    borderBottomWidth: 1,
    borderBottomColor: "#DCE1D7",
    paddingVertical: 8,
  },
  tabsScroll: {
    paddingHorizontal: 14,
    gap: 8,
  },
  tabChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  tabChipActive: {
    borderWidth: 1.5,
  },
  tabChipIcon: {
    fontSize: 13,
  },
  tabChipText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.3,
  },

  contentScroll: {
    padding: 16,
    gap: 12,
  },
  bannerCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  iconCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  bannerIcon: {
    fontSize: 22,
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.5,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  sectionDescription: {
    color: "#293541",
    fontSize: 10.5,
    lineHeight: 15,
    marginTop: 2,
  },

  visualCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  visualLabel: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  routeExampleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  exampleCol: {
    flex: 1,
    alignItems: "center",
  },
  exampleDivider: {
    width: 1,
    height: 48,
    backgroundColor: "rgba(212, 180, 90, 0.3)",
    marginHorizontal: 8,
  },
  miniBoardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 6,
  },
  miniCell: {
    width: 26,
    height: 26,
    borderRadius: 6,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  miniCellActive: {
    backgroundColor: "rgba(62, 232, 181, 0.15)",
    borderColor: "#DCE1D7",
  },
  miniCellInvalid: {
    backgroundColor: "rgba(255, 100, 124, 0.15)",
    borderColor: "#DCE1D7",
  },
  miniLetter: {
    color: "#2a9c7a",
    fontSize: 12,
    fontWeight: "900",
  },
  miniArrow: {
    color: "#2a9c7a",
    fontSize: 12,
    fontWeight: "900",
  },
  validStatusText: {
    color: "#2a9c7a",
    fontSize: 8.5,
    fontWeight: "900",
  },
  invalidStatusText: {
    color: "#ca4f62",
    fontSize: 8.5,
    fontWeight: "900",
  },

  modesPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  modeMiniBadge: {
    flex: 1,
    minWidth: 100,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    alignItems: "center",
  },
  modeMiniBadgeTitle: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  modeMiniBadgeSub: {
    color: "#293541",
    fontSize: 8,
    fontWeight: "700",
    marginTop: 2,
  },

  leaguesRow: {
    flexDirection: "row",
    gap: 4,
    width: "100%",
  },
  leagueChip: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    alignItems: "center",
  },
  leagueChipIcon: {
    fontSize: 13,
  },
  leagueChipTitle: {
    fontSize: 8,
    fontWeight: "900",
    marginTop: 2,
  },
  leagueChipLp: {
    color: "#293541",
    fontSize: 7,
    fontWeight: "700",
    marginTop: 1,
  },

  rewardsStripCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 16,
    padding: 10,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  rewardPillsRow: {
    flexDirection: "row",
    gap: 4,
    width: "100%",
  },
  rewardMiniPill: {
    flex: 1,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
  },
  rewardMiniPillEpic: {
    borderColor: "#DCE1D7",
    backgroundColor: "rgba(255, 208, 0, 0.12)",
  },
  rewardMiniIcon: {
    fontSize: 11,
  },
  rewardMiniDay: {
    color: "#293541",
    fontSize: 7.5,
    fontWeight: "800",
    marginTop: 1,
  },
  rewardMiniAmt: {
    color: "#293541",
    fontSize: 8,
    fontWeight: "900",
  },

  multipliersCard: {
    flexDirection: "row",
    gap: 8,
    width: "100%",
  },
  multiplierItem: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
  },
  multiplierBadge: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  multiplierValue: {
    color: "#293541",
    fontSize: 16,
    fontWeight: "900",
    marginVertical: 2,
  },
  multiplierSub: {
    color: "#293541",
    fontSize: 7.5,
    fontWeight: "700",
  },

  blocksList: {
    gap: 10,
    marginTop: 4,
  },
  blockCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 16,
    padding: 13,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  blockHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  blockTitle: {
    color: "#293541",
    fontSize: 12.5,
    fontWeight: "900",
    letterSpacing: 0.4,
    flex: 1,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  blockTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
  },
  blockTagText: {
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 4,
  },
  detailBullet: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: "900",
  },
  detailText: {
    flex: 1,
    color: "#293541",
    fontSize: 10.5,
    lineHeight: 15.5,
    fontWeight: "500",
  },

  footer: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
  },
  indicatorRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
    marginBottom: 10,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(212, 180, 90, 0.3)",
  },
  dotActive: {
    width: 18,
    height: 6,
    borderRadius: 3,
  },
  footerButtonsRow: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  prevBtn: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
    alignItems: "center",
    justifyContent: "center",
  },
  prevBtnText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  nextBtn: {
    flex: 1.5,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  nextBtnText: {
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  finishBtn: {
    backgroundColor: "#aef5e0",
  },
  finishBtnText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
});
