import catalog from "../data/word-catalog.json";

export type WordDifficulty = "easy" | "medium" | "hard";
export type WordTheme = "general" | "nature" | "city" | "mind" | "space" | "sports" | "food";

export type WordEntry = {
  word: string;
  difficulty: WordDifficulty;
  boards: number[];
  tags: WordTheme[];
  weight: number;
};

type CatalogPayload = { version: number; words: WordEntry[] };

const WORD_BLACKLIST = new Set([
  // --- Kullanıcı tarafından bildirilen ve filtrelenen saçma / argo / tıbbi / küfür kelimeler ---
  "MABLAK", "DEBİL", "BASUR", "PEZEVENK", "DÜRZİ", "KAKA", "ÇİŞ", "MENİ", "ENİK", "DENYO", "APTAL", "SÜRTÜK", "DÖL", "KAHPE",
  "BASAK", "BASYA", "BASTIK", "BASİL", "DEBAGAT", "DEBBOY", "DEBBAĞ", "MABEYİN", "MABAT",
  "CÜZZAM", "FRENGİ", "TİFÜS", "KOLERA", "VEREM", "APANDİS", "VEBA", "GAYTA", "DIŞKI",
  "İSTİDA", "GARAMİ", "GAMBA", "TELKİH", "TEPİR", "TENVİR", "TEVKİL", "GALİZ", "TALİKA", "GAŞİY",
  "SUOKU", "MUTKİ", "KARGIN", "KAÇLI", "TEAMÜL", "OYDAŞ", "SPERM", "CİFE", "ORAL", "KİST", "YALAK",
  "CART", "CURT", "GÖVEK", "CEMAN", "YÜKÜN", "MOLAS", "EMMEÇ", "MARİZ", "CİHET", "GÜRE", "AYAŞ",
  "MİSO", "MUTİ", "VİDO", "UĞRU", "BARI", "İLGEÇ", "BÜGDÜZ", "TARAŞ", "MANZUM", "APOLET", "MARAZİ", "TAYF",
  "CÜNÜP", "ZİNA", "LİVATA", "GUSÜL", "ŞEHVET", "HADIM", "CİNSİ", "TENASÜL", "MECUSİ", "ZINDIK",
  "KAFİR", "MÜNAFIK", "MÜRTED", "HALVET", "LAHURİ", "UYUNTU", "SARALI", "TAYLAK", "BADAS", "ZİYALI",
  "İPTİDA", "BARUDİ", "HİTAM", "CEMŞAT", "TERHİN", "PASTAL", "NAKIS", "KAZAĞI", "KÖTEK", "DURAL",
  "KOKOT", "FODRA", "HABEŞ", "ERDİŞİ", "HAİLE", "İZOBAR", "MUNZAM", "HAYBE", "GARPLI", "KOVUŞ", "İLENİŞ", "CÜCÜK", "DAYANÇ", "KARİNA",
  "BOMBOK", "TIRKAZ", "ALBATR", "HÜRLE", "TİMBAL", "GENZEL", "BOALAR", "SERGİN", "KESENE",

  // --- Kullanıcı Talebiyle Çıkarılan Kelimeler (Özel İsimler, Yabancı Kelimeler, Garip Ekler vb.) ---
  "SAÇMACILIK", "SADAKOR", "SANGILIK", "SAPARTA", "SARAK", "SARAYPATI", "SARIFİĞ", "SAVURTUŞ", "SAYRIMSAK", "SEBAYÜDÜ",
  "SEFİHANE", "SELZEDE", "SENEVİ", "SERAK", "SERAPA", "SERÇİN", "SEYYİBE", "SİNCABİ", "SİNYORA", "SİNTİNE",
  "SÖMİKOK", "SÖVÜNTÜ", "SPİRİL", "STEYŞIN", "SÜBEKLİ", "SÜNDÜS", "SÜRFİLE", "TAHRİLLİ", "TAHTALIKÖY", "TATARI",
  "TATBİLİR", "TELEKIZ", "TELEÜT", "TEMBUL", "TEPHİRHANE", "TERSBEŞİK", "TIKNAZLIK", "TIKSIRIKLI", "TIMTIKIZ", "TINGADAK",
  "TİRAMOLA", "TÖSKÜRÜ", "TRİNKETA", "TRİŞİN", "TUTARGA", "TUTÇEK", "TÜNAYDIN", "TÜYTOP", "UFUNETLİ", "ULUHİYET",
  "UNUTMABENİ", "USSALLIK", "UYLAŞIM", "UZUNEŞEK", "ÜÇÇATAL", "ÜÇTELLİ", "ÜSKÜRE", "ÜZÜMGÜNEŞİ", "VABESTE", "VANDÖZ",
  "VARSANI", "VECTLİ", "VINILTI", "VİSAMİRAL", "VİZİYER", "VURTUT", "YALAPŞAP", "YALBIRDAK", "YAMYAŞ", "YANŞAK",
  "YAPAĞILI", "YAPINCAK", "YAPYAKIN", "YARPUZ", "YAYINİSPİ", "YAYLAKİYE", "YAYVANLIK", "YEĞREK", "YEMİŞÇİL", "YERİNEL",
  "YİDDİŞ", "YORDAMSIZ", "YÜREGİR", "ZAMKIARABİ", "ZEPHİYE", "ZIBARIŞ", "ZIMNINDA", "ZINGADAK", "ZIYPAK", "ZİVİRCİK",
  "ZİYADAR", "ZÜRRA",
  "DOĞALLIK", "DOKTOR", "SARICALIK", "SAYRIL", "SETİK", "SETRİAVRET", "SINGIN", "SIRACALI", "SIRMAKEŞ", "SIRPLIK",
  "SIRSIKLAM", "SIVIRYA", "SIZAK", "SİCİLYALI", "SİGALA", "SİMSARİYE", "SÜREYAZAR", "ŞAHTUR", "ŞANGIRTI", "ŞANSONET",
  "ŞEBBOY", "ŞEBİARUS", "ŞEFİK", "ŞİİRİYET", "ŞOROLOP", "TAKINTISIZ", "TANTUNİ", "TAZİYEEVİ", "TEMRİYE", "TERAVİ",
  "TİLMİZ", "TONİLATO", "TUFANBEYLİ", "ULULAYIŞ", "URANÜS", "URUGUAYLI", "UŞŞAK", "ÜMRANLI", "VARGEL", "VENÜS",
  "YAĞILIK", "YALINÇ", "YOLBİL", "YUNUS", "YÜZERGEZER", "ZAHİRDE", "ZATIALİNİZ", "ZLOTİ", "ZÜLFİKAR",
  "UÇUKLAYIŞ", "UYARCILIK", "UYDURULUŞ", "UYDURUŞ", "VANLILIK", "VEREVİNE", "VERİNTİ", "VİRAJLI", "VUKUFLU", "YAĞIŞÖLÇER",
  "YANŞAKLIK", "YAPILANIŞ", "YARARLIK", "YARAŞIR", "YARAŞIRLIK", "YAŞARLIK", "YAŞMAKLI", "YAYLIM", "YAYINTI", "YAZINCILIK",
  "YEDİGİR", "YEĞİN", "YELTENİŞ", "YEMEKALTI", "YEMLİKLİ", "YENGİ", "YENİDÜNYA", "YIĞILI", "YIĞILIM", "YIĞILIŞ",
  "YILANKAVİ", "YILAŞIRI", "YIVIŞIK", "YOĞRUM", "YOKUŞSUZ", "YOLLU", "YORUMLANIŞ", "YUFKALIK", "YUVAR", "YÜCELİM",
  "YÜCELTİŞ", "YÜĞRÜK", "YÜZEYLİ", "ZANLILIK", "ZAVİYEVİ", "ZİKREDİLİŞ", "ZİYANSIZ", "ZÜLÜFLÜ", "ZÜRRİYETLİ",
  "UYARLANIŞ", "UYARLAYIŞ", "UYGULAYIŞ", "ÜNLENİŞ", "ÜNLÜLÜ", "ÜNSİYET", "ÜNSÜZLÜ", "ÜRETİLİŞ", "ÜRETİŞ", "ÜSTADANE",
  "ÜSTELENİŞ", "ÜSTELEYİŞ", "ÜSTLENİM", "ÜŞÜNTÜ", "ÜZENGİLİ", "VAKTİNDE", "VALLAHA", "VARILIŞ", "VARİYETLİ", "VASATİ",
  "VEKİLHARÇ", "VELİYULLAH", "YADIRGANIŞ", "YADIRGAYIŞ", "YAĞIŞLILIK", "YAKAMOZLU", "YAKINSAK", "YALVAÇLIK", "YAMYAMLIK", "YANARDÖNER",
  "YANGILI", "YANIKARA", "YANIŞÖLÇER", "YANSITIŞ", "YANSIYIŞ", "YANTUTMAZ", "YAPAĞI", "YAPAKÇILIK", "YARAYIŞLI", "YARDIRIŞ",
  "YARICILIK", "YARINTI", "YASAKLILIK", "YASTAĞAÇ", "YAVRUKURT", "YAYIMLANIŞ", "YAYIMLAYIŞ", "YAYINIM", "YAYMACILIK", "YAZDIRIM",
  "YAZDIRIŞ", "YEĞLEYİŞ", "YENİLEYİŞ", "YENİLİŞ", "YETİNİŞ", "YETİRİŞ", "YETİŞEK", "YETİŞMİŞ", "YETMİŞERLİ", "YIPRANIŞ",
  "YIPRATIŞ", "YIRTMAÇLI", "YUVARLACIK", "YUVARLAYIŞ", "ZAĞCILIK", "ZEBANİ", "ZERDE", "ZIRCAHİL", "ZIRDELİ",
  "ABASIZLIK", "ACEMKÜRDİ", "ACILILIK", "AÇIKLAYIŞ", "AÇIKLIKLA", "ADALILIK", "ADAMCAĞIZ", "ADAMCILLIK", "ADAŞLIK", "ADENİT",
  "ADLILIK", "AFALLAYIŞ", "AFOROZLU", "AFSUNLU", "AĞAÇSIZLIK", "AĞBENEK", "AĞCIK", "AĞDALANIŞ", "AĞIRLAYIŞ", "AĞIZSIZLIK",
  "AĞLAYIŞ", "AĞRAZ", "AĞYAR", "AHENKTAR", "AHIRDAŞ", "AKARET", "AKÇILLIK", "AKHARDAL", "AKILLANIŞ", "AKIMSIZLIK",
  "AKİLANE", "AKKEFAL", "AKPELİN", "AKROMATİN", "AKRONİM", "AKROPOL", "AKSATA", "AKSATILIŞ", "AKSETTİRİŞ", "AKSÖĞÜT",
  "AKSÜLAMEL", "AKTİNYUM", "AKTÜERYAL", "AKVAREL", "ALABANDA", "ALACALILIK", "ALAGARSON", "ALAVERE", "ALAYİŞ", "ALAYİŞLİ",
  "ALAYLILIK", "ALÇALTILIŞ", "ALDATILIŞ", "ALDEHİT", "ALELACELE", "ALELHUSUS", "ALELUMUM", "ALEVLENİŞ", "ALFENİT", "ALGARİNA",
  "ALGILAYIŞ", "ALIMLILIK", "ALOGAMİ", "ALPAKA", "ALŞİMİ", "ALTINBEŞİK", "ALÜMİNLİ", "AMAÇLILIK", "AMAÇSIZLIK", "AMANSIZLIK",
  "AMFİBOL", "AMFİZEM", "AMFORA", "AMİRANE", "AMİYANE", "AMNİYON", "ANAFOR", "ANARTRİ", "ANASIL", "ANATOMİST",
  "ANDAVAL", "ANDAVALLI", "ANEROİT", "ANGUDİ", "ANIKLIK", "ANLAMLILIK", "ANLATILIŞ", "APAREY", "APOKRİF", "ARASAT",
  "ARAZBAR", "ARBALET", "ARBİTRAJ", "ARBORETUM", "ARDUVAZ", "ARGALİ", "ARGOLU", "ARIZALILIK", "ARİSTOKRAT", "ARİTMİK",
  "ARSLANLI", "ARŞINLIK", "ARŞİDÜK", "ARTROZ", "ARZIENDAM", "ARZULAYIŞ", "ASETATLI", "ASFALTİT", "ASILANIŞ",
  "ASİMPTOT", "ASTROPİKAL", "AŞERAT", "AŞILILIK", "AŞISIZLIK", "ATAERKİ", "ATERİNA", "ATEŞLENİŞ", "ATILIŞ",
  "ATLATILIŞ", "ATOMAL", "ATROPİN", "AVLANIŞ", "AYDINLANIŞ", "AYIKLANIŞ", "AYIPLILIK", "AYNABAKAR", "AYNASIZLIK", "AZAPSIZ",
  "AZLEDİLİŞ", "BACABAŞI", "BACASIZLIK", "BADİRE", "BADİYE", "BAĞDAT", "BAĞILDAK", "BAĞIŞLANIŞ", "BAĞIŞLAYIŞ", "BAĞLAŞIMLI",
  "BAHRİYELİ", "BAHTSIZLIK", "BAKLALI", "BALAST", "BALATA", "BALDIRAK", "BALLIDARI", "BALTABAŞ", "BALTALAYIŞ", "BALTIK",
  "BALYOS", "BARBA", "BARBATA", "BARBEKÜ", "BARİT", "BARİTLİ", "BARKA", "BARLAM", "BAROMETRE", "BARYUM",
  "BASAKLI", "BASAMAKSIZ", "BASKLARNET", "BASMAKALIP", "BASMALIK", "BASMAYAZI", "BASTIBACAK", "BASTIRIK", "BASTIRILIŞ", "BAŞAKLANIŞ",
  "BAŞGEDİKLİ", "BAŞKESİT", "BAŞKURT", "BAŞLAHANA", "BAŞLANIŞ", "BAŞTABİP", "BATIN", "BAVULLU", "BAYRI",
  "BAZİTLİ", "BAZOFOBİ", "BAZUKA", "BEDBİN", "BEDHAH", "BEDİHİ", "BEDİR", "BELAHET", "BELEDİ", "BELGEÇ",
  "BELİRLENİŞ", "BELİRLEYİŞ", "BELİRTKE", "BELİT", "BENDİR", "BENİMSETİŞ", "BENİMSEYİŞ", "BENZETİM", "BERBERİ", "BERDEL",
  "BERGAMOT", "BERHAVA", "BERHAYAT", "BERİBENZER", "BERJER", "BERKELYUM", "BERKEMAL", "BERTAFSİL", "BESALET", "BESLENİŞ",
  "BESTESİZ", "BEŞARET", "BEŞERİYET", "BEŞERLİ", "BEŞİZLİ", "BETİK", "BETİMLENİŞ", "BETONİYER", "BETONLU", "BEYANAT",
  "BEYAZSİNEK", "BEYNAMAZ", "BEYTÜLMAL", "BEZZAZ", "BIÇAKLAYIŞ", "BIYIKLILIK", "BIZIR", "BİBLİYOTEK", "BİÇEM", "BİÇENEK",
  "BİÇİMLENİŞ", "BİLAKİS", "BİLASEBEP", "BİLAVASITA", "BİLDİRİLİŞ", "BİLLURİ", "BİLLURİYE", "BİNDİRİLİŞ", "BİNDİRİŞ", "BİREYÜSTÜ",
  "BİSTURİ", "BİSÜLFAT", "BİSÜLFÜR", "BİTEK", "BİTEVİ", "BİTİŞİMLİ", "BİVEFA", "BİYODİZEL", "BİYOENERJİ",
  "BİYOFİZİK", "BİYOGAZ", "BİZAR", "BLASTULA", "BLOKAJ", "BLOKNOT", "BOBİNAJ", "BOCURGAT", "BOĞANAK",
  "BOĞMACALI", "BOĞMAKLI", "BOKSİT", "BOMBELİ", "BOMBESİZ", "BONMARŞE", "BORÇLANIŞ", "BORUK", "BOYUTLANIŞ", "BÖRTÜK",
  "BRAKET", "BRİKET", "BUDUN", "BUĞUR", "BUKAĞI", "BUKANAK", "BUKLET", "BULDOK", "BUNGUN", "BURSALILIK",
  "BUSBULANIK", "BUTAFOR", "BUYRULTU", "BUYURU", "BUZAĞILI", "BUZUKİ", "BÜTÜNLENİŞ", "BÜVET", "BÜYÜKAYI", "BÜYÜKLENİŞ",
  "BÜYÜLEYİŞ", "BÜZGÜSÜZ", "BÜZÜŞÜK", "CAFCAF", "CAFCAFLI", "CAHİLANE", "CAKALI", "CAMBAZHANE", "CANHIRAŞ", "CANİYANE",
  "CANKULAĞI", "CANLANIŞ", "CAZGIR", "CAZIRTI", "CEBEL", "CEBRİYE", "CEDİT", "CELAL", "CELBE", "CEMBİYE",
  "CEPHELİ", "CERAHATLİ", "CERBEZE", "CERİDE", "CERİHA", "CERRAHİ", "CERRAR", "CESAMETLİ", "CESURANE", "CEVAPLAYIŞ",
  "CEVAPLI", "CEVHERLİ", "CEVHERSİZ", "CEVİR", "CEZAİ", "CEZASIZ", "CEZBELİ", "CEZBESİZ", "CIMBAR",
  "CIRILTI", "CIVILTILI", "CIZGARA", "CIZIK", "CIZIRTISIZ", "CİBİN", "CİDAL", "CİDAR", "CİĞERPARE", "CİHANŞÜMUL",
  "CİKLET", "CİLTLİ", "CİLVEBAZ", "CİNAİ", "CİNAS", "CİNASLI", "CİNGÖZ", "CİNSİLATİF", "CİRİM", "CİSİMCİK",
  "CİSMANİ", "CİVANMERT", "CİVELEK", "CUKKA", "CUMBADAK", "CUMBALAK", "CUMBURTU", "CÜBBELİ", "CÜLUS", "CÜLUSİYE",
  "CÜMBÜŞLÜ", "CÜMLECİK", "CÜNUN", "CÜRETLİ", "CÜRETSİZ", "CÜRUF", "CÜRÜM", "CÜSSELİ", "CÜSSESİZ", "ÇABALAYIŞ",
  "ÇAĞCIL", "ÇAĞLAYIŞ", "ÇAĞNAK", "ÇAKIN", "ÇAKINTI", "ÇAKMAKSIZ", "ÇAKŞIRLI", "ÇALTILIK", "ÇANAKÇIK",
  "ÇAPAÇUL", "ÇAPAKLI", "ÇAPAKSIZ", "ÇAPARİ", "ÇAPÇAK", "ÇAPRAŞIK", "ÇAPSIZLIK", "ÇARIKLI", "ÇARLIK", "ÇARPILI",
  "ÇARŞAFLI", "ÇATALLIK", "ÇATANA", "ÇATILI", "ÇATILIŞ", "ÇATIRTILI", "ÇATISIZ", "ÇATLATILIŞ", "ÇATLAYIŞ", "ÇAYDAÇIRA",
  "ÇEKEMEZ", "ÇEKİMSİZ", "ÇEKİNİK", "ÇEKİŞMESİZ", "ÇEKTİRİŞ", "ÇELİKHANE", "ÇELİŞMESİZ", "ÇELMELEYİŞ", "ÇELTİKLİ", "ÇENEKLİ",
  "ÇENELİ", "ÇENTİKLİ", "ÇEPELLİ", "ÇERİBAŞI", "ÇEŞİTKENAR", "ÇEVİRGE", "ÇIKKIN", "ÇİLESİZ", "ÇİNEKOP",
  "ÇİNİLİ", "ÇİPURA", "ÇİRKEFLİ", "ÇİTLEMBİK", "ÇİVİLİ", "ÇİZECEK", "ÇİZELGE", "ÇİZGE", "ÇİZGİLİ", "ÇİZGİSİZ",
  "ÇİZİKLİ", "ÇİZİLİ", "ÇİZİNTİ", "ÇOCUKCAĞIZ", "ÇOCUKLU", "ÇOMAKLI", "ÇÖLYAK", "ÇUVALLAYIŞ", "ÇÜRÜTÜLÜŞ", "DADAŞLIK",
  "DAĞLILIK", "DALAYIŞ", "DAMITILIŞ", "DAMLAYIŞ", "DANGADAK", "DARALTILIŞ", "DAVALILIK", "DAYATILIŞ", "DEBELENİŞ", "DELİCESİNE",
  "DERLENİŞ", "DERTLENİŞ", "DETAYLILIK", "DEVAMLILIK", "DIŞINDA", "DIŞLANIŞ", "DİLDAŞLIK", "DİLİMLENİŞ", "DİLİMLEYİŞ", "DİLLENİŞ",
  "DİNLEYİŞ", "DOLANIŞ", "DOLAYLILIK", "DÖKTÜRÜŞ", "DÖLLENİŞ", "DÖNDÜRÜŞ", "DUMANLILIK", "DÜZENLENİŞ", "DÜZENLEYİŞ", "EBELEYİŞ",
  "EDEPLENİŞ", "EFELENİŞ", "EĞDİRİŞ", "ELEBAŞILIK", "ELENİŞ", "ELMACILIK", "ERTELEYİŞ", "ESASLILIK", "ESRARLILIK", "ETKİLEYİŞ",
  "ETRAFLILIK", "FARKSIZLIK", "FAYDALILIK", "FİYATLILIK", "GAMLILIK", "GARPLILIK", "GEZDİRİŞ", "GIDAKLAYIŞ", "GIDASIZLIK", "GIDIKLAYIŞ",
  "GÖLGELEYİŞ", "GÜLDÜRÜŞ", "GÜMLEYİŞ", "GÜNAHLILIK", "HAFİFLEYİŞ", "HAFİFSEYİŞ", "HAKLILIK", "HALKALANIŞ", "HASARLILIK", "HAŞLANIŞ",
  "HATIRLANIŞ", "HAVALILIK", "HAYIRLILIK", "HAZIRLANIŞ", "HAZIRLAYIŞ", "HECELEYİŞ", "HESAPLAYIŞ", "HIRPALANIŞ", "HIRSLANIŞ", "HIZLANIŞ",
  "HIZLILIK", "HORLAYIŞ", "HOROZLANIŞ", "HORTLAYIŞ", "HOŞLANIŞ", "ISLANIŞ", "IŞIKSIZLIK", "İÇLENİŞ", "İLAÇLANIŞ", "İLAÇSIZLIK",
  "İLERLEYİŞ", "İMANLILIK", "İMANSIZLIK", "İMZALAYIŞ", "İNDİRİLİŞ", "İNDİRİŞ", "İNSANLILIK", "İZLENİŞ", "KAFASIZLIK", "KAMACILIK",
  "KAMÇILANIŞ", "KANSIZLIK", "KAPAKLANIŞ", "KARŞILANIŞ", "KARŞILAYIŞ", "KAŞIKLAYIŞ", "KATILIŞ", "KATLAYIŞ", "KENARLILIK", "KENETLENİŞ",
  "KESELENİŞ", "KINSIZLIK", "KISITLILIK", "KISTIRILIŞ", "KIYASLAYIŞ", "KIZARTILIŞ", "KİBİRLENİŞ", "KİLİTLENİŞ", "KİTAPLILIK", "KOKLAYIŞ",
  "KOLALAYIŞ", "KOLALILIK", "KOLASIZLIK", "KOPARTILIŞ", "KOPYALANIŞ", "KOVALANIŞ", "KÖPÜKLENİŞ", "KÖRLENİŞ", "KÖTÜLENİŞ", "KULLANIŞ",
  "KUTLAYIŞ", "LAMACILIK", "LOKMACILIK", "OYMACILIK", "POSTALANIŞ", "SAATİNDE", "SABIRLILIK", "SAHNELEYİŞ", "SALGILAYIŞ", "SAPLANIŞ",
  "SARMALAYIŞ", "SAVMACILIK", "SAYGILILIK", "SEBATLILIK", "SEKTİRİŞ", "SELAMLAYIŞ", "SENDELEYİŞ", "SEVDALANIŞ", "SEVDALILIK", "SEZDİRİŞ",
  "SEZİNLEYİŞ", "SINIRLILIK", "SIRASINDA", "SIRASIYLA", "SIZLANIŞ", "SIZLAYIŞ", "SİLAHLILIK", "SİLKELENİŞ", "SİVASLILIK", "SOLUKLANIŞ",
  "SORGULANIŞ", "SORGULAYIŞ", "SÖNDÜRÜŞ", "SÖYLEYİŞ", "SULANIŞ", "SÜRDÜRÜŞ", "SÜRÜKLENİŞ", "ŞAPADANAK", "ŞARTLILIK",
  "ŞEREFLENİŞ", "ŞUNCACIK", "TAMAMLANIŞ", "TANIKLILIK", "TANIMLANIŞ", "TANIMLAYIŞ", "TANITILIŞ", "TASARLAYIŞ", "TATLILIKLA", "TATSIZLIK",
  "TELAŞLANIŞ", "TEMİZLENİŞ", "TERSLENİŞ", "TERSLEYİŞ", "TIKIRINDA", "TIRMALAYIŞ", "TOPALLAYIŞ", "TOPLAYIŞ", "TOSLAYIŞ", "TUZLAYIŞ",
  "TÜMLENİŞ", "UĞRUNDA", "ULANIŞ", "ULAYIŞ", "UMUTLANIŞ", "UYAKSIZLIK", "UZAYLILIK", "VURGULAYIŞ", "YAĞLANIŞ",
  "YAĞLAYIŞ", "YAĞMACILIK", "YAKALANIŞ", "YALANIŞ", "YALANLANIŞ", "YAMALANIŞ", "YANDAŞLIK", "YANITLANIŞ", "YANKILANIŞ", "YANSIZLIK",
  "YAŞINDA", "YATILIŞ", "YEDİRİŞ", "YIKMACILIK", "YOLLANIŞ", "YUDUMLAYIŞ", "YURTTAŞLIK", "YÜKLENİŞ", "ZAMANINDA", "ZARARLILIK",
  "ZAYIFLAYIŞ", "ZORLAYIŞ",
  "AGRANDİSÖR", "ALAMANATA", "ALAYUNTLU", "AMBERBU", "ANAMNEZİ", "ANDROSEFAL", "ANITLI", "ANSAMBL", "ANZAROT", "APUKURYA",
  "ASESBAŞI", "ASOSYAL", "ATARİ", "AVROVİL", "AVURTLU", "AYIKULAĞI", "AYILTI", "BADISABA", "BAĞDADİ", "BAKARA",
  "BALKANLIK", "BALOZ", "BALTRAP", "BARHANA", "BARİTİN", "BARKAROL", "BASURLU", "BATSAT", "BAVCILIK", "BAYATİ",
  "BAYRAMİ", "BEDAHET", "BEDAYİ", "BEDİRİK", "BEDÜK", "BEHİMİ", "BEKRİ", "BELEMİR", "BERRİ",
  "BERTİK", "BESİHANE", "BESTELİ", "BEŞON", "BETİLİ", "BEVVAP", "BİBEHRE", "BİENAL", "BİHABER", "BİKARAR",
  "BİKES", "BİLUMUM", "BİLVASITA", "BİLYON", "BİRİMKARE", "BİTEY", "BİZMUT", "BOĞATA", "BOĞUNÇ", "BOŞNAK",
  "BOŞVERMİŞ", "BOYUNSUZ", "BOZARIK", "BÖLYÖNET", "BÖRKENEK", "BRAVO", "BROVNİNG", "BRÜLÖR", "BUĞUEVİ", "BULADA",
  "BULGARİ", "BURTLAK", "BUYOT", "BÜĞELEK", "BÜĞLÜ", "BÜSTİYER", "CAFERİ", "CAMIZ", "CANFEZA",
  "CANGIL", "CEMADAT", "CEMBİYELİ", "CENGEL", "CENUPLU", "CEVABİ", "CEVAZ", "CEZAYİRLİ", "CIDAĞI", "CIVADRA",
  "CİCOZ", "CİHARISE", "CİLASUN", "CİMDALLI", "CİNYOLU", "CİVANKAŞI", "CİZVİT", "CURNATA", "ÇAÇALIK", "ÇAKER",
  "ÇALKAĞI", "ÇANDI", "ÇANGAL", "ÇARLİSTON", "ÇAŞITLIK", "ÇATAPAT", "ÇAVALYE", "ÇEKELEZ", "ÇEKER", "ÇEKİŞTE",
  "ÇELMİK", "ÇEMREK", "ÇERVİŞLİ", "ÇİNAKOP", "ÇİSKİN", "ÇİTMİK", "ÇİVİYUKARI", "DAMASKO", "DANDİNİ", "DARAŞ",
  "DARAŞLIK", "DASİT", "DAVGANA", "DAYLAK", "DEFİBELA", "DEFOLU", "DEJAVU", "DEKADANLIK", "DEMEVİ", "DENİZGÜLÜ",
  "DENİZİBİĞİ", "DENİZÜZÜMÜ", "DENKTAŞ", "DENKTAŞLIK", "DERNEKEVİ", "DERUHTE", "DEVAİMİSK", "DEVRİHİNDİ", "DIMIŞKİ", "DİFTERİLİ",
  "DİNERİ", "DİNGİ", "DİMYAT", "DİTİRAMP", "DİVANIHARP", "DİZELGE", "DİZYEM", "DÖMİVOLE", "DÖPİYES", "DÖRDÜL",
  "DÖRTÇİFTE", "DRAHMİ", "DRAJE", "DUBARA", "DUHULİYE", "DUMAĞI", "DUMPİNG", "DURALLIK", "DÜBBÜEKBER", "DÜBEŞ",
  "DÜMTEK", "DÜNİT", "DÜRZÜ", "EBEKUŞAĞI", "EFSUS", "EHLİKİTAP", "EHLİSALİP", "EHLİZEVK", "EKOLALİ", "EKSELANS",
  "EKSERİYA", "EKVATORAL", "ELMADAĞ", "ELOĞLU", "EMRİHAK", "EMRİVAKİ", "ENBERİ", "ENCAM", "ENİKONU", "ENTERFON",
  "ENTERİT", "ENVAİÇEŞİT", "ENVAİTÜRLÜ", "EPİKEREM", "EPİSANTIR", "ERGANUN", "ERİKA", "ESKİMO", "ESKÜLABİ", "ESSAH",
  "EŞHAS", "EŞREF", "ETİBBA", "ETOBUR", "ETRİYE", "EVCARA", "EVİRTİM", "EVLİYALIK", "EVROPİYUM", "EZKAZA",
  "EZOFORİ", "LAHURAKİ", "LALÜEBKEM", "LAMELİF", "LAMİSE", "LANARKİT", "LIĞLI", "LİMAKİ", "LİPSOS", "LOBELYA",
  "LÜNET", "MADERŞAHİ", "MAĞMUM", "MAĞRURANE", "MAHDUT", "MAHMUL", "MAHUNYA", "MAHYALIK", "MALİHÜLYA", "MALTALI",
  "MALUMATTAR", "MAMAFİH", "MANCANA", "MANİŞKA", "MARSIK", "MASARİKA", "MASTURİ", "MAYİSTRA", "MAYŞOR", "MELFUF",
  "MERMERŞAHİ", "MESAMAT", "MESTURE", "METNERYUM", "METRDOTEL", "MIGIRLIK", "MİKYAS", "MİLDİYU", "MONTGOMER", "MOTRİS",
  "MOZERELLA", "MUASIR", "MÜNHANİ", "MÜSTEAR", "MÜSVEDDE", "NAKIZ", "NAKİSA", "NATIKALI", "NEKAİS", "NEMDENETİR",
  "NISIF", "NUKUT", "NÜHÜFT", "OBABAŞI", "OĞULDURUK", "OLÇUM", "ONSUZ", "OOSFER", "OPERAKOMİK", "OZONOSKOP",
  "ÖLMEZOĞLU", "ÖMRÜBİLLAH", "ÖMRÜHAYAT", "ÖTLEĞİ", "PADALYA", "PALANDIZ", "PALYOŞ", "PAMUKAKİ", "PANKRAS", "PATAKREM",
  "PATAL", "PATİSKA", "PAYREKS", "PEMBEGEMRE", "PEMBEKURT", "PEMBEZAR", "PUSVAL", "PÜNEZ", "PÜRSIHHAT", "PÜRTELAŞ",
  "RAPPADAK", "ROSTO",
  "LAFÇILIK", "LAKAPLI", "LAKAYIT", "LAKÇILIK", "LALALIK", "LAMBALI", "LAMBALIK", "LAMBASIZ", "LATEKSLİ",
  "LAVANTALI", "LEKELİ", "LEKESİZ", "LİBASLI", "LİFLİ", "LİMİTSİZ", "LİSANSLI", "LİSELİ", "LİYAKATLİ", "LİYAKATSİZ",
  "LOHUSALIK", "LOKANTALI", "LÜZUMLU", "LÜZUMSUZ", "MAAŞLI", "MAAŞLILIK", "MACARLIK", "MAFYACILIK", "MAHMUDE", "MAHMUZLU",
  "MAHSULDAR", "MAKASSIZ", "MALCILIK", "MALİYETLİ", "MALUMATLI", "MALUMATSIZ", "MANALILIK", "MANDALLI", "MANDALSIZ", "MANİDARLIK",
  "MANTARLI", "MANTARLIK", "MANYAKLIK", "MANZARALI", "MARİFETSİZ", "MARJLI", "MARKALI", "MARKASIZ", "MASACIK",
  "MASALCILIK", "MASAÜSTÜ", "MASKESİZ", "MAŞALI", "MATEMLİ", "MAYALANIŞ", "MAYALI", "MAYASIZLIK", "MAYISLI", "MAZERETSİZ",
  "MEDYACILIK", "MEHTAPLI", "MELEŞ", "MELİODİLİ", "MELODİLİ", "MENDİLLİ", "MENEDİLİŞ", "MENEVİŞLİ", "MERASİMLİ", "MERCANLI",
  "MESELESİZ", "MESNETLİ", "MESNETSİZ", "METALÜRJİK", "METANETSİZ", "METOTSUZ", "MEVZİİ", "MEVZİLENİŞ", "MEYLEDİŞ", "MEYMENETLİ",
  "MEYVELİ", "MIKNATISLI", "MİHANİKİ", "MİHNETLİ", "MİKROFONİK", "MİKROPLU", "MİKYASLI", "MİLİMETRİK", "MİLİMİKRON", "MİLSİZ",
  "MİLYARLIK", "MİMİK", "MİNARECİK", "MİNDERSİZ", "MİNERALSİZ", "MİNİK", "MİNİMİNİ", "MİNNETSİZ", "MİYAVLAYIŞ",
  "MOBİLYALI", "MODACILIK", "MODAEVİ", "MOLASIZ", "MONARŞİK", "MONARŞİST", "MONARŞİZM", "MONATÇILIK", "MOTORLU", "MUAF",
  "MUAMMALIK", "MUĞLALILIK", "MUHAFIZLIK", "MUHTAÇLIK", "MUİNLİ", "MUKAVELELİ", "MÜCEVHERLİ", "MÜDDETSİZ", "MÜHÜRLENİŞ", "MÜHÜRLÜ",
  "MÜHÜRSÜZ", "MÜLAYİM", "MÜREKKEPLİ", "MÜŞKÜLATLI", "MÜZİKLİ", "NAÇARLIK", "NADASLI", "NAKARATLI", "NAKLEDİLİŞ", "NAKLEDİŞ",
  "NALBANTLIK", "NALINLI", "NALLANIŞ", "NAMINA", "NASILSINIZ", "NASIRLI", "NASIRSIZ", "NASİPSİZ", "NEDENİYLE", "NEREDEYSE", "NERELİ", "NESNESİZ", "NEŞELİ", "NEŞESİZ", "NEZAKETLİ", "NEZLELİ", "NİFAKÇILIK", "NİSPETLİ", "NİSPETSİZ",
  "NİTELENİŞ", "NİTELEYİŞ", "NİTRATLI", "NİYETLENİŞ", "NİYETLİ", "NİZAMLI", "NİZAMSIZ", "NOHUDİ", "NOKSANSIZ", "NORMALALTI",
  "NORVEÇLİ", "NÖBETLEŞE", "NÖROLOJİK", "NUMARALI", "NUMARASIZ", "NURUAYNIM", "NURUDİDEM", "NÜFUSLU", "NÜFUZLU", "NÜFUZSUZ",
  "NÜZULLÜ", "OBURCASINA", "OCAKBAŞI", "ODAKLANIŞ", "ODALI", "ODUNLU", "OKSİJENLİ", "OKŞAMALIK", "OKŞANIŞ", "OKULLU",
  "OKUMAK", "OLAMAZLIK", "OLMAMIŞLIK", "OLMAZLI", "OLMUŞ", "OLTACILIK", "OLUMSALLIK", "OMUZDAŞLIK", "OMUZLU", "ONARICILIK",
  "ONAYLANIŞ", "ONAYLAYIŞ", "ONBİRAYLIK", "ONDÜLELİ", "ONLARINKİ", "ONUNKİ", "ONURLU", "ORALI", "ORANLILIK",
  "ORANSIZ", "ORDUEVİ", "ORGANİZE", "ORMANCIK", "ORTALI", "ORUÇLU", "ORUÇSUZ", "OSMANİ", "OSMANLI", "OSMANLILIK",
  "OSMİYUMLU", "OTELGARNİ", "OTİSTİK", "OTLU", "OTOBUR", "OTSUL", "OTSUZ", "OTURACAK", "OTURMAK", "OYALANTI",
  "OYDAŞLIK", "OYLUMLU", "OYNAYIŞ", "OYUNCAKLI", "OZANLIK", "OZMOZ", "ÖDENİŞ", "ÖFKELENİŞ", "ÖFKELİ", "ÖĞRETİLİŞ", "ÖĞÜTÜŞ", "ÖKSÜRÜKLÜ", "ÖKSÜRÜŞ", "ÖLÇEKLİ", "ÖLÇEKSİZ", "ÖLÇÜLÜ", "ÖLÜMLÜ", "ÖNERİLİŞ", "ÖNLEYİŞ", "ÖNLÜKLÜ", "ÖRGÜLÜ", "ÖRGÜTLEYİŞ", "ÖRGÜTLÜ", "ÖRTÜLÜŞ", "ÖRTÜSÜZ", "ÖVÜLÜŞ", "ÖVÜNÜŞ",
  "ÖYLELİKLE", "ÖZELLİKLE", "ÖZELLİKLİ", "ÖZETLENİŞ", "ÖZLEMSİZ", "ÖZLENTİLİ", "ÖZLÜ", "ÖZÜMSEYİŞ", "ÖZÜRSÜZ", "ÖZVERİLİ",
  "PAÇASIZ", "PAHASINA", "PAKETLEYİŞ", "PALMİTAT", "PALMİTİN", "PANJURLU", "PANKARTLI", "PANTOLONLU", "PARACILIK",
  "PARAFİNLİ", "PARALI", "PARALILIK", "PARASIZ", "PARASIZLIK", "PARAZİTLİ", "PARAZİTSİZ", "PARÇALAYIŞ", "PARILDAYIŞ", "PARILTI",
  "PARILTILI", "PARKÇILIK", "PASAKLI", "PASLILIK", "PASÖR", "PASTÖRİZE", "PATATESLİ", "PAYANDALI", "PAYANDALIK", "PAYLAŞMAK",
  "PAYTAKLIK", "PAZARCILIK", "PAZARLANIŞ", "PAZARLIKLI", "PAZILI", "PEÇETELİ", "PEKMEZLİ", "PENTÜR", "PENUVAR", "PERÇEMLİ",
  "PERÇİNSİZ", "PERDELİ", "PERHİZLİ", "PERİŞANLIK", "PERVANELİ", "PERVANESİZ", "PERVAZLI", "PEŞTAMALLI", "PEYNİRHANE", "PEYNİRSİZ",
  "PİMPİRİKLİ", "PİRELİ", "PİŞİRMEK", "PİŞTİ", "PİTİKARE", "PLAKALI", "PLANCILIK", "PLANLAMAK", "PLANLILIK", "PLANSIZLIK",
  "POTANSİYEL", "POTURLU", "PROBLEMLİ", "PROBLEMSİZ", "PROGRAMLI", "PROTEİNSİZ", "PUSATLI", "PUSULACIK", "PUSULASIZ",
  "PUTRELLİ", "PÜRÇÜKLÜ", "PÜRHİDDET", "PÜRTÜKLÜ", "PÜSKÜLSÜZ", "PÜSKÜRÜŞ", "RAĞBETLİ", "RAHATLAYIŞ", "RAHMETLİ",
  "RAKAMSIZ", "RAMPALI", "RANDEVULU", "RANDEVUSUZ", "REÇETELİ", "REÇİNELİ", "REDDEDİŞ", "REHBERSİZ", "RENDELENİŞ", "RENDELİ",
  "RENKTAŞLIK", "RESİMLİ", "RESMEDİŞ", "RESSAMLIK", "REVNAKLI", "REZEKSİYON", "RİMELLİ", "RİTMİK", "RİZİKOLU", "RUMELİLİ",
  "RUMUZLU", "RUTUBETLİ", "RUTUBETSİZ", "RÜTBESİZ",
  "FABRİKATÖR", "FACTORİNG", "FALAKALI", "FANGRİ", "FARBALA", "FARBALI", "FENİK", "FERDA", "FERHANE",
  "FERNEZ", "FIRDOLAYI", "FISFIS", "FİKİRDEŞ", "FİLİZ", "FİLUM", "FİNGİRDEK", "FİTNESS", "FLEGMON",
  "FLEOL", "FONDÜ", "FONOLİT", "FOTOAKIM", "FOTOKİNEZİ", "FOTOSKOP", "FRANKLIK", "FRİSA", "FRİŞKA", "FURGON",
  "FÜLÜS", "GABARİ", "GAFFAR", "GAFUR", "GALALİT", "GALERYA", "GALEYANLI", "GALİBARDA", "GANALI", "GAZIŞI",
  "GECELERİ", "GECELEYİŞ", "GEÇİNİZ", "GELENİ", "GELGELELİM", "GERÇEKTE", "GERDANİYE", "GERDEL", "GİNSENG", "GİRANBAHA",
  "GİTSİN", "GİTTİ", "GLASNOST", "GLASYOLOG", "GÖKEVİ", "GÖKYOLU", "GÖLGECİL", "GÖYÜK", "GRAFİK",
  "GRANDİ", "GROSTON", "GRUPLANIŞ", "GÜÇBEĞENİR", "GÜLGÜLİ", "GÜNDE", "GÜNDELİKLİ", "GÜNDÜZLERİ", "GÜNGÖRMÜŞ",
  "HACIAĞA", "HACIAĞALIK", "HAFIZALİ", "HAFTALIKLI", "HAHHA", "HALİM", "HALİS", "HALİSÜDDEM", "HALKOYU",
  "HALLİHAMUR", "HAMAKAT", "HAMDOLSUN", "HAMHALAT", "HAMULE", "HARMONİYUM", "HARMONYUM", "HARTA", "HARTADAK", "HARTUÇ",
  "HASILI", "HASSE", "HASTEL", "HAŞARILIK", "HAVACIVA", "HAYDARİ", "HAYDİNDİ", "HAYDİSENE", "HAYIF", "HAYIRHAH",
  "HAYMATLOS", "HAYVANCIK", "HAZANDİDE", "HAZAR", "HAZIRLOP", "HAZIRUN", "HEBA", "HEDONİST", "HELİS", "HELYODOR",
  "HESABİ", "HIRSSIZLIK", "HIRTAPOZ", "HİDDETSİZ", "HİPOSANTIR", "HİSSİSELİM", "HİTİT", "HORASANİ", "HORST", "HOTANTO",
  "HÖKELEKLİ", "HUKŞAT", "HULUS", "HÜMAYUN", "HÜNSA", "HÜRYA", "HÜSEYNİ", "HÜVEYDA", "IKINTI", "INCALIZ",
  "IPISSIZ", "IPISSIZLIK", "IRAKGÖRÜR", "IRAKSAK", "ISIDAM", "ISKARMOZ", "ISLAHHANE", "ISLIKLANIŞ", "ISMARLAYIŞ", "ISTAMPA",
  "ISTAR", "ITTIRAT", "IZTIRAR", "İCABINDA", "İÇTENLİKLE", "İÇTİMAİ", "İÇTİMAİYAT", "İDARELİ", "İDEALİZE", "İDENTİK",
  "İĞBİRAR", "İĞTİNAM", "İHLAS", "İHLASLI", "İHLASLILIK", "İKEBANA", "İKİNDİÜSTÜ", "İKİRCİK", "İKİRCİM", "İKİRCİMLİ",
  "İKİŞER", "İKRAHLIK", "İLAHE", "İLANİHAYE", "İLARYA", "İLENÇLİ", "İLETİŞİMLİ", "İLHANLIK", "İLİSTİR", "İLLA",
  "İLLE", "İLMÜHABER", "İLTİHABİ", "İMARET", "İMRAHOR", "İMRENTİ", "İMSAKİYE", "İNADINA", "İNANLI", "İNANSIZ",
  "İNÇ", "İNDİFAİ", "İNDİNDE", "İNDÜKLEÇLİ", "İNHİNA", "İNİLDEYİŞ", "İNOVATİF", "İNSANİYET", "İNSİYAK",
  "İPEKHANE", "İPİLTİ", "İPTİZAL", "İRADİYE", "İRKİLİŞ", "İRMİK", "İSPANYOLET", "İSPİRTOLU", "İTİBARIYLA", "İTİBARİ",
  "İTİDALLİ", "İTİKAT", "İTİLİŞ", "İTİNAYLA", "İTİZAR", "İTTİHAT", "İZAFİYE", "İZANLI", "İZOMERİK", "JALUZİLİ",
  "JENERİK", "JEOKİMYA", "JEOTERMAL", "JİNEKOLOJİ", "KABARALI", "KABULLENİŞ", "KABULLENMEK", "KAÇAR", "KAÇLIK",
  "KAÇMAKLIK", "KAÇTA", "KADINANA", "KADINNİNE", "KADİRİ", "KADRİL", "KAFADARLIK", "KAFAKOL", "KAFDAĞI", "KAKILIŞ",
  "KAKINÇ", "KAKMACILIK", "KAKTIRIŞ", "KALABA", "KALBİSELİM", "KALENSÖVE", "KALIMLI", "KALIPÇILIK", "KALYA", "KAMARİLLA",
  "KAMGA", "KAMUS", "KANALCIKLI", "KANASTA", "KANÇILARYA", "KANDİLİSA", "KANIKSAYIŞ", "KANITLAYIŞ", "KANTARİYE", "KANTİYANE",
  "KANYAK", "KAPANIKLIK", "KAPATIŞ", "KAPÇIKLI", "KAPİK", "KAPİŞ", "KAPLILIK", "KAPNİSİT", "KAPORALI", "KAPTIKAÇTI",
  "KARABACAK", "KARABALDIR", "KARABALIK", "KARABİNYER", "KARADAĞLI", "KARAKUŞİ", "KARALI", "KARASIĞIR", "KARATAŞ", "KARAY",
  "KARBONİFER", "KARDEŞLİ", "KARİHA", "KARKARA", "KARMALIK", "KARNİ", "KARŞIN", "KARYAĞDILI", "KASALIK",
  "KASATURA", "KASEM", "KASINTILI", "KASVETSİZ", "KAŞESİZ", "KAŞIKÇIN", "KAŞKORSE", "KAŞPUSİYE", "KATAKOFTİ", "KATAKULLİ",
  "KATIMLIK", "KAVANÇO", "KAVASYA", "KAVKILI", "KAVUŞTAK", "KAYDIHAYAT", "KAYGANLIK", "KAYGILANIŞ", "KAYGILILIK", "KAYIR",
  "KAYITIM", "KAYNAÇ", "KAYPAKLIK", "KAZAMAT", "KAZASKER", "KAZILIŞ", "KAZIMIK", "KAZOLİT", "KEDİGÖZÜ", "KEFENSİZ",
  "KEFNE", "KELALAKA", "KELEPSER", "KELİFİT", "KEMAL", "KEMERE", "KEMİRDEK", "KENTAL", "KENTET", "KENTTAŞ",
  "KENTTAŞLIK", "KENYALI", "KERDE", "KERTELES", "KESATLIK", "KESESİZ", "KESİF", "KESTİRİŞ", "KEŞŞAFLIK", "KEVEL",
  "KEYFEKEDER", "KEZZAP", "KIBRISLI", "KIÇTANKARA", "KILAĞILI", "KILIR", "KILKUYRUK", "KINACIK", "KINASIZLIK", "KINAYIŞ",
  "KIPIK", "KIPKIZIL", "KIRAĞILI", "KIRATLIK", "KIRBA", "KIRÇIL", "KIRKYILLIK", "KITIK", "KIYIK", "KIYILIK",
  "KIYIMLI", "KIYMIKLI", "KIZCAĞIZ", "KIZILBOYA", "KIZILYARA", "KIZKALBİ", "KİBUTZ", "KİFAF", "KİKİRİK", "KİKLON",
  "KİKLOTRON", "KİLİZ", "KİLLİ", "KİNSİZ", "KİPKİRLİ", "KİREBOLU", "KİRİŞHANE", "KİRLİHANIM", "KİYANUS", "KLASİK",
  "KOAPTÖR", "KOKETRİ", "KOKONA", "KOKOROZ", "KOLANCILIK", "KOLDAŞLIK", "KOLEDOK", "KOLODYUM", "KOLYOZ", "KOMOT",
  "KONÇLU", "KONGÖVDE", "KONGÖVDELİ", "KONKUR", "KONSA", "KONSULTO", "KONTRPİYE", "KOPANAKİ", "KORDONE", "KORİDA",
  "KORPORATİF", "KORUN", "KORUNCAK", "KOŞA", "KOŞAM", "KOTARILIŞ", "KOTONPERLE", "KOVALIK", "KOYACAK", "KOYAR",
  "KOYULUŞ", "KOZMOGONİK", "KÖÇEK", "KÖLELİ", "KÖRPECİK", "KÖSNÜL", "KÖTÜRÜM", "KRAVL", "KREPDÖŞİN",
  "KREPLİN", "KRUVAZE", "KUBATLIK", "KULOĞLU", "KULYUÇ", "KUMANDI", "KUNDA", "KUPKURU", "KURCALANIŞ", "KURCALAYIŞ", "KURGULANIŞ", "KURGULAYIŞ", "KURMACILIK", "KURULU", "KURUSIKI", "KÜFREDİŞ", "KÜLLÜ", "KÜLÜ", "KÜLYUTMAZ", "KÜMÜLÜS", "KÜNDE", "KÜRDANLIK", "KÜTLÜ", "KÜTÖR",
  "ABDÜLLEZİZ", "ADAPAZARI", "ADINA", "AĞLAMAKLIK", "AKLIMDA", "AKSARAY", "AKTİNYUMLU", "ALPAKS", "AMAZON",
  "ANANELİ", "ANANESİZ", "ANIRIŞ", "ANITKABİR", "ANTARKTİKA", "APANSIZIN", "ARAŞTIRI", "ARZİYAT", "ASARIATİKA", "AVM",
  "BAĞIN", "BAKARAK", "BAKARSIN", "BAŞARILAR", "BEDAVASINA", "BEDAVAYA", "BESBEDAVA", "BİRBİRİM", "BİRÇOKLARI", "BİNDİ", "BİTTABİ", "BİRİNCASIF",
  "BODYGUARD", "BOĞADA", "BUGÜNLERDE", "BUNCAĞIZ", "BURAK",
  "CEBRAİL", "CEMİL", "CHANGE", "CHARTER", "CUNDA",
  "ÇİVRİL", "ÇOKLARI", "ÇOKSATAR", "ÇUKUROVA",
  "DAKİKASINA", "DARÜLACEZE", "DARÜLEYTAM", "DAÜSSILA", "DEVLETLE", "DILAK", "DİDON", "DÜNYADA",
  "DOĞALLIKLA", "DOKTORALI", "DRAGON",
  "EBEBULGURU", "ENGELLEYİM", "ESNASINDA", "EUROBOND", "EVVELALLAH",

  // --- Biyolojik Familya, Taksonomi ve Sınıflandırma Terimleri (IŞINLILAR ve benzerleri) ---
  "IŞINLILAR", "KAMÇILILAR", "KESELİLER", "SİFONLULAR", "TRAKELİLER", "SPORLULAR", "HALKALILAR",
  "DELİKLİLER", "KANATLILAR", "BOAGİLLER", "ATGİLLER", "MUZGİLLER", "TOYGİLLER", "HANİGİLLER",
  "MORSGİLLER", "TURPGİLLER", "FİLGİLLER", "İNSANSILAR", "OTOBURLAR", "ETÇİLLER", "FUKUSLAR", "SİKALAR", "FİLAR",
  "YENGEÇVARİ", "BALONVARİ",

  // --- Gereksiz / Yapay Çoğullar (Kök kelimesi zaten mevcut olanlar) ---
  "ÖRÜMCEKLER", "KELEBEKLER", "PAPAĞANLAR", "MANTARLAR", "SİNEKLER", "YARASALAR", "ARILAR",
  "TİMSAHLAR", "MAYMUNLAR", "TAVUKLAR", "AKREPLER", "ISTAKOZLAR", "FUNDALAR", "KUŞLAR", "KARINCALAR",
  "SÜLÜKLER", "ŞERİTLER", "BUNLAR", "ONLAR", "EKLER", "EKLENTİLER", "ARMONİLER",
  "BİRLER", "ÇAĞLAR", "BAĞLAR", "ONLARSIZ",

  // --- Özel İlçe ve Yer Adları ---
  "EĞİRDİR", "KARS", "KOVANCILAR", "BAĞCILAR", "AVCILAR", "AYDINLAR", "ESENLER", "AKINCILAR", "SEYDİLER",

  // --- Taboo, Müstehcen ve Uygunsuz Kelimeler ---
  "VAJİNA", "FRİJİT", "JARTİYER", "KIÇ", "SEKS", "NAZİZM", "NEONAZİZM", "FALANJİST",

  // --- Yabancı / İngilizce Kelimeler ---
  "BESTSELLER", "JOGGİNG", "TREYLER", "VOKABÜLER", "SLİP", "VAMP", "STAR", "DATA",

  // --- Ağır Osmanlıca / Ölü / Günlük Dilde Karşılığı Olmayan Sözcükler ---
  "FECRİSADIK", "PONJE", "JURNAL", "İNTELİJANS", "ÇAVULDUR", "DUDU", "SABİ",
  "MÜSTEVİ", "MÜSTAKİM", "MÜSTEVLİ", "MÜSTELZİM", "MÜSTEHZİ", "MÜSTANTİK", "MÜSTEŞRİK",
  "MÜTEAMMİM", "MÜTEBAHHİR", "MÜTEKAİT", "MÜTEHEVVİR", "MÜTEESSİR", "MÜTECANİS", "MÜTEDAİR",
  "MÜTENAKIZ", "MÜSTEBAT", "İSTİĞFAR", "İSTİNTAK", "MÜSTEKREH", "MÜTEFERRİK", "İSTİFRA",
  "MÜSTAHSİL", "MÜTEESSİF", "İSTİCAL", "MÜTEBESSİM", "MÜTEAFFİN", "MÜTECASİR", "İSTİMATOR",
  "İSTİKA", "MÜTEMADİ", "MÜTEMERKİZ", "MÜTEFEKKİR", "MÜTENAKIS", "MÜTEMAYİZ", "İSTİDLAL",
  "MÜTEDEYYİN", "MÜTEALİYE", "MÜTEBEDDİL", "MÜTEHASSİS", "İSTİHBAR", "MÜTENEKKİR", "MÜTEHAKKİM",
  "İSTİMRAR", "MÜTEVAZİN", "MÜTEARİFE", "İSTİFHAM", "MÜTENASİP", "MÜTEBAKİ", "MÜTECAVİZ",
  "İSTİMAL", "MÜTEHAYYİR", "MÜSTAĞNİ", "MÜTEHAMMİL", "İSTİBAT", "MÜTEKABİL", "MÜTESANİT",
  "MÜSTEHAP", "MÜTEHEYYİÇ", "İSTİĞNA", "MÜSTACEL", "MÜTEVEFFA", "İSTİLZAM", "MÜSTENKİF",
  "MÜTENEFFİR", "MÜTEKELLİM", "İSTİSKAL", "MÜTEHAVVİL",

  // --- Aşırı Akademik / Bilinmeyen Terimler ---
  "MONADİZM", "EGOTİZM", "LAMAİZM", "STEREOSKOP", "FAKİRİZM", "PANSLAVİZM", "ÇİNKOGRAFİ",
  "PETROGRAFİ", "PÜRİZM", "MİKAŞİST", "OSTEOLOJİ", "FRENOLOJİ", "VİROLOJİK", "PETROLOJİK",
  "JEOSİSMİK", "SİLİNDİRAJ", "FONOLOJİK", "PİKAJCILIK", "VEJETALİN", "TELEOLOJİK", "SİTOLOJİK",
  "LETARJİ", "KSİLOLOJİK", "MİKOLOJİK", "PLONJON", "POLİJİNİ", "PEDOLOJİK", "PEJORATİF",
  "DENDROLOJİ", "AEROLOJİK", "METROLOJİK", "ENTOMOLOJİ", "TRİBOLOJİ", "MİNEROLOJİ",
  "ABAJURSUZ", "JAKUZİSİZ", "JELATİNSİZ", "RUJSUZ", "DONSUZ", "UÇKURSUZ", "BESMELESİZ",
  // --- Daha önce eklenenler --- "LAK", "PRUVA", "MEME", "PISMA", "TONLUK", "EKSERİ", "EKSERİYA", "ÖZENİ", "ÖRMELİ", "DİTMEK",
  "BAV", "RUF", "DUN", "FEL", "SEM", "NOM", "POG", "ALG", "HAV", "CUP", "PIR", "DEH", "BED",
  "ZOM", "PÖÇ", "SÜMEK", "KUSMA", "SIVAMA", "TUTMACA",
  "PİÇ", "KOV", "ARİ", "ŞUH", "ÇAV", "TÖS", "İDE", "ÖZE", "KAM", "HAF", "AKA", "KÖS", "KIĞ",
  "POF", "AFİ", "İYE", "ŞOR", "OMA", "ZEM", "TÜN", "VIN", "ELK", "LÖS", "ÇİR", "ÖHÖ", "EDİ",
  "ŞEM", "MEH", "FEK", "EKE", "ŞAD", "KİK", "ŞAZ", "CIZ", "UZO", "ABE", "YEĞ", "TAL",
  "BİDE", "BİTİ", "BÖKE", "BUZUK", "CILK", "ÇEPNİ", "ÇEŞT",
  "ÇIKIN", "ÇİMÇİK", "DALIZ", "DAMLI", "DEBİ", "DEĞE", "DEĞİM", "DEPSİ",
  "DEŞİK", "DEVİ", "DEVRİ", "DİDAR", "DİDİM",
  "DİMAĞ", "DİNGO", "DİPER", "DİRİĞ",
  "DİVAL", "DİVİT", "DİZEK", "DİZME",
  "DOKUM", "DOLAM", "DOMBAY", "DOMDOM", "DONER", "DONAM", "DORUM",
  "DÖLÜK", "DÖNEŞ", "DÖNMESİ", "DÖŞEM", "DÖŞER", "DUHUL", "DUKA", "DURGU",
  "DURMA", "DURUK", "DUŞAK", "DUYMA", "DUYUM",
  "DÜRZİ", "DÜZGÜ", "DÜZME", "ECELİ", "ECNEBİ",
  "EVİMİ", "EVİNİ", "ADINI", "GÜNÜ", "SESİNİ", "YOLUNU", "KIZINI", "OĞLUNU", "CANINI", "İŞİNİ", "SÖZÜNÜ", "ELİNİ", "GÖZÜNÜ", "AKLINI", "BAŞINI", "SUYUNU",
  "SENİT", "YOKÇU", "FANYA", "KEMHA", "EZANİ", "KADÜK", "APAŞ", "ÇEDİK", "DROG", "BEZİK", "KEMRE", "CAİZE", "İNTAK", "KOTRA", "JARSE", "GASİL", "MATUH", "ARGIN", "ERGİ", "HAMEL", "HATİF", "BIKIŞ", "ÇOLPA", "EPOPE", "DÜRÜ", "ALTES", "ALYON", "DERÇ", "MİMLİ", "BABAÇ", "AÇIM",

  // --- Arkaik / Osmanlıca / Ölü kelimeler ---
  "AHİ", "ZEM", "ZOM", "PIR", "EDİ", "CIK", "POG", "POF", "MEH", "NOM", "OMA", "ORA", "HAF",
  "TAAM", "SAGU", "SERE", "SÖBE", "SELEK", "SELEF", "SEHİV", "RAŞE", "RAŞİ", "RESEN", "REVAN",
  "RİYA", "NÜKS", "ULAH", "URUP", "UĞUT", "UTÇU", "UMRE",
  "VAİZ", "VACİP", "VECİH", "VECİZ", "VEDİA", "VİSAL", "VİTİR", "VOYVO", "VUKU", "VUZUH", "VÜSAT", "ZAİL", "ZEHAP", "ZİMMİ", "SOBE", "SEKEL",
  "İBDA", "İBZAL", "İCAR", "İFRAĞ", "İHAM", "DÜRÜ", "DERÇ", "APRE", "AGUŞ", "AHŞA", "ALPU", "APAZ", "ARŞE", "ASRİ",
  "BÜVE", "CÖNK", "CÜZİ", "DANK", "DERK", "DİNK", "EHEM", "EKİT",
  "SEMAH", "SAGU", "SARİG", "SARAT", "SANGI", "SIYGA", "SÜBEK", "SÜCUT", "SÜFLİ",
  "SÜYEK", "SÜYÜM", "SÜVME", "SÜVEN", "SİFİN", "SİRTO", "SİTİL", "SİYME", "SİĞİL",
  "TAAT", "TABYA", "TADAT", "TAHRA", "TALİK", "TANİN", "TAPON", "TARAZ", "TARİZ",
  "TATMA", "TAVAF", "TEDAİ", "TEDİP", "TEKST", "TELSİ", "TEMEK", "TEPİR", "TERBİ",
  "TESRİ", "TESİT", "TEVİL", "TEŞRİ", "TEŞT", "TIKIZ", "TINAZ", "TINMA", "TOKUZ",
  "TONOZ", "TOPUR", "TOYCA", "TOYCU", "TRAKE", "TRATA", "TROMP", "TRÖST",
  "TÖREL", "TÖZEL", "TÜMÜR", "TİRİZ", "TİMAR",
  "ULEMA", "URBAN", "USSAL", "VAKAR", "VAKIA", "VALÖR",
  "VELUR", "YALAZ", "YAMÇI", "YANGI", "YANIŞ", "YAPAK", "YARDA", "YASMA",
  "YATÇI", "YAVE", "YAYIŞ", "YAZIŞ", "YAĞAR", "YAĞSI", "YEDME", "YEDİZ", "YELVE",
  "YERME", "YEZİT", "YEĞNİ", "YILKI", "YILMA", "YIRIK", "YIVA", "YOLMA", "YORTU",
  "YOSMA", "YUNAK", "YUNMA", "YUVAK", "YUVGU", "YÜLÜK", "YÜSRÜ", "YİTME", "YİTİŞ",
  "ZEBUN", "ZELVE", "ZORGU", "ZÜHAL", "ZÜLÜF",
  "ÇALTI", "ÇAMAT", "ÇAMAŞ", "ÇAPMA", "ÇAPUL", "ÇARKA", "ÇAVLI", "ÇAYAN",
  "ÇEKEL", "ÇEKÇE", "ÇEKÜL", "ÇELEN", "ÇENEK", "ÇENET", "ÇERGE", "ÇERÇİ",
  "ÇOKAL", "ÇOKÇU", "ÇİPİL", "ÇİRİŞ", "ÇİĞİL", "ÇİŞİK",
  "ÖBÜRÜ", "ÖRFİ", "ÖRGE", "ÖRÜK", "ÖTÜCÜ", "ÖZALP",
  "ÜFLEÇ", "ÜLFET", "ÜLÜŞ", "ÜMMİ", "ÜMÜK", "ÜRAT", "ÜRGÜP",
  "İCAP", "İCAR", "İCMAL", "İFRAĞ", "İHAM", "İHATA", "İHDAS", "İHRAM", "İHRAZ",
  "İKDAM", "İKRAH", "İKRAR", "İKRAZ", "İLKAH", "İLLET", "İMALE",
  "İNŞAT", "İPEKA", "İPSİZ", "İRADİ", "İRSEN", "İRŞAT", "İSLİM", "İSPİR", "İTLAF", "İTMAM", "İTİLA", "İVESİ", "İZAZ", "İZHAR",
  "ŞAFUL", "ŞAFİİ", "ŞAHAP", "ŞARPİ", "ŞATIR", "ŞAYAK", "ŞAYKA", "ŞAİRE",
  "ŞEKVA", "ŞERHA", "ŞERİR", "ŞIRAK", "ŞORCA", "ŞÖMİZ", "ŞİMAL", "ŞİNTO", "ŞİRAN",

  // --- Teknik / Tıbbi / Bilimsel ---
  "SPAZM", "SPERM", "PENİS", "PENES", "OOSİT", "NÜZUL", "MEDÜZ", "NODÜL", "MELAS",
  "LORTA", "LEPRA", "LAHUT", "LAĞIV", "KÜRDİ", "KİTRE",
  "KUTSİ", "KUTNU", "KOTRA", "KOFTİ", "KITAL", "KITIR", "KROŞE", "KUPLE",
  "RAFİT", "RECİM", "REFİK", "REKİZ", "REMİZ", "RÜKÜN", "RÜSUM", "RÜYET", "RİCAL",
  "SÜMÜK", "TIRIS", "TİRİZ",
  "UTMAK", "UZLUK", "UZVİ",
  "VONOZ", "VİYAK", "VİYA",

  // --- Özel isim / Yer adı / Marka / Etnik (kesinlikle çıkar) ---
  "NUH", "AYLA", "AYAŞ", "SİVAS", "ZELVE", "ORLON", "ORİON", "YUNAN", "URLA",
  "VANLI", "RUMCA", "METİS", "MOĞOL", "MACAR", "KİLİS", "KEŞAN",
  "ÇEÇEN", "ZENCİ", "ORYA",
  "UŞAKLI", "KÜTAHYALI", "DÜZCELİ", "ADANALI", "ANTALYALI", "AĞRILI", "BURDURLU",
  "RİZELİ", "MERSİNLİ", "AKSARAYLI", "HATAYLI", "AMASYALI", "BAYBURTLU", "ARTVİNLİ",
  "TRABZONLU", "KIRŞEHİRLİ", "YALOVALI", "TUNCELİLİ", "ERZURUMLU", "ERZİNCANLI",
  "KARABÜKLÜ", "TOKATLI", "SİVASLI", "BİNGÖLLÜ", "GİRİTLİ", "KARTALLI",
  "BEŞİRİ", "KOZLUK", "GERCÜŞ", "HASANKEYF", "TAVAS", "ACIPAYAM", "BULDAN",
  "SERİNHİSAR", "CİHANBEYLİ", "DOĞANHİSAR", "ILGIN", "SEYDİŞEHİR", "BEYŞEHİR",
  "YALIHÜYÜK", "ÇATAK", "ERCİŞ", "BAHÇESARAY", "ÇAMLIDERE", "KALECİK", "HAYMANA",
  "SİLİVRİ", "ALANYA", "MANAVGAT", "KORKUTELİ", "DEMRE", "GÜNDOĞMUŞ", "DİGOR",
  "SARIKAMIŞ", "ARPAÇAY", "ANAMUR", "BOZYAZI", "TARSUS", "BERGAMA", "ALİAĞA",
  "GAZİEMİR", "KARŞIYAKA", "TORBALI", "URLA", "KARABURUN", "PAZARCIK", "SİLVAN",
  "BİSMİL", "HAZRO", "İDİL", "ULUDERE", "GÜÇLÜKONAK", "ŞEMDİNLİ", "ÇUKURCA",
  "DERECİK", "KURTALAN", "BAYKAN", "ŞİRVAN", "BİRECİK", "AKÇAKALE", "DİYADİN",
  "TATVAN", "MUTKİ", "GÜROYMAK", "MAZGİRT", "ÇAYIRLI", "OTLUKBELİ", "AŞKALE",
  "İSPİR", "NARMAN", "OLTU", "PASİNLER", "ŞENKAYA", "TORTUM", "KARAÇOBAN",
  "KÖPRÜKÖY", "UZUNDERE", "ALUCRA", "ÇAMOLUK", "YAĞLIDERE", "ÇATALPINAR", "FATSA",
  "KORGAN", "ÜNYE", "ARHAVİ", "MURGUL", "SÜRMENE", "ŞALPAZARI", "TONYA", "VAKFIKEBİR",

  // --- Rahatsız edici / argo / kaba ---
  "CİFE", "SOBE", "SIYGA",

  // --- Kullanıcının bildirdiği ve tespit edilen saçma/arkaik/Scrabble kelimeleri ---
  "AGEL", "GIGI", "GETR", "GABİ", "GALİ", "GANG", "GANİ", "GARP", "GEDA", "GELE",
  "GONK", "GREK", "GÖCE", "GÖNÇ", "GÖRK", "GÜRE", "GİDİ", "HAFİ", "HAJE", "HARA",
  "HAZA", "HAİL", "HAİZ", "HOŞT", "HUŞU", "HÜDA", "HİŞT",
  "IRIP", "IĞIL", "IŞKI", "KAKA", "KALA", "KAMA", "KANT", "KAVİ",
  "KAÇA", "KEFE", "KEKE", "KESP", "KUUT", "KÜNK", "KİLE", "KİPE", "KİST",
  "LAKA", "LALA", "LAİN", "LAŞE", "LİKA", "MAKİ", "MANO", "MAPA", "MARN", "MAYİ",
  "MESH", "MEŞK", "MOKA", "MURÇ", "MUTİ", "MUİN", "MUİT", "MÜFT", "MİAT", "MİHR",
  "MİSO", "NALE", "NARH", "NAZİ", "NAİL", "NAŞİ", "NEBİ", "NÜVE", "NİTE", "OBUA",
  "OMCA", "PARE", "PATA", "PENA", "PEPE", "PEYK", "PIŞT", "PUPA", "RATE", "REHA", "SADA", "SAFİ", "SAKE", "SANI", "SAVA", "SAYE", "SEKİ",
  "SÖKE", "SÖVE", "SÜJE", "SİLO", "SİLİ", "SİNE", "SİYA", "TABA", "TALK",
  "TAPI", "TAUN", "TEFE", "TERE", "TRAS", "TROK", "TÜLÜ", "TİFO", "TİPO", "ULAK",
  "ULAM", "ULUM", "UMUŞ", "URUK", "UĞRA", "UĞRU", "VAKİ", "VERE", "VİDO",
  "VİRA", "YAVE", "YIVA", "YOMA", "YUNA", "ZAİL", "ZINK", "ZİLİ", "ÇİPO", "ÇİSE", "ÇİTİ", "ÖKSE", "ÖLÜŞ", "ÖVÜŞ", "ÖÇLÜ", "ÖĞÜR", "ÜNİK", "İAŞE", "İBRE", "İNAK", "İNAL", "İRAP", "İRCA", "İTAP", "İVGİ", "İÇRE", "İÇİŞ",
  "İŞBU", "ŞALT", "ŞİST", "ABLİ", "ABUS", "ACUL", "ACUR", "AHAR", "AHİR", "AHİT",
  "AKİS", "ALAZ", "ANIK", "APSE", "ARAZ", "ASAP", "ASAR", "ASIM", "ATOL",
  "AVAR", "AVAZ", "AYIT", "AZİT", "AÇAR", "AÇIŞ", "AÇKI", "BABİ", "BADE", "BAKİ",
  "BARI", "BARİ", "BATİ", "BETİ", "BOCA", "BREŞ", "BROM",
  "BRİT", "BRİÇ", "BUKE", "BİBİ", "BİYE", "CART", "CELİ", "CIRT", "DANE",
  "DARA", "DARP", "DEBİ", "DEFİ", "DİNE", "DİZE", "EHİL", "EKLİ", "EKOL",
  "EKTİ", "ENİK", "ENİR", "EREK", "ERİL", "ESEF", "ESİK", "ESİM", "ETER", "EVCE",
  "EŞEY", "FLOŞ", "FRİZ", "FUTA",
  // 3 harfli saçma/arkaik kelimeler:
  "ABA", "AHA", "AKI", "ARP", "ATE", "BÖN", "CÜZ", "DOK", "DÜK",
  "FER", "FOL", "FİN", "GIK", "HUN", "KET", "KOF", "KUT", "LAL", "LAM",
  "LOK", "LOP", "LOR", "MİM", "PEY", "PUT", "PÜR", "RUN", "SAC", "SAK", "SKİ",
  "SOM", "SİM", "SİN", "TEM", "YEK", "YUH", "ZAT", "ÇAT", "ÇİP",
  "ÇİS", "ÇİŞ", "ÜRE", "ŞAK", "ŞER", "ŞOM",
  // 5 harfli bariz saçma/arkaik/yabancı kelimeler:
  "ABADİ", "ABALI", "ABANA", "ABAŞO", "ABBAS", "ABOSA", "ACUZE", "ACİBE", "ADESE",
  "AFİLİ", "AGAMİ", "AKABE", "AKAJU", "AKALA", "AKKÖY", "AKMAZ", "AKPAS", "AKSAK",
  "AKÇIL", "ALEVİ", "ALEYH", "ALGIN", "ALLEM", "ALMAŞ",
  "ALMUS", "ALTIZ", "ALİZE", "AMADE", "AMPİR", "ANACA", "ANDIK", "ANDIÇ", "ANLAK",
  "ANZAK", "ANÜRİ", "APOTR", "APOŞİ", "APSİS", "APİKO", "ARAKA", "ARGAÇ",
  "ARSİN", "ARİZA", "ASKAT", "ASKLI", "ASİDE", "AVAZE", "AVLAK", "AYNAZ", "AZVAY",
  "MEREK", "MUHİL", "MERES", "MEZRU", "MENUS", "MEHLE",
  "YAVAŞA", "YAVAŞAK", "YAVŞA", "YAVŞAK",
  "CAMİT", "FAHTE", "FAÇALI", "CARLI", "MAHCUR", "NAKİP", "MUHAT", "MAHUR", "REKİZ",
  "GABRO", "MUHİP", "RUHÇA", "RİCAL", "RÜKÜN", "RÜYET", "MEVUT", "GABİN", "REMİZ",
  "RECİM", "RÜSUM", "REVAK", "MİLEL", "MUTAT", "MÜHRE", "MUTAF", "FAÇUNA",
  "FANYA", "FASIK", "FASİT", "FİRAK", "FÜCUR", "FÜTUR", "CAĞLI", "CANFEZ", "CAVLAN",
  "PESEK",
  "ÇOKÇA",

  // --- Kısa (3-4 harfli) saçma / yabancı / çekimli / kaba kelimeler ---
  "ASK", "DEK", "HOR", "PÜF", "REY", "CİP", "KİT", "HİT", "ARK",
  "DONE", "PEST", "VURU", "İTKİ", "ADLI", "AKLI", "EĞİL", "EMMİ", "İRİN", "UYUZ", "PURO",
  "SEVİ", "GÖZE", "ELDE", "ONAR", "UÇLU", "YAĞI", "YAŞA", "ÖZGE", "ÇEKİ", "ÇOĞU", "ÜSTE",

  // --- Ağır ve Ölü Osmanlıca / Arapça / Farsça Terkibler ---
  "MUHAVVİL", "MUHAKKİK", "MUHACERET", "MUHAYYEL", "MÜNAZAA", "MÜNZEVİ", "MÜNFAİL", "MÜCAMAA", "MUTERİZ", "MÜCBİR",
  "MÜNEZZEH", "MÜHRESENK", "MÜEDDEP", "MÜCELLA", "MÜTALAA", "MÜFERRİH", "MÜREVVİÇ", "MÜECCEL", "MÜNTEHABAT", "TAANNÜT",
  "MUAREFE", "TAAYYÜN", "MUTASAVVER", "MUAŞERET", "MÜESSİF", "MUADDEL", "MÜSEVVİT", "MÜPTEDİ", "MÜDEBBİR", "MUTTASIF",
  "MUHADDİS", "TAKEOMETRE", "MÜNAKALAT", "MUTARİZA", "TAHRİR", "MÜNADİ", "MÜFTEHİR", "MURABAHA", "TAHACCÜM", "TAKARRÜR",
  "MUZLİM", "MÜLAZIM", "TAAMMÜT", "TAAMMÜM", "MUTAVASSIT", "TEFEYYÜZ", "TEFAHHUS", "MÜKRİM", "MÜFESSİR", "MÜNAKALE",
  "TAHRİF", "MUAHEZE", "MÜNKESİR", "TENSİKAT", "MUVAKKAT", "MUHTELİS", "TEKAÜDİYE", "TEFARİK", "TAHMİL", "MUHRİK",
  "MÜRTESEM", "MÜRURİYE", "MÜDRİKE", "MÜSAKKAFAT", "MÜLAYEMET", "MUKASSEM", "MÜSELLESAT", "MÜNFESİH", "MÜNTEHA", "MUAHEDE",
  "MUNSAP", "MUKARRER", "TARANTI", "TALAZ", "TAGADDİ", "MÜDRİR", "TENDÜRÜST", "TAAŞŞUK", "TAHATTUR", "TAYIN",
  "MÜLHİT", "MUADELE", "MUHTEVİ", "MÜFRET", "TENSİL", "TEFHİM", "MURASSA", "TANSIK", "MÜRDESENK", "MUATTAL",
  "TAKOMETRE", "TAHASSUN", "TALAZLIK", "MÜZAYAKA", "MUKATAALI", "TAVZİH", "MÜNHEZİM", "MÜRECCAH", "TASTİR", "MÜDDEİ",
  "TENAFÜR", "TEVALİ", "İNTİBAKSIZ", "TAAYYÜŞ", "TAKİM", "TEKFİR", "TEFTİH", "TENEVVÜ", "MUVAFIK", "MUTAZARRIR",
  "TARZİYE", "TENKİSAT", "MÜNTESİP", "MÜRTEFİ", "İNTİHABAT", "TAKALLÜS", "TAGAYYÜR", "MÜSEKKİN", "TAZAMMUN", "TARASSUT",
  "TAKANAK", "TENEZZÜH", "MÜZEVİR", "TAAFFÜN", "MUHASAMAT", "MÜNEKKİT", "MÜHTEDİ", "TARABA", "MÜLHAK", "MUHARRİŞ",
  "MUHASIR", "MUTTASIL", "MÜSABIK", "MUALLA", "MÜMTENİ", "MÜNTEŞİR", "TENSİP", "MUTASARRIF", "TALİMAR", "MÜBREM",
  "MÜMAS", "MÜYESSER", "TEVLİT", "MÜCAHEDE", "MUKAVVİ", "TAHARRİ", "MUTEKİT", "TAKLİP", "TAKİGRAF", "MÜRTEKİP",
  "MÜNHAL", "TENASÜH", "MUKADDESAT", "MUSİKAR", "TEVAZÜN", "MUSANNA", "MUSIR", "MUSANNİF", "MUACCİZ", "MUKAVVES",
  "TAHFİF", "MÜSELLİM", "TENASÜPSÜZ", "TARAFGİR",
  "TEBCİL", "TEBERRU", "TEBERRÜK", "TEBYİZ", "TEBŞİR", "TECAHÜL", "TECEMMU", "TECESSÜM", "TECZİYE", "TEDENNİ",
  "TEDVİN", "TEDVİR", "TEEHHÜR", "TEEMMÜL", "TEFENNİ", "TEGAFÜL", "TEHACÜM", "TELTİK", "TELVİS", "TEMADİ",
  "TEMARUZ", "TEMEDDÜH", "TEMERRÜT", "TEMESSÜL", "TENGE", "TEREDDİ", "TEREKE", "TERÜTAZE", "TESANÜT", "TESELLÜM",
  "TESHİN", "TESMİYE", "TESVİT", "TETABUK", "TEVŞİH", "TEZELLÜL", "TEZELZÜL", "TEZKİYE", "TEZVİRAT", "TEŞEHHÜT",
  "TEŞEVVÜŞ", "TEŞRİH", "TEŞRİHHANE", "TEŞVİŞ", "TAĞYİR", "MUAHHAR", "MUATTAR", "MUHATARA", "MÜŞEBBEH", "MÜŞEVVEŞ",
  "MÜŞEVVİK", "İHKAKIHAK", "İSTADYA", "İSTRALYA", "AMALİERBAA", "ASRISAADET", "LAAKAL", "AMİRİİTA", "ŞECAAT", "HAKPEREST", "KADİRŞİNAS",
  "BADEHU", "CEHİL", "NEZAHET", "BİHUŞ", "BİHAKKIN", "PAZVANT", "PEKENT", "BELİĞ", "CALİP", "CANİP", "EGLOG", "ESVAP",
  "GÜNEÇ", "HİZİP", "KALIÇ", "KOŞAÇ", "MAHIV", "NAHİV", "NESEP", "SALİP", "TOKAÇ", "HALFA", "HAVVA", "KAVAF", "DETANT", "AMYANT",

  // --- Nadir / Yapay Ek Türetimleri (-AÇ, -EÇ, -İÇ, -MEÇ, -GAÇ vb.) ---
  "YOĞUNLAÇ", "BOŞALTAÇ", "YALAVAÇ", "DİKEÇ", "ATLAMBAÇ", "BİİLAÇ", "İMTİZAÇ", "KÖMEÇ", "AKITAÇ", "YANSITAÇ",
  "POTLAÇ", "KURUTMAÇ", "KAVURMAÇ", "DARAÇ", "SUNTIRAÇ", "KAKAÇ", "DURAÇ", "YELEÇ", "PEÇİÇ", "TEHYİÇ",
  "TERVİÇ", "KAVLIÇ", "BADIÇ", "DELGİÇ", "EZGİÇ", "ALDANGIÇ", "YAKMAÇ", "YANILTMAÇ", "YIKAMAÇ", "ÇALGIÇ",
  "ÖDEGEÇ", "GÖSTERGEÇ", "DOĞRULTMAÇ", "KARMAÇ", "GÜCÜK", "BULGURCUK", "BÜRÜMCÜK", "ÇAMURCUK", "ÇOĞURCUK", "HAVUZCUK",
  "PÜSKÜLCÜK", "PATLANGAÇ", "TUTTURGAÇ",

  // --- Aşırı Akademik / Kimyasal / Felsefi / Yabancı Jargon ---
  "DEKSTRİN", "DEKSTROZ", "EKSTRAFOR", "GOŞİST", "SLAVİSTİK", "SLAVİST", "NEOFAŞİST", "NATİVİZM", "SEMİTİZM", "TELEOLOJİK",
  "TÜRKOLOJİK", "NEOLOJİZM", "AEROLOJİ", "ALŞİMİST", "ANEMOMETRE", "ASİDİMETRE", "ARYANİST", "ARYANİZM", "BAPTİST", "BAROGRAF",
  "BATİMETRE", "BOLOMETRE", "BOLŞEVİZM", "DANSİMETRE", "DEKAMETRE", "EKONOMİZM", "ENTEROGRAF", "FİDEİZM", "FİNALİZM", "FÜZYOMETRE",
  "GAZOMETRE", "GRAFOLOJİ", "HELENİST", "HELENİSTİK", "HELYOGRAF", "KABALİST", "KARTOGRAF", "KRİPTOLOJİ", "KRİTİSİZM", "LAMAİST",
  "LENGÜİSTİK", "MANOMETRE", "MİKROMETRE", "NARKOTİZM", "OPORTÜNİST", "OPORTÜNİZM", "OTOGRAFİ", "OŞİNOGRAFİ", "PALEOGRAFİ", "PANTEİST",
  "PANTEİZM", "PANTOGRAF", "PANTÜRKİZM", "PARNASİZM", "PLÜRALİST", "POLİTEİST", "POLİTEİZM", "POZİTİVİZM", "PRAGMATİST", "PİKNOMETRE",
  "PİROMETRE", "RADYOMETRE", "RASİST", "SADİST", "SADİZM", "SENKRETİZM", "STENOGRAFİ", "SÜRREALİZM", "TAŞİZM", "TOPOLOJİK",
  "TİPOGRAFİ", "TİPOLOJİK", "VİROLOJİ", "ÇİNKOGRAF", "ÜTOPİST", "ŞAPİROGRAF", "ŞİNTOİZM", "REEKSPORT", "DEKASTER", "VİNTER",
  "ŞVESTER", "PLASTER", "OBERJ", "POLİSAJ", "TRİKOTAJ", "JİKLE", "MODELAJ", "AJİTASYON", "JAKARLI", "MULTİPLEKS", "APSENT", "ŞETLANT",

  // --- Tıbbi / Patolojik / Uygunsuz / Kaba ---
  "SİROZLU", "FİSTÜL", "KANSERLİ", "İLTİHAPLI", "LARENJİT", "ANALJEZİ", "TESTİS", "ERDİŞİ", "AVRAT", "ANALI",

  // --- Özel Yer / İlçe / Şehir / Yabancı Etnik İsimler ---
  "ERBAA", "KOCAALİ", "KONYAALTI", "DOMANİÇ", "MUSABEYLİ", "ABORJİN", "NİJERYALI", "ARJANTİNLİ", "ARJANTİN",
  "AHIRLI", "AKKIŞLA", "AKÇAKENT", "ALACAKAYA", "ALTINOVA", "ALTINTAŞ", "ALTINÖZÜ", "ANTALYA", "ARICAK",
  "ARNAVUTKÖY", "ARTOVA", "ARİFİYE", "ASLANAPA", "ATAKUM", "AVANOS", "AYDINTEPE", "AZDAVAY", "BABADAĞ",
  "BALÇOVA", "BASKİL", "BAYAT", "BAYRAKLI", "BAYRAMPAŞA", "BOĞAZKALE", "BURSA", "BİLECİK", "CUMAYERİ",
  "DADAY", "DARGEÇİT", "DENİZLİ", "DERİK", "DERİNKUYU", "DEVELİ", "DEVREK", "DOĞANYOL", "DOĞANYURT",
  "DOĞANŞAR", "DOĞANŞEHİR", "DUMLUPINAR", "DİNAR", "ERFELEK", "ERMENEK", "ERZİN", "FERİZLİ", "GAZİANTEP",
  "GEBZE", "GELENDOST", "GEREDE", "GERZE", "GEYVE", "GÖLYAKA", "GÖYNÜCEK", "GÜLAĞAÇ", "GÜMÜŞOVA", "GİRESUN",
  "HAMAMÖZÜ", "HANÖNÜ", "HARMANCIK", "HONAZ", "HİSARCIK", "IĞDIR", "KARAKEÇİLİ", "KARATAY", "KAYNAŞLI",
  "KEÇİBORLU", "KIRŞEHİR", "KIZILTEPE", "KOZAKLI", "LALAPAŞA", "MALATYA", "MALTEPE", "MAZIDAĞI",
  "MERSİN", "MERZİFON", "MİHALIÇÇIK", "NEVŞEHİR", "NUSAYBİN", "NİZİP", "OSMANCIK", "OSMANELİ", "OSMANGAZİ",
  "PAMUKOVA", "SAKARYA", "SAMSUN", "SENİRKENT", "SEYİTGAZİ", "SORGUN", "SULAKYURT", "SULTANGAZİ", "SULUSARAY",
  "SUMBAS", "SUŞEHRİ", "TAVŞANLI", "TEFENNİ", "TOMARZA", "TUZLA", "TÜRKELİ", "VEZİRKÖPRÜ", "YAKAKENT",
  "YAPRAKLI", "YAYLADERE", "YENİÇAĞA", "YEŞİLHİSAR", "YEŞİLOVA", "ZONGULDAK", "ÇAMARDI", "ÇANAKKALE",
  "ÇAVDIR", "ÇAYIROVA", "ÇEKMEKÖY", "ÇİFTLİKKÖY", "ÜSKÜDAR", "İNHİSAR", "ŞAHİNBEY", "ŞAPHANE", "ŞEFAATLİ", "ÖMERLİ",

  // --- Saçma Scrabble "-siz/-suz" Ekli Sözcükler ---
  "KAMYONSUZ", "LAVABOSUZ", "KOCASIZ", "ALTSIZ", "CİNSLİKSİZ", "AKIŞMASIZ", "ALINDISIZ", "ANTETSİZ", "AYRICASIZ", "AZATSIZ",
  "BADİRESİZ", "BETİSİZ", "BİLİSİZ", "BİYESİZ", "CARSIZ", "CAZSIZ", "DOKUNCASIZ", "DOĞRUSUZ", "DULDASIZ", "DÖŞEMSİZ",
  "DİRLİKSİZ", "ELDESİZ", "ELEMESİZ", "ETENESİZ", "EŞLEMESİZ", "FARBASIZ", "FERACESİZ", "FOSFATSIZ", "FİLARSIZ", "FİSTANSIZ",
  "GAİLESİZ", "HARESİZ", "HAŞILSIZ", "HELEZONSUZ", "KALAFATSIZ", "KALIMSIZ", "KALKERSİZ", "KAMASIZ", "KAVKISIZ", "KERATİNSİZ",
  "KONÇSUZ", "KOZASIZ", "KUMASIZ", "KUSKUNSUZ", "KÜFESİZ", "KİLSİZ", "LATASIZ", "LAVANTASIZ", "MAHFAZASIZ", "MANYETOSUZ",
  "MANİKÜRSÜZ", "MİNTANSIZ", "NALINSIZ", "NALÇASIZ", "NATIKASIZ", "NAZİRSİZ", "NOHUTSUZ", "PALANGASIZ", "PALTOSUZ", "PAPATYASIZ",
  "PERTAVSIZ", "PEÇESİZ", "PEÇETESİZ", "POSTSUZ", "POŞUSUZ", "PÜRTÜKSÜZ", "PİLİSİZ", "RİMELSİZ", "RİZİKOSUZ", "SEBZESİZ",
  "SECİYESİZ", "SİGARASIZ", "TANECİKSİZ", "TAPASIZ", "TENTENESİZ", "TENTESİZ", "TIPASIZ", "TOPSUZ", "TOPUKSUZ", "TUTKALSIZ",
  "TÖRELSİZ", "UFUNETSİZ", "URBASIZ", "UYARSIZ", "VAZELİNSİZ", "VUKUFSUZ", "VURUNTUSUZ", "VUZUHSUZ", "VİDASIZ", "YAMÇISIZ",
  "YANSIMASIZ", "YANSIZ", "YARAŞIKSIZ", "YEMLİKSİZ", "YUNDUSUZ", "ZAMSIZ", "ZEVALSİZ", "ZIVANASIZ", "ÇAPASIZ", "ÇARŞISIZ",
  "ÇEKMECESİZ", "ÇOBANSIZ", "ÇOCUKSUZ", "ÇOMAKSIZ", "ÇİNKOSUZ", "ÇİNİSİZ", "ÇİVİSİZ", "ÖDÜNSÜZ", "ÖRGÜTSÜZ", "ÜRKÜSÜZ",
  "ÜTÜSÜZ", "İDRAKSİZ", "İHTİYARSIZ", "İNZİBATSIZ", "İSPİRTOSUZ", "İTİKATSIZ", "ŞAKIRTISIZ", "ŞAMDANSIZ", "ŞEREFESİZ", "ŞİFASIZ",
  "ŞİKESİZ", "ŞİMŞEKSİZ", "MUİNSİZ", "TABİATSIZ", "İHTİRASSIZ",

  // --- Akraba / Diyalektik Türetimler ---
  "TEYZEZADE", "HALAZADE", "HARAMZADE", "AMCAZADE", "KÖFTER",

  // --- Kullanıcı isteğiyle kaldırılan kelimeler (Batch 6) ---
  "ABACILIK", "ABLAKLIK", "AKMANTAR", "AKSONA", "ALDANÇ", "ALIKLIK", "ALINLIK",
  "ASKINTILIK", "ATIMCILIK", "BIRAKIT", "BOĞALIK", "BURUNDURUK", "BURUNSALIK",
  "CIZBIZ", "DIRILTI", "DİNGİLDEK", "DİVLEK", "DOKURCUN", "DOMALIŞ", "DONRA",
  "GULGULE", "KAKNEM", "KALKIKLIK", "KANCUR", "KARAKAVUK", "KARKAS", "KASNI",
  "ZEYTİNSİZ", "ZEYTİNLİ",

  // --- Element isimleri (teknik, oyunda yeri yok) ---
  "DİSPROSYUM", "ERBİN", "FERMİYUM", "FRANSİYUM", "HAFNİYUM", "İNDİYUM", "İRİDYUM",
  "KALSİYUM", "LORENTİYUM", "LÜTESYUM", "MOLİBDİN", "OSMİYUM", "SKANDİYUM",
  "STRONSİYUM", "TEKNETYUM", "TANTAL", "URANYUM", "ZİRKONYUM",

  // --- Tıbbi / biyolojik terimler ---
  "ANESTEZİST", "ANJİYO", "BRONŞİT", "DİSPANSER", "EMBOLİ", "ENSEFALİT",
  "FAGOSİTOZ", "FİBRİN", "FİSSÜR", "FLEBİT", "GLOBÜLİN", "GLOKOM", "GONOKOK",
  "HAPLOİT", "HEMOFİLİ", "HEMOROİT", "HİSTOLOJİ", "KATALEPTİK", "KİNESTEZİ",
  "MELANİT", "MELİNİT", "MENÜSKÜS", "NEVRASTENİ", "ORKİT", "ORTODONTİ",
  "PEROKSİT", "PERİTONİT", "PEPSİN", "PEPTON", "PONKSİYON", "RAŞİTİK",
  "SİNARİT", "SİNÜZİT", "SİTOTOKSİK", "SPASTİK", "TRAHOM", "TRİKOSEFAL",
  "TÜBERKÜLOZ", "TÜBERKÜLİN",

  // --- İngilizce / yabancı kelimeler ---
  "AVATAR", "BİLLBOARD", "BLENDER", "PACEMAKER", "PINGPONG", "PLAYBACK",
  "RADAR", "SCOREBOARD", "SKORBORD", "SLALOM", "SMOKİN", "STENO", "STOR",
  "TİŞÖRT", "TREND", "YOGA",

  // --- Özel isim / yer / kişi adı ---
  "ALTINDAĞ", "CİHANGİR", "MERKÜR", "MERİH", "MOSKOF", "TUĞRUL",
  "UGANDALI", "UKRAYNALI",

  // --- Osmanlıca / arkaik / günlük dışı ---
  "AFOROZ", "ARKAÜSTÜ", "BAHRİYE", "DEFTERDAR", "DEFTERHANE", "FERASET",
  "FETVA", "FETVAHANE", "GAYBUBET", "GAZEL", "GAZELİYAT", "HARABAT",
  "HARABATİ", "HARABİYET", "HARAMİ", "İMARETHANE", "KERHANE", "MAHREK",
  "MAHRUKAT", "MAHSUP", "MUSİKİ", "NAFİLE", "NAKKARHANE", "NAKŞİBENDİ",
  "NAZARİ", "SELATİN", "MURAKABE", "MURİS", "MUSİBET", "MUSKA"
]);


// Senior QA Stem Filter: Removes possessive, case, participial and artificial derived suffixes
const ARTIFICIAL_SUFFIX_REGEX = /(Sİ|SÜ|SU|SI|LİK|LUK|LÜK|MA|ME|MELİ|MALI|MEK|MAK|Cİ|CU|CÜ|CI|Çİ|ÇU|ÇÜ|ÇI|SEL|SAL|MACA|MECE|EN|AN|LENME|LANMA|ULMA|İLME|CA|CE|ÇA|ÇE)$/;

// Living Turkish natural infinitives (approved core verbs)
const NATURAL_INFINITIVES = [
  "SEVMEK", "GÖRMEK", "KOŞMAK", "BİLMEK", "YAŞAMAK", "ÇÖZMEK", "ANLAMAK", "YÜRÜMEK", "YAZMAK", "OKUMAK",
  "DUYMAK", "BULMAK", "GÜLMEK", "BAKMAK", "GEZMEK", "UÇMAK", "YÜZMEK", "DÜŞÜNMEK", "BAŞLAMAK", "ÖĞRENMEK",
  "ANLATMAK", "ÇALIŞMAK", "KAZANMAK", "KORUMAK", "PAYLAŞMAK", "DİNLEMEK", "DURMAK", "KALKMAK", "OTURMAK", "KONUŞMAK",
  "BEKLEMEK", "BİTİRMEK", "DÖNMEK", "SEÇMEK", "İSTEMEK", "DENEMEK", "YAPMAK", "GİTMEK", "GELMEK", "ALMAK",
  "VERMEK", "AÇMAK", "KAPAMAK", "BULUŞMAK", "YAKALAMAK", "SAVUNMAK", "KUTLAMAK", "YENMEK", "YARIŞMAK",
  "SÖYLEMEK", "SORMAK", "GİRMEK", "ÇIKMAK", "BİTMEK", "İÇMEK", "UNUTMAK", "HATIRLAMAK", "AĞLAMAK",
  "KALMAK", "OLMAK", "ETMEK", "DEMEK", "TANIMAK", "İNANMAK", "KULLANMAK", "HAZIRLAMAK", "TEMİZLEMEK",
  "PİŞİRMEK", "YIKAMAK", "GİYMEK", "TUTMAK", "BIRAKMAK", "ATMAK", "ÇEKMEK", "KESMEK", "TAŞIMAK",
  "GETİRMEK", "GÖTÜRMEK", "GÖNDERMEK", "SATMAK", "ÖDEMEK", "SAYMAK", "GEÇMEK", "KOYMAK", "AÇIKLAMAK",
  "KAPATMAK", "ÖĞRETMEK", "ÇİZMEK", "BOYAMAK", "SEVİNMEK", "KORKMAK", "ŞAŞIRMAK", "DÜŞMEK", "YATMAK",
  "BAĞIRMAK", "ÖPMEK", "SARILMAK", "DOKUNMAK", "HİSSETMEK", "PLANLAMAK", "UYGULAMAK", "BEĞENMEK",
  "YAKMAK", "SÖNDÜRMEK", "ISITMAK", "SOĞUTMAK", "DOLDURMAK", "BOŞALTMAK", "KARŞILAMAK", "UĞRAMAK",
  "ÇAĞIRMAK", "GÖRÜŞMEK", "ANLAŞMAK", "TARTIŞMAK", "REDDETMEK", "KABULLENMEK", "GÖSTERMEK", "CEVAPLAMAK"
];

// Whitelist of valid stem words that coincidentally end with suffix patterns
const STEM_WHITELIST = new Set([
  "MEYVE", "GÜNEŞ", "ELMA", "YÜZME", "ÇİZME", "KALE", "DÜME", "KÜME", "KİME", "DİME",
  "ÇEŞME", "BÖLME", "DÖNME", "GÖRME", "GELME", "ORMAN", "ADAM", "KADIN", "İNSAN", "VADİ",
  "SAHİL", "KENT", "ŞEHİR", "DUVAR", "TAVAN", "MASA", "KAPILMA", "SARMA", "DOLMA", "KIZARTMA",
  "FOTOSENTEZ", "EKOSİSTEM", "BAHÇE", "PARÇA", "DİLEKÇE", "KEMENÇE", "ORTANCA", "İMECE", "AMCA", "GONCA",
  "SERÇE", "İŞKENCE", "TABANCA", "KARINCA", "DÜŞÜNCE", "GÜVENCE", "EĞLENCE",
  "SÖYLENCE", "DİRENCE", "GÖRÜMCE", "BİLMECE", "BULMACA", "ÇEKMECE", "DÖNENCE",
  "LONCA", "İLTİCA",
  ...NATURAL_INFINITIVES
]);


const THEME_WORDS: Record<Exclude<WordTheme, "general">, readonly string[]> = {
  nature: [
    "ADA", "ARI", "BAL", "DAL", "GÖL", "GÜL", "KUM", "TAŞ", "YAZ", "AĞAÇ", "BİTKİ", "ÇİMEN", "KARA", "VADİ", "DERE", "KAYA", "KURT", "GEYİK",
    "DENİZ", "ÇİÇEK", "BAHÇE", "ORMAN", "SAHİL", "BULUT", "NEHİR", "DALGA", "BALIK", "ASLAN", "KAPLAN", "BUZUL", "YOSUN", "ZİRVE", "YAMAÇ", "TABİAT", "VOLKAN",
    "YAPRAK", "YAĞMUR", "TOPRAK", "MEVSİM", "RÜZGAR", "KANYON", "MAĞARA", "OKYANUS", "TAVŞAN", "KUMSAL", "MERCAN", "TUNDRA", "TAYFUN", "YILDIRIM", "FIRTINA", "ŞİMŞEK", "ŞELALE", "EKOSİSTEM", "FOTOSENTEZ", "MANGROV", "SARMAŞIK", "TROPİKAL",
    "GÖKKUŞAĞI", "YANARDAĞ", "KUTUPAYISI", "BUZULLAR"
  ],
  city: [
    "ODA", "KAPI", "KENT", "YOL", "PARK", "BİNA", "KULE", "YAYA", "ÇATI", "OTEL",
    "ŞEHİR", "YOLCU", "SEFER", "SOKAK", "CADDE", "KÖPRÜ", "PAZAR", "METRO", "ARABA", "LİMAN", "SİTE",
    "HARİTA", "PUSULA", "MACERA", "TİYATRO", "SİNEMA", "MARKET", "DÜKKAN", "OTOBÜS", "TRAFİK", "BALKON", "MEYDAN", "OTOGAR", "BULVAR", "KAVŞAK", "VİYADÜK", "SANAYİ",
    "MAHALLE", "TRAMVAY", "BİSİKLET", "ASANSÖR", "PENCERE", "RESTORAN", "İSTASYON", "GÖKDELEN", "BELEDİYE", "OTOPARK", "KAMUSAL",
    "YOLCULUK", "MERDİVEN", "METROPOL", "MİMARİ", "ÜSTGEÇİT", "ALTGEÇİT", "ALTYAPI", "ŞEHİRCİLİK", "URBANİZASYON"
  ],
  mind: [
    "DİL", "SES", "OYUN", "RİSK", "ÖLÇÜ", "İZİN", "AKIL", "ZEKA", "OKUL", "DERS", "SORU", "ZEKİ",
    "BİLGİ", "ÇÖZÜM", "DENGE", "GİZEM", "FİKİR", "BEYİN", "KİTAP", "SINAV", "CEVAP", "TEORİ", "SANAT", "MERAK", "DENEY", "BİLİM", "ŞUUR", "İDRAK", "KAVRAM",
    "KELİME", "HAFIZA", "EĞİTİM", "DEFTER", "MANTIK", "FORMÜL", "SÖZLÜK", "DİKKAT", "SEZGİ", "ANALİZ", "HİPOTEZ", "BİLİNÇ",
    "BİLMECE", "BULMACA", "GİZEMLİ", "ANLAMLI", "BİLİNMEZ", "HATIRLA", "DÜŞÜNCE", "ÖĞRENME", "FELSEFE", "EDEBİYAT", "ÇIKARIM", "AKADEMİK",
    "ALGORİTMA", "KOGNİTİF", "PSİKOLOJİ", "METODOLOJİ", "BİLİNÇALTI", "MUHAKEME", "ANSİKLOPEDİ"
  ],
  space: [
    "GÖK", "UZAY", "FÜZE", "UYDU", "IŞIK",
    "GÜNEŞ", "EVREN", "MEKİK", "ROKET", "KÜTLE", "ÇEKİM", "FOTON", "BOŞLUK", "KUŞAK", "SONDA", "ROVER",
    "YILDIZ", "GEZEGEN", "METEOR", "NEBULA", "KRATER", "SİSTEM", "PULSAR", "KUAZAR", "SATÜRN", "PLÜTON", "MODÜL", "KAPSÜL", "IŞIMAK",
    "GALAKSİ", "YÖRÜNGE", "ASTRONOM", "KOZMONOT", "IŞIKHIZI", "GÖKTAŞI", "KIZILÖTE", "RADYASYON", "İSTASYON",
    "ASTRONOT", "SAMANYOLU", "KARADELİK", "ASTEROİT", "METEORİT", "GÖZLEMEVİ", "TELESKOP", "TEKİLLİK", "SÜPERKÜME", "ATMOSFER",
    "SÜPERNOVA", "ÖTEGEZEGEN", "ASTROFİZİK", "KUTUPYILDIZI", "KÜTLEÇEKİM", "YERÇEKİMİ", "YILDIZTOZU"
  ],
  sports: [
    "GOL", "ŞUT", "PAS", "LİG", "MAÇ", "KOŞU", "KALE", "FİLE", "POTA", "KASK", "SPOR",
    "TAKIM", "RAKET", "HAKEM", "KUPA", "ATLET", "GÜREŞ", "YARIŞ", "REKOR", "BOKSÖR", "HÜCUM", "KAPTAN",
    "FUTBOL", "BASKET", "TENİS", "MADALYA", "PARKUR", "DEFANS", "TRİBÜN", "NAKAVT", "PERİYOT",
    "STADYUM", "MARATON", "PENALTI", "TURNUVA", "BİSİKLET", "VOLEYBOL", "HENTBOL", "DEPLASMAN",
    "ANTRENMAN", "ŞAMPİYON", "OLİMPİYAT", "KONDİSYON", "TARAFTAR", "MÜCADELE", "DİSİPLİN", "ŞAMPİYONLUK"
  ],
  food: [
    "TUZ", "BAL", "YAĞ", "SÜT", "ÇAY", "AŞÇI", "FIRIN", "OCAK", "TARİF", "ÇORBA", "PİLAV", "SEBZE", "MEYVE", "TATLI",
    "EKMEK", "LEZZET", "YEMEK", "TUZLU", "ŞEKER", "TAVUK", "BALIK", "KAHVE", "BÖREK", "KÖFTE", "IZGARA", "ŞERBET", "PEYNİR", "MEZE", "HELVA", "MANTI",
    "MUTFAK", "BAHARAT", "KAVURMA", "DONDURMA", "PASTA", "SOSLAR", "İÇECEK", "GURME", "ZİYAFET", "SUNUM", "MENEMEN", "BAKLAVA",
    "KIZARTMA", "RESTORAN", "APARATİF", "ENGİNAR", "KAHVALTI", "TEREYAĞI",
    "GASTRONOMİ", "ZEYTİNYAĞLI", "AKŞAMYEMEĞİ"
  ]
};

export { THEME_WORDS };

const TR_WORD_RE = /^[ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ]+$/;

function isValidCatalogWord(word: string) {
  return word.length >= 3 && word.length <= 15 && TR_WORD_RE.test(word) && !WORD_BLACKLIST.has(word);
}

function difficultyForLength(len: number): WordDifficulty {
  if (len <= 5) return "easy";
  if (len <= 7) return "medium";
  return "hard";
}

/** Everyday Turkish words a typical player would actually know. */
const EXTRA_EVERYDAY_WORDS = [
  "GÜN", "BAL", "TUZ", "SÜT", "ÇAY", "YAĞ", "GÖL", "GÜL", "TAŞ", "YOL", "SES", "GÖZ",
  "ANA", "NAR", "KUŞ", "KAZ", "ARI", "ADA", "DAĞ", "KUM", "KAR", "YIL", "YAZ", "KIŞ",
  "SAÇ", "YÜZ", "DİL", "DİŞ", "KOL", "BAŞ", "TOP", "ODA", "GOL", "MAÇ", "ZİL", "BOT",
  "DAL", "KÖK", "BİR", "İKİ", "ÜÇ", "BİN", "YÜN", "FİL", "AYI", "MOR", "GRİ", "DAR",
  "PAS", "LİG", "ŞUT", "GÖK", "MUM", "RAY", "HIZ", "KIZ", "KÖY", "ATEŞ", "SİS", "PUL",
  "RAF", "ÇİM", "SAHA", "YUVA", "OLTA", "KOKU", "KRAL", "YELE", "GÜÇ", "EYER",
  "SÜRÜ", "GAGA", "LALE", "ÇAM", "MEŞE", "BEŞ", "ALTI", "YEDİ", "DÖRT", "SEKİZ", "DOKUZ",
  "BABA", "DOST", "AİLE", "ELMA", "MUZ", "ÜZÜM", "KEDİ", "İNEK", "KEÇİ", "KAPI", "MASA",
  "SAAT", "OKUL", "DERS", "OYUN", "TREN", "UÇAK", "GEMİ", "AĞAÇ", "PARK", "HAVA", "GECE",
  "MAVİ", "SARI", "UZUN", "KISA", "YENİ", "ESKİ", "UMUT", "AĞIZ", "KALP", "PARA", "KART",
  "KUTU", "KASA", "DANS", "FİLM", "ŞİİR", "TOST", "MONT", "ETEK", "ATKI", "HARF", "SORU",
  "RÜYA", "PİL", "LİSE", "KURS", "OFİS", "ANNE", "DEDE", "NİNE", "AMCA", "DAYI",
  "UYKU", "İĞNE", "DOLU", "KALE", "KUPA", "MAYO", "KAMP", "ÇATI", "BACA", "YARA", "LİRA",
  "FİŞ", "ZARF", "OCAK", "TAVA", "RENK", "KARE", "SAYI", "SİTE", "ACİL", "BANK", "BERE",
  "SPOR", "PUAN", "UZAY", "BOYA", "ZEKA", "NEŞE", "TÜY", "KÖPEK", "KOYUN", "HOROZ", "KURT",
  "YILAN", "FARE", "SİLGİ", "ÇANTA", "SINIF", "SINAV", "ÖDEV", "BEBEK", "TAKSİ",
  "METRO", "MOTOR", "BULUT", "ORMAN", "ÇİÇEK", "BAHÇE", "NEHİR", "DÜNYA", "SABAH", "ÖĞLE",
  "AKŞAM", "HAFTA", "YEŞİL", "BEYAZ", "SİYAH", "PEMBE", "BÜYÜK", "KÜÇÜK", "SICAK", "SOĞUK",
  "SERT", "HIZLI", "YAVAŞ", "GÜZEL", "MUTLU", "ÜZGÜN", "KORKU", "ÖFKE", "SEVGİ", "BARIŞ",
  "KULAK", "BURUN", "AYAK", "POLİS", "AŞÇI", "ŞOFÖR", "YAZAR", "KOŞU", "TENİS", "FIRIN",
  "KASAP", "MANAV", "KAFE", "MÜZE", "HAVUZ", "PLAJ", "DURAK", "KÖPRÜ", "CADDE", "SOKAK",
  "ÜLKE", "BAKAN", "BANKA", "FİYAT", "HEDİYE", "MÜZİK", "ŞARKI", "MASAL", "KAHVE",
  "AYRAN", "SUCUK", "SİMİT", "PİZZA", "KAĞIT", "KİLİT", "CEKET", "GÖMLEK", "ÇORAP", "ŞAPKA",
  "DÜĞÜN", "BAYRAM", "TATİL", "TAHTA", "SKOR", "YEMEK", "BİLGİ", "CEVAP", "FİKİR", "HAYAL",
  "DOĞRU", "KOLAY", "MESAJ", "RADYO", "ŞARJ", "KUZEN", "TORUN", "SABUN", "HAVLU", "TARAK",
  "MAKAS", "İPLİK", "MEYVE", "SEBZE", "TATLI", "ŞEKER", "ÖNLÜK", "FORMA", "HAKEM", "KAYIK",
  "FENER", "DOĞA", "BALON", "GARAJ", "İLAÇ", "HASTA", "ADRES", "PAPATYA", "SÖĞÜT", "TOHUM",
  "TABAK", "KAŞIK", "ÇATAL", "BIÇAK", "BARDAK", "YATAK", "DOLAP", "PERDE", "HALI",
  "SULUK", "DAİRE", "ÜÇGEN", "BİLET", "VALİZ", "OTEL", "EKRAN", "DERGİ", "GAZETE", "SAHNE",
  "TABLO", "HEYKEL", "TARİH", "ESER", "KAYAK", "YARDIM", "ROKET", "REÇEL", "BİBER", "SOĞAN",
  "HAVUÇ", "TEKNE", "DAMLA", "BİNA", "TARLA", "SAYFA", "SANAT", "SOFRA", "AÇLIK", "ÇEŞME",
  "KABUK", "DİLİM", "SERİN", "KANAT", "KOVAN", "ÇAYIR", "KÜMES", "SADIK", "ŞEKİL", "LEVHA",
  "IŞIK", "TÜNEL", "SÖZLÜK", "HİKAYE", "ROMAN", "ANAHTAR", "GÖZLÜK", "HAZİNE", "KELİME",
  "GERÇEK", "YANLIŞ", "KAMERA", "FABRİKA", "MAĞAZA", "TEYZE", "YASTIK", "YORGAN", "ŞAMPUAN",
  "KANTİN", "FUTBOL", "YENGEÇ", "ÇADIR", "SAĞLIK", "CÜZDAN", "OTOBAN", "MEKTUP", "POSTANE",
  "MENEKŞE", "SÜMBÜL", "TENCERE", "KOMODİN", "AKTÖR", "ÇİZME", "BASKET", "ZEYTİN",
  "PİLAV", "ÇORBA", "KÖFTE", "BALIK", "PASTA", "TAVUK", "ARMUT", "KİRAZ", "ÇİLEK", "KAVUN",
  "İNCİR", "SALATA", "YOĞURT", "PATATES", "DOMATES", "LAHANA", "NOHUT", "PİRİNÇ", "TAVŞAN",
  "ÖRDEK", "ASLAN", "KAPLAN", "GEYİK", "MAYMUN", "ZEBRA", "KELEBEK", "SİNCAP",
  "KURBAĞA", "KARTAL", "SERÇE", "SALON", "MUTFAK", "BANYO", "KOLTUK", "DUVAR", "TAVAN",
  "ZEMİN", "AYNA", "TABLET", "KALEM", "DEFTER", "KİTAP", "ARABA", "OTOBÜS", "KAMYON",
  "YILDIZ", "YAĞMUR", "RÜZGAR", "DENİZ", "YAPRAK", "ÇİMEN", "TOPRAK", "GÖKYÜZÜ", "GENİŞ",
  "YUMUŞAK", "ÇİRKİN", "SEVİNÇ", "PARMAK", "BACAK", "ÇİFTÇİ", "OYUNCU", "RESSAM",
  "SPORCU", "YÜZME", "ECZANE", "MARKET", "SİNEMA", "MEYDAN", "ŞEHİR", "MİLLET", "BAYRAK",
  "POĞAÇA", "PANTOLON", "ELDİVEN", "MACERA", "BULMACA", "İNTERNET", "KULAKLIK",
  "FAKÜLTE", "İLKOKUL", "MESAİ", "İŞYERİ", "KAHVALTI", "NEVRESİM", "TENEFFÜS", "STADYUM",
  "ŞEMSİYE", "YÜRÜYÜŞ", "KUTLAMA", "BALKON", "ÖKSÜRÜK", "BANDAJ", "VİTAMİN", "İNDİRİM",
  "KAVŞAK", "KARANFİL", "BUZDOLABI", "BULAŞIK", "SANDVİÇ", "PASAPORT", "KLAVYE", "AKTRİS",
  "SALINCAK", "KAYDIRAK", "MANZARA", "SESSİZ", "KAPTAN", "RİTİM", "FIRÇA", "KAHKAHA",
  "SÜRPRİZ", "ZİYARET", "SOHBET", "SALKIM", "ÇEKİRDEK", "GEVREK", "HORTUM", "ÇİFTLİK",
  "KARDEŞ", "ÇOCUK", "ARKADAŞ", "İNSAN", "KADIN", "ERKEK", "OĞLAN", "PORTAKAL", "KARPUZ",
  "ŞEFTALİ", "PEYNİR", "YUMURTA", "MAKARNA", "BİSKÜVİ", "SARIMSAK", "ISPANAK", "FASULYE",
  "MERCİMEK", "BAHARAT", "PAPAĞAN", "GÜVERCİN", "SANDALYE", "PENCERE", "TELEFON", "OYUNCAK",
  "BİSİKLET", "TRAKTÖR", "FIRTINA", "OKYANUS", "SONBAHAR", "İLKBAHAR", "TURUNCU", "DOSTLUK",
  "HEMŞİRE", "İTFAİYE", "AVUKAT", "HAKİM", "SANATÇI", "HASTANE", "RESTORAN", "TİYATRO",
  "İSTASYON", "LİMONATA", "HAMBURGER", "AYAKKABI", "YOLCULUK", "KAYBETMEK", "BAŞARMAK",
  "OYNAMAK", "UYUMAK", "UYANMAK", "ARAMAK", "UYGULAMA", "ANAOKULU", "HAFTASONU", "ŞİMŞEK",
  "MERDİVEN", "ASANSÖR", "PAZARLIK", "KARTPOSTAL", "KALABALIK", "TEKERLEK", "DOĞUMGÜNÜ",
  "GÖZYAŞI", "SEVİMLİ", "TİLKİ", "PENGUEN", "MANDALİNA",
  "DONDURMA", "ÇİKOLATA", "SALATALIK", "KAPLUMBAĞA", "TELEVİZYON", "BİLGİSAYAR", "HELİKOPTER", "GÖKKUŞAĞI", "PAZARTESİ", "ÇARŞAMBA", "PERŞEMBE", "CUMARTESİ",
  "KAHVERENGİ", "MUTLULUK", "MÜHENDİS", "MÜZİSYEN", "FUTBOLCU", "BASKETBOL", "VOLEYBOL",
  "KÜTÜPHANE", "HAVAALANI", "BELEDİYE", "CUMHURİYET", "ALIŞVERİŞ", "FOTOĞRAF", "ÜNİVERSİTE",
  "TEREYAĞI", "BALKABAĞI", "KÖPEKBALIĞI", "DİKDÖRTGEN", "ANSİKLOPEDİ",
  "TAHTEREVALLİ", "ESİNTİ", "YÜKSEK", "KIRMIZI", "GÜNEŞ", "EKMEK", "SALI", "CUMA", "PAZAR",
  "ADAM", "TAKIM", "DALGA", "RESİM", "HARİTA", "ZOR", "KASK", "LİMAN", "LEZZET"
] as const;

/** Extra well-known words to keep boards varied without obscure catalog terms. */
const EXTRA_EVERYDAY_MORE = [
  "CAN", "ÇOK", "YOK", "VAR", "BEN", "SEN", "BİZ", "SİZ", "TAM", "SON", "ALT", "ÜST",
  "CAM", "KAN", "BUZ", "CEP", "ÇÖL", "ÇÖP", "ÇİT", "DAM", "DİN", "DON", "DUA", "DÜN",
  "DÜŞ", "FAL", "FEN", "GAZ", "HAL", "HAN", "HAT", "HEP", "HİÇ", "HÜR", "İLK", "JET",
  "KAS", "KAT", "KIR", "KÖR", "KÜP", "LAF", "MAL", "NET", "NOT", "NUR", "OTO", "PAY",
  "PEK", "SAĞ", "SAZ", "SEL", "SET", "SIR", "SOL", "SÖZ", "SUÇ", "ŞAL", "ŞEF", "ŞEN",
  "ŞİŞ", "ŞOK", "TAT", "TEK", "TEL", "TEN", "TER", "TEZ", "TOK", "TÜR", "ÜYE", "YAS",
  "YEM", "YER", "YEL", "YÜK", "ZAR", "ZAM", "ARKA", "ORTA", "BOŞ", "EVET", "HAYIR",
  "ÇÜNKÜ", "AMA", "SIRA", "YAZI", "OKUMA", "HESAP", "MATEMATİK", "TÜRKÇE",
  "COĞRAFYA", "BEDEN", "BOYAMA", "ÇİZİM", "CETVEL", "PERGEL", "KALEMTRAŞ",
  "TEBEŞİR", "PROJEKTÖR", "LABORATUVAR", "DENEY", "TÜP", "MIKNATIS", "BÜYÜTEÇ", "KÜRE",
  "ATLAS", "ANNEANNE", "BABANNE", "DÜNÜR", "GELİN", "DAMAT", "ENİŞTE", "YENGE", "BACANAK",
  "GÖRÜMCE", "KAYINVALİDE", "KAYINPEDER", "ÇOCUKLUK", "GENÇLİK", "YAŞLILIK", "DOĞUM",
  "NİŞAN", "SÜNNET", "MEZAR", "CENAZE", "MİSAFİR", "KOMŞU", "SEVGİLİ",
  "KARI", "KOCA", "SOYADI", "İSİM", "LAKAP", "LÜTFEN", "TEŞEKKÜR", "RİCA", "ÖZÜR",
  "MERHABA", "SELAM", "HOŞÇAKAL", "AFİYET", "BAŞARI", "PASTANE", "AKTAR",
  "KIRTASİYE", "OYUNCAKÇI", "ÇİÇEKÇİ", "KUYUMCU", "TERZİ", "BERBER", "KUAFÖR", "ECZACI",
  "TAMİRCİ", "TESİSATÇI", "ELEKTRİKÇİ", "BOYACI", "MARANGOZ", "DEMİRCİ",
  "FIRINCI", "SÜTÇÜ", "BALIKÇI", "BAHÇIVAN", "ASKER", "PİLOT", "GARSON", "HOSTES",
  "MİMAR", "SAVCI", "İTFAİYECİ", "POSTACI", "TAKSİCİ", "KAMYONCU", "ESNAF", "SATICI",
  "MEMUR", "İŞÇİ", "PATRON", "MÜŞTERİ", "GAZETECİ", "SUNUCU", "YÖNETMEN", "ŞARKICI",
  "DANSÇI", "ŞAİR", "ASTRONOT", "ANTRENÖR", "KALECİ", "FORVET", "TEKNİK", "TARAFTAR",
  "FİLE", "POTA", "RAKET", "BADMİNTON", "ATLAMA", "BOKS", "JUDO", "KARATE", "PATEN",
  "BİNİCİLİK", "YELKEN", "KÜREK", "OKÇULUK", "CİMNASTİK", "PİLATES", "HALTER",
  "KORNER", "FAUL", "OFSAYT", "SÜRE", "DEVRE", "UZATMA", "SERİ", "GRUP", "FİNAL",
  "MARATON", "OLİMPİYAT", "MİLLİ", "BİTKİ", "KARA", "VADİ", "DERE", "KAYA", "SAHİL",
  "YOSUN", "ZİRVE", "YAMAÇ", "TABİAT", "VOLKAN", "MEVSİM", "MAĞARA", "KUMSAL", "MERCAN",
  "YILDIRIM", "ŞELALE", "KENT", "KULE", "YAYA", "YOLCU", "SEFER", "DÜKKAN", "TRAFİK",
  "MAHALLE", "TRAMVAY", "GÖKDELEN", "OTOPARK", "AKIL", "ZEKİ", "ÇÖZÜM", "DENGE",
  "GİZEM", "BEYİN", "MERAK", "BİLİM", "KAVRAM", "HAFIZA", "EĞİTİM", "MANTIK", "FORMÜL",
  "DİKKAT", "ANALİZ", "BİLİNÇ", "DÜŞÜNCE", "ÖĞRENME", "FELSEFE", "EDEBİYAT", "FÜZE", "UYDU", "EVREN", "GEZEGEN", "SİSTEM", "GALAKSİ", "ATMOSFER", "TELESKOP",
  "TARİF", "TUZLU", "BÖREK", "IZGARA", "MEZE", "HELVA", "MANTI", "KAVURMA", "İÇECEK",
  "BAKLAVA", "MENEMEN", "ENGİNAR", "DOLMA", "SARMA", "KIZARTMA", "PUSULA", "SANAYİ",
  "BULVAR", "ÖLÇÜ", "İZİN", "RİSK", "TEORİ", "PARÇA", "ORTANCA", "İMECE", "GONCA",
  "KARINCA", "GÜVENCE", "EĞLENCE", "BİLMECE", "ÇEKMECE", "AÇIK", "KAPALI", "TEMİZ",
  "KİRLİ", "ZENGİN", "FAKİR", "GENÇ", "YAŞLI", "GÜÇLÜ", "ZAYIF", "KALIN", "İNCE",
  "YAKIN", "UZAK", "ERKEN", "GEÇ", "FAZLA", "EKSİK", "YARIM", "ÇİFT", "SAĞLAM",
  "YORGUN", "DİNGİN", "SABIRLI", "ACELECİ", "CESUR", "KORKAK", "CÖMERT", "CİMRİ",
  "KİBİRLİ", "DÜRÜST", "YALANCI", "ÇALIŞKAN", "TEMBEL", "AKILLI", "ŞANSLI", "ŞANSSIZ",
  "ACI", "EKŞİ", "TATSIZ", "LEZZETLİ", "KOKULU", "PARLAK", "KAYGAN", "DÜZ",
  "EĞRİ", "YUVARLAK", "SİVRİ", "KÖŞELİ", "DERİN", "SIĞ", "AĞIR", "HAFİF", "UCUZ", "BEDAVA", "MÜMKÜN", "İMKANSIZ", "GEREKLİ", "GEREKSİZ", "SADE",
  "KARMAŞIK", "BELİRGİN", "GİZLİ", "YASAL", "YASAK", "SERBEST", "MEŞGUL", "HAZIR",
  "TAMAM", "DEVAM", "BOĞAZ", "OMUZ", "DİRSEK", "DİZ", "TOPUK", "TIRNAK", "KAŞ",
  "KİRPİK", "ALIN", "ÇENE", "BOYUN", "SIRT", "BEL", "GÖĞÜS", "KARIN", "MİDE",
  "AKCİĞER", "BÖBREK", "KARACİĞER", "DAMAR", "KEMİK", "DERİ", "NEFES", "SEVİYE",
  "HAPŞIRIK", "GRİP", "NEZLE", "HAP", "ŞURUP", "AŞI", "PANSUMAN", "ALÇI", "AMELİYAT",
  "KONTROL", "MUAYENE", "REÇETE", "KLİNİK", "AMBULANS", "SERUM", "TANSİYON", "NABIZ",
  "KAZAK", "HIRKA", "YELEK", "EŞARP", "KEMER", "KRAVAT", "PİJAMA", "ŞORT", "TERLİK",
  "SANDALET", "ELBİSE", "KABAN", "PALTO", "YAĞMURLUK", "YÜZÜK", "KOLYE", "KÜPE",
  "BİLEZİK", "BROŞ", "DEVE", "EŞEK", "SIĞIR", "DOMUZ", "HİNDİ", "LEYLEK", "BAYKUŞ",
  "KARGA", "MARTI", "PELİKAN", "AHTAPOT", "KARİDES", "İSTAKOZ", "MİDYE",
  "BALİNA", "KERTENKELE", "BUKALEMUN", "SALYANGOZ", "SİNEK", "SİVRİSİNEK", "BÖCEK",
  "ÖRÜMCEK", "AKREP", "YARASA", "KÖSTEBEK", "KIRPI", "ÇAKAL", "LEOPAR", "GERGEDAN",
  "ZÜRAFA", "KOALA", "KANGURU", "PANDA", "GÜVE", "ÇEKİRGE", "SOLUCAN", "LAHMACUN",
  "PİDE", "KUMPİR", "DÖNER", "DÜRÜM", "CİĞER", "KOKOREÇ", "İSKENDER", "TURŞU", "PEKMEZ", "TAHİN", "BOZA", "SALEP", "KÜNEFE", "KADAYIF", "SÜTLAÇ", "AŞURE",
  "LOKUM", "PİŞMANİYE", "LOKMA", "GOFRET", "CİPS", "KRAKER", "BONBON",
  "SAKIZ", "KREP", "PANKEK", "KURABİYE", "KEK", "TART", "PROFİTEROL", "TİRAMİSU",
  "FINDIK", "CEVİZ", "BADEM", "LEBLEBİ", "HURMA", "LİMON", "KİVİ", "ANANAS", "MANGO",
  "AVOKADO", "AHUDUDU", "BÖĞÜRTLEN", "VİŞNE", "ERİK", "AYVA", "PATLICAN", "KABAK",
  "PIRASA", "MARUL", "ROKA", "MAYDANOZ", "NANE", "FESLEĞEN", "KEKİK", "KİMYON",
  "KARABİBER", "PULBİBER", "TARÇIN", "ZENCEFİL", "ZERDEÇAL", "KARBONAT", "MAYA",
  "KEFİR", "KAYMAK", "SİRKE", "KETÇAP", "MAYONEZ", "HARDAL", "EZME", "HUMUS",
  "GÖZLEME", "KATMER", "LAZANYA", "SPAGETTİ", "ERİŞTE", "ŞEHRİYE",
  "EZOGELİN", "YAYLA", "TARHANA", "İŞKEMBE", "YİRMİ", "OTUZ", "KIRK", "ELLİ",
  "ALTMIŞ", "YETMİŞ", "SEKSEN", "DOKSAN", "MİLYON", "MİLYAR", "SIFIR", "ÇEYREK",
  "ÖNCE", "SONRA", "ŞİMDİ", "BUGÜN", "YARIN", "ASIR", "ÇAĞ", "SANİYE", "DAKİKA",
  "İKİNDİ", "ŞAFAK", "VAKİT", "ZAMAN", "BANT", "ZIMBA", "DOSYA", "KLASÖR",
  "KARTON", "MUKAVVA", "AJANDA", "TAKVİM", "DÜRBÜN", "YAZICI", "TARAYICI", "HOPARLÖR",
  "MİKROFON", "KABLO", "DÜĞME", "MODEM", "VİDEO", "ARAMA", "GÖRÜŞME",
  "YAYIN", "KANAL", "DİZİ", "BELGESEL", "HABER", "OPERA", "BALET", "KONSER",
  "FESTİVAL", "SERGİ", "GALERİ", "GİŞE", "MİNİBÜS", "METROBÜS", "VAPUR", "FERİBOT",
  "YAT", "SANDAL", "DOLMUŞ", "KAMYONET", "MOTOSİKLET", "KAYKAY", "PUSET", "İSKELE",
  "TERMİNAL", "KALDIRIM", "GEÇİT", "BENZİNLİK", "BENZİN", "MAZOT", "ELEKTRİK",
  "LASTİK", "DİREKSİYON", "FREN", "VİTES", "KLİMA", "SİNYAL", "KORNA", "BAGAJ",
  "KAPUT", "PLAKA", "RUHSAT", "EHLİYET", "CEZA", "KAZA", "TAMİR", "SERVİS",
  "KURUŞ", "BANKNOT", "KREDİ", "BORÇ", "FAİZ", "MAAŞ", "ÜCRET", "PEŞİN", "TAKSİT",
  "FATURA", "MAKBUZ", "VERGİ", "BÜTÇE", "BİRİKİM", "YATIRIM", "KAZANÇ", "ZARAR",
  "TASARRUF", "HARCAMA", "REYON", "SEPET", "KUYRUK", "ÖDEME", "NAKİT", "APARTMAN",
  "VİLLA", "KÖŞK", "GECEKONDU", "KARAVAN", "YURT", "MOTEL", "PANSİYON", "TUVALET",
  "ANTRE", "KORİDOR", "TERAS", "KİLER", "ÇAMAŞIRHANE", "DÖŞEME", "PARKE", "FAYANS",
  "MOBİLYA", "KANEPE", "SEHPA", "GARDİROP", "BÜFE", "ÇARŞAF", "BATTANİYE", "AVİZE",
  "ABİDE", "PRİZ", "KALORİFER", "SOBA", "KOMBİ", "ŞOFBEN", "ASPİRATÖR", "ÜTÜ",
  "SÜPÜRGE", "MİKSER", "ÇAYDANLIK", "CEZVE", "GÜVEÇ", "KEVGİR", "KEPÇE",
  "KASE", "FİNCAN", "SÜRAHİ", "SÜZGEÇ", "TEPSİ", "SALAM", "PASTIRMA", "KARNIYARIK",
  "TANDIR", "İÇLİKÖFTE", "SUBÖREĞİ", "KOLBÖREĞİ", "ADALET", "HUKUK",
  "MAHKEME", "KARAKOL", "HAPİSHANE", "CEZAEVİ", "KAYMAKAMLIK", "MUHTAR",
  "BAŞKAN", "MİLLETVEKİLİ", "SEÇİM", "SANDIK", "DEMOKRASİ", "İSTİKLAL", "ANAYASA",
  "HAK", "ÖZGÜRLÜK", "EŞİTLİK", "KARDEŞLİK", "SAYGI", "HOŞGÖRÜ", "SABIR", "CESARET",
  "İNANÇ", "GÜVEN", "SADAKAT", "DÜRÜSTLÜK", "ÇALIŞMA", "EMEKLİLİK", "MESLEK",
  "KARIYER", "ORTAOKUL", "KREŞ", "KAMPÜS", "BÖLÜM", "PROJE", "SUNUM", "KARNE",
  "DİPLOMA", "MEZUNİYET", "TÖREN", "GEZİ", "TUR", "REHBER", "REZERVASYON", "SODA",
  "ŞALGAM", "KOLA", "GAZOZ", "TÜRKKAHVESİ", "FİLTRE", "HAMLE", "İPUCU", "TEBRİKLER",
  "BERABERE", "YENİDEN", "AYARLAR", "DAVET", "ŞİFRE", "GİRİŞ", "KAYIT",
  "ÇIKIŞ", "SONUÇ", "ÖDÜL", "GÖREV", "GÜNLÜK", "HAFTALIK", "SIRALAMA", "PROFİL",
  "UĞURBÖCEĞİ", "KURUFASULYE", "ZEYTİNYAĞI", "AYÇİÇEĞİ", "KREDİKARTI",
  "SIRTÇANTASI", "YAĞMURLUK", "SİVRİSİNEK",
  "KERTENKELE", "SALYANGOZ", "KAYINVALİDE", "KAYINPEDER", "LABORATUVAR",
  "ELEKTRİKÇİ", "TESİSATÇI", "MOTOSİKLET", "DİREKSİYON", "ÇAMAŞIRHANE", "KARNIYARIK",
  "İMAMBAYILDI", "HÜNKARBEĞENDİ", "MİLLETVEKİLİ", "REZERVASYON", "OLİMPİYAT",
  "CİMNASTİK", "BADMİNTON", "GERGEDAN", "BUKALEMUN", "PROFİTEROL",
  "TİRAMİSU", "PİŞMANİYE", "KAYMAKAMLIK", "HAPİSHANE", "EMEKLİLİK", "MEZUNİYET",
  "DEMOKRASİ", "ÖZGÜRLÜK", "DÜRÜSTLÜK", "KARDEŞLİK", "BİNİCİLİK", "TELESKOP",
  "ATMOSFER", "EDEBİYAT", "FELSEFE", "MATEMATİK", "COĞRAFYA",
  "KIRTASİYE", "OYUNCAKÇI", "İTFAİYECİ", "GAZETECİ", "YÖNETMEN", "ANTRENÖR",
  "ŞAMPİYONLUK", "TARAFTAR", "PENALTI", "MARATON", "YILDIRIM", "GÖKDELEN",
  "MAHALLE", "TRAMVAY", "OTOPARK", "BULVAR", "KALDIRIM", "BENZİNLİK", "EHLİYET",
  "BANKNOT", "TASARRUF", "APARTMAN", "PANSİYON", "GARDİROP", "KALORİFER", "ASPİRATÖR",
  "ÇAYDANLIK", "KARNIYARIK", "İÇLİKÖFTE", "ANAYASA",
  "İSTİKLAL", "ORTAOKUL", "DİPLOMA", "BELGESEL", "FESTİVAL", "METROBÜS", "FERİBOT",
  "KAMYONET", "TERMİNAL", "AMBULANS", "MUAYENE", "AMELİYAT", "AKCİĞER", "KARACİĞER",
  "SANDALET", "YAĞMURLUK", "BİLEZİK", "PELİKAN", "AHTAPOT", "KARİDES", "İSTAKOZ",
  "BALİNA", "YARASA", "KÖSTEBEK", "KANGURU", "LAHMACUN", "KOKOREÇ", "İSKENDER",
  "KADAYIF", "KURABİYE", "AVOKADO", "AHUDUDU", "BÖĞÜRTLEN", "MAYDANOZ", "FESLEĞEN",
  "KARABİBER", "ZENCEFİL", "ZERDEÇAL", "MAYONEZ", "SPAGETTİ", "TARHANA",
  "İŞKEMBE", "KRONOMETRE", "HOPARLÖR", "MİKROFON", "KÜTÜPHANE",
  "HELİKOPTER", "MOTOSİKLET", "DİREKSİYON", "ÇAMAŞIRHANE", "BATTANİYE",
  "PASTIRMA", "CEZAEVİ", "SADAKAT", "KARIYER", "REZERVASYON", "TÜRKKAHVESİ",
  "BERABERE", "SIRALAMA", "TEBRİKLER", "BAŞARI", "TEŞEKKÜR",
  "MERHABA", "HOŞÇAKAL", "LÜTFEN", "ÇÜNKÜ", "HAZIRAN", "AĞUSTOS",
  "TEMMUZ", "EYLÜL", "KASIM", "ARALIK", "ŞUBAT", "MAYIS", "MART", "EKİM",
  "MİLYON", "MİLYAR", "SANİYE", "DAKİKA", "İKİNDİ", "BUGÜN", "YARIN", "ŞİMDİ",
  "ÖNCE", "SONRA", "ÇEYREK", "SIFIR", "YİRMİ", "OTUZ", "KIRK", "ELLİ", "ALTMIŞ",
  "YETMİŞ", "SEKSEN", "DOKSAN", "CİMNASTİK", "OKÇULUK", "YELKEN",
  "KÜREK", "HALTER", "KORNER", "OFSAYT", "UZATMA", "DEVRE", "MİLLİ", "TABİAT",
  "VOLKAN", "MEVSİM", "MAĞARA", "KUMSAL", "MERCAN", "ŞELALE", "YAMAÇ", "ZİRVE",
  "YOSUN", "SAHİL", "VADİ", "DERE", "BİTKİ", "GÖKDELEN", "MAHALLE", "OTOPARK",
  "TRAMVAY", "YOLCU", "SEFER", "DÜKKAN", "KULE", "KENT", "HAFIZA", "KAVRAM",
  "FORMÜL", "ANALİZ", "BİLİNÇ", "ÖĞRENME", "GEZEGEN", "GALAKSİ", "UYDU", "FÜZE",
  "EVREN", "ENGİNAR", "MENEMEN", "BAKLAVA", "IZGARA", "KAVURMA", "HELVA",
  "ORTANCA", "GONCA", "İMECE", "PARÇA", "ÇEKMECE", "BİLMECE", "EĞLENCE", "GÜVENCE",
  "ACELECİ", "SABIRLI", "DİNGİN", "YORGUN", "SAĞLAM", "KÖŞELİ", "YUVARLAK",
  "KAYGAN", "LEZZETLİ", "TATSIZ", "ŞANSSIZ", "ÇALIŞKAN", "YALANCI",
  "DÜRÜST", "KİBİRLİ", "CİMRİ", "CÖMERT", "KORKAK", "CESUR", "TEMBEL", "AKILLI",
  "GEREKLİ", "GEREKSİZ", "İMKANSIZ", "MÜMKÜN", "BEDAVA", "BELİRGİN",
  "KARMAŞIK", "SERBEST", "MEŞGUL", "HAPŞIRIK", "PANSUMAN", "MUAYENE", "REÇETE",
  "KLİNİK", "SERUM", "TANSİYON", "NABIZ", "HIRKA", "EŞARP", "KRAVAT", "PİJAMA",
  "TERLİK", "KABAN", "PALTO", "YÜZÜK", "KOLYE", "BROŞ", "LEYLEK", "BAYKUŞ",
  "KARGA", "MARTI", "MİDYE", "ÇAKAL", "LEOPAR", "KOALA", "PANDA", "GÜVE",
  "ÇEKİRGE", "SOLUCAN", "PİDE", "KUMPİR", "DÜRÜM", "CİĞER", "TURŞU",
  "PEKMEZ", "TAHİN", "BOZA", "SALEP", "KÜNEFE", "SÜTLAÇ", "AŞURE", "LOKUM",
  "LOKMA", "GOFRET", "CİPS", "KRAKER", "BONBON", "SAKIZ", "KREP",
  "PANKEK", "KEK", "TART", "FINDIK", "CEVİZ", "BADEM", "LEBLEBİ", "HURMA",
  "ANANAS", "MANGO", "KİVİ", "VİŞNE", "ERİK", "AYVA", "PATLICAN", "KABAK",
  "PIRASA", "MARUL", "ROKA", "NANE", "KEKİK", "KİMYON", "TARÇIN", "KARBONAT",
  "MAYA", "KEFİR", "KAYMAK", "SİRKE", "KETÇAP", "HARDAL", "EZME", "HUMUS",
  "GÖZLEME", "KATMER", "LAZANYA", "ERİŞTE", "ŞEHRİYE", "EZOGELİN", "YAYLA",
  "MUKAVVA", "AJANDA", "TAKVİM", "DÜRBÜN", "YAZICI", "TARAYICI", "MODEM",
  "VİDEO", "ARAMA", "YAYIN", "KANAL", "DİZİ", "OPERA", "BALET", "KONSER",
  "SERGİ", "GALERİ", "GİŞE", "MİNİBÜS", "VAPUR", "YAT", "SANDAL", "DOLMUŞ",
  "KAYKAY", "PUSET", "İSKELE", "GEÇİT", "BENZİN", "MAZOT", "FREN", "VİTES",
  "SİNYAL", "KORNA", "BAGAJ", "KAPUT", "PLAKA", "RUHSAT", "KAZA",
  "TAMİR", "SERVİS", "KURUŞ", "KREDİ", "BORÇ", "FAİZ", "MAAŞ", "ÜCRET",
  "PEŞİN", "TAKSİT", "FATURA", "MAKBUZ", "VERGİ", "BÜTÇE", "BİRİKİM",
  "YATIRIM", "KAZANÇ", "ZARAR", "HARCAMA", "REYON", "SEPET", "KUYRUK",
  "ÖDEME", "NAKİT", "VİLLA", "KÖŞK", "KARAVAN", "MOTEL", "TUVALET", "ANTRE",
  "KORİDOR", "TERAS", "KİLER", "DÖŞEME", "PARKE", "FAYANS", "MOBİLYA",
  "KANEPE", "SEHPA", "ÇARŞAF", "AVİZE", "PRİZ", "SOBA", "KOMBİ", "ŞOFBEN",
  "ÜTÜ", "SÜPÜRGE", "MİKSER", "CEZVE", "GÜVEÇ", "KEVGİR", "KEPÇE",
  "KASE", "FİNCAN", "SÜRAHİ", "SÜZGEÇ", "TEPSİ", "SALAM", "TANDIR", "HUKUK",
  "MAHKEME", "KARAKOL", "MUHTAR", "BAŞKAN", "SEÇİM", "SANDIK", "HAK",
  "EŞİTLİK", "SAYGI", "HOŞGÖRÜ", "SABIR", "CESARET", "İNANÇ", "GÜVEN",
  "ÇALIŞMA", "MESLEK", "KREŞ", "KAMPÜS", "PROJE", "KARNE", "TÖREN", "GEZİ",
  "REHBER", "SODA", "ŞALGAM", "KOLA", "GAZOZ", "HAMLE", "İPUCU", "YENİDEN",
  "AYARLAR", "DAVET", "ŞİFRE", "GİRİŞ", "KAYIT", "ÇIKIŞ",
  "SONUÇ", "ÖDÜL", "GÖREV", "GÜNLÜK", "PROFİL", "MÜDÜR",
  "KİTAPLIK", "KALEMLİK", "HESAP", "SIRA", "YAZI", "OKUMA", "BEDEN",
  "BOYAMA", "ÇİZİM", "CETVEL", "PERGEL", "TEBEŞİR", "DENEY", "TÜP",
  "MIKNATIS", "BÜYÜTEÇ", "KÜRE", "ATLAS", "GELİN", "DAMAT", "ENİŞTE",
  "YENGE", "DOĞUM", "NİŞAN", "MEZAR", "CENAZE", "MİSAFİR", "KOMŞU",
  "SEVGİLİ", "KARI", "KOCA", "İSİM", "LAKAP", "RİCA", "ÖZÜR", "SELAM",
  "AFİYET", "PASTANE", "AKTAR", "TERZİ", "BERBER", "KUAFÖR", "ECZACI",
  "TAMİRCİ", "BOYACI", "MARANGOZ", "DEMİRCİ", "FIRINCI", "ASKER",
  "PİLOT", "GARSON", "HOSTES", "MİMAR", "POSTACI", "ESNAF", "SATICI",
  "MEMUR", "İŞÇİ", "PATRON", "MÜŞTERİ", "SUNUCU", "ŞARKICI", "DANSÇI",
  "ŞAİR", "KALECİ", "FORVET", "TEKNİK", "FİLE", "POTA", "RAKET", "ATLAMA",
  "BOKS", "JUDO", "KARATE", "PATEN", "PİLATES", "FAUL", "SÜRE",
  "SERİ", "GRUP", "FİNAL", "MİLLİ", "KARA", "KAYA", "YAYA", "AKIL",
  "ZEKİ", "ÇÖZÜM", "DENGE", "GİZEM", "BEYİN", "MERAK", "BİLİM", "DİKKAT",
  "TARİF", "TUZLU", "BÖREK", "MEZE", "MANTI", "DOLMA", "SARMA", "PUSULA",
  "SANAYİ", "ÖLÇÜ", "İZİN", "RİSK", "TEORİ", "AÇIK", "KAPALI", "TEMİZ",
  "KİRLİ", "ZENGİN", "FAKİR", "GENÇ", "YAŞLI", "GÜÇLÜ", "ZAYIF", "KALIN",
  "İNCE", "YAKIN", "UZAK", "ERKEN", "GEÇ", "FAZLA", "EKSİK", "YARIM",
  "ÇİFT", "ACI", "EKŞİ", "PARLAK", "DÜZ", "EĞRİ", "SİVRİ", "DERİN",
  "SIĞ", "AĞIR", "HAFİF", "UCUZ", "SADE", "GİZLİ", "YASAL", "YASAK",
  "TAMAM", "DEVAM", "BOĞAZ", "OMUZ", "DİRSEK", "DİZ", "TOPUK", "TIRNAK",
  "KAŞ", "KİRPİK", "ALIN", "ÇENE", "BOYUN", "SIRT", "BEL", "GÖĞÜS",
  "KARIN", "MİDE", "DAMAR", "KEMİK", "DERİ", "NEFES", "SEVİYE", "GRİP",
  "NEZLE", "ŞURUP", "AŞI", "ALÇI", "KONTROL", "NABIZ", "KAZAK", "YELEK",
  "KEMER", "ŞORT", "DEVE", "EŞEK", "SIĞIR", "DOMUZ", "HİNDİ", "DÖNER",
  "LİMON", "SOS", "AÇMA", "TUR", "BANT", "DOSYA", "KLASÖR",
  "HABER", "LASTİK", "KLİMA", "CEZA", "HIZ",
  "MÜHİM", "MÜBAREK", "MÜKEMMEL", "MÜKAFAT", "MÜFETTİŞ", "MÜTERCİM", "MÜTEVAZİ", "MÜSAMAHA", "MÜZAKERE", "MÜNASİP",
  "MÜSLÜMAN", "MUHABİR", "MUHASEBE", "MUHTEŞEM", "MUCİZE", "MUHTAÇ", "MUHAFAZA", "İSTİSNA", "İSTİKRAR", "İSTİRAHAT",
  "İNTİHAR", "İNTİKAM", "İFTİRA", "TEKRAR", "TEMİZLİK", "TESİSAT", "TEFTİŞ", "TEBRİK", "TESLİM", "TEZGAH", "TAKİP", "TAŞIT",
  "SÜLÜK", "KUDUZ", "OTAĞ"
] as const;

function getBoardsForLength(len: number): number[] {
  if (len <= 6) return [4, 6, 8, 10];
  if (len <= 8) return [6, 8, 10];
  if (len <= 10) return [8, 10];
  return [10];
}

const THEME_ENTRIES: WordEntry[] = (Object.entries(THEME_WORDS) as [Exclude<WordTheme, "general">, readonly string[]][]).flatMap(
  ([theme, words]) =>
    words.filter(isValidCatalogWord).map((word) => ({
      word,
      difficulty: difficultyForLength(word.length),
      boards: getBoardsForLength(word.length),
      tags: [theme],
      weight: 4,
    })),
);

const EVERYDAY_SET = new Set(
  [...EXTRA_EVERYDAY_WORDS, ...EXTRA_EVERYDAY_MORE, ...NATURAL_INFINITIVES].filter(isValidCatalogWord),
);

const rawFilteredWords = (catalog as CatalogPayload).words
  .filter((entry) => {
    const word = entry.word;
    if (word.length < 3 || WORD_BLACKLIST.has(word)) return false;
    if (STEM_WHITELIST.has(word)) return true;
    if (ARTIFICIAL_SUFFIX_REGEX.test(word)) return false;
    return true;
  })
  .map((entry) => ({
    ...entry,
    boards: getBoardsForLength(entry.word.length),
  }));

const wordMap = new Map<string, WordEntry>();
for (const entry of rawFilteredWords) {
  wordMap.set(entry.word, entry);
}
for (const entry of THEME_ENTRIES) {
  const existing = wordMap.get(entry.word);
  if (existing) {
    wordMap.set(entry.word, {
      ...existing,
      boards: Array.from(new Set([...existing.boards, ...entry.boards])),
      tags: Array.from(new Set([...existing.tags, ...entry.tags])),
    });
  } else {
    wordMap.set(entry.word, entry);
  }
}

for (const verb of NATURAL_INFINITIVES) {
  if (!wordMap.has(verb)) {
    wordMap.set(verb, {
      word: verb,
      difficulty: difficultyForLength(verb.length),
      boards: getBoardsForLength(verb.length),
      tags: ["general"],
      weight: 3,
    });
  }
}

for (const word of EVERYDAY_SET) {
  const existing = wordMap.get(word);
  if (existing) {
    wordMap.set(word, {
      ...existing,
      difficulty: difficultyForLength(word.length),
      weight: Math.max(existing.weight, 12),
    });
  } else {
    wordMap.set(word, {
      word,
      difficulty: difficultyForLength(word.length),
      boards: getBoardsForLength(word.length),
      tags: ["general"],
      weight: 12,
    });
  }
}

export const WORD_CATALOG_DATA = {
  version: (catalog as CatalogPayload).version,
  words: Array.from(wordMap.values()),
};

export const WORD_CATALOG = {
  4: WORD_CATALOG_DATA.words.filter((entry) => entry.boards.includes(4)),
  6: WORD_CATALOG_DATA.words.filter((entry) => entry.boards.includes(6)),
  8: WORD_CATALOG_DATA.words.filter((entry) => entry.boards.includes(8)),
  10: WORD_CATALOG_DATA.words.filter((entry) => entry.boards.includes(10)),
} as const;

export const WORD_BANK = {
  4: WORD_CATALOG[4].map((entry) => entry.word),
  6: WORD_CATALOG[6].map((entry) => entry.word),
  8: WORD_CATALOG[8].map((entry) => entry.word),
  10: WORD_CATALOG[10].map((entry) => entry.word),
} as const;

export function catalogWordsForBoard(size: 4 | 6 | 8 | 10, maximumLength: number = Math.max(size, 12)) {
  const specific = WORD_CATALOG[size].filter((entry) => entry.word.length <= maximumLength);
  const familiar = specific.filter((entry) => EVERYDAY_SET.has(entry.word));
  if (familiar.length >= 30) return familiar;
  if (specific.length >= 30) return specific;
  return WORD_CATALOG_DATA.words.filter((entry) => entry.word.length <= maximumLength);
}

export function catalogWordsForTheme(size: 4 | 6 | 8 | 10, theme: WordTheme, maximumLength: number = Math.max(size, 12)) {
  const boardWords = catalogWordsForBoard(size, maximumLength);
  if (theme === "general") return boardWords;
  const themedWords = new Set(THEME_WORDS[theme]);
  const familiarThemed = boardWords.filter((entry) => themedWords.has(entry.word) || entry.tags.includes(theme));
  if (familiarThemed.length >= 3) return familiarThemed;
  const catalogThemed = WORD_CATALOG[size].filter(
    (entry) => entry.word.length <= maximumLength && (themedWords.has(entry.word) || entry.tags.includes(theme)),
  );
  return catalogThemed.length >= 3 ? catalogThemed : boardWords;
}
