import { StyleSheet } from "react-native";
import { palette } from "@/shared/palette";

export const styles = StyleSheet.create({

  content: { flexGrow: 1, paddingBottom: 170 },
  hud: {
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    marginBottom: 8,
    overflow: "hidden",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  hudInner: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  identity: { flexDirection: "row", gap: 8, alignItems: "center", flex: 1, minWidth: 0 },
  identityMeta: { flex: 1, minWidth: 0 },
  avatarWrap: { position: "relative" },
  avatarFlameBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF7ED",
    borderRadius: 8,
    paddingHorizontal: 5,
    paddingVertical: 2,
    zIndex: 10,
  },
  avatarFlameEmoji: { fontSize: 10, marginRight: 2 },
  avatarFlameCount: { color: "#C2410C", fontSize: 11, fontWeight: "700" },
  avatarFlameShield: { fontSize: 10, marginLeft: 2 },
  flameStreakPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF7ED",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  flameStreakPillText: { color: "#C2410C", fontSize: 11, fontWeight: "700" },
  avatar: { width: 42, height: 42, borderRadius: 21, justifyContent: "center", alignItems: "center", overflow: "hidden", backgroundColor: "#F8FAFC" },
  avatarImage: { width: "100%", height: "100%", borderRadius: 21 },
  avatarText: { color: palette.text, fontWeight: "700", fontSize: 16 },
  name: { color: palette.text, fontSize: 15, fontWeight: "700", letterSpacing: 0.1 },
  rankRow: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 3 },
  titlePill: {
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    flexShrink: 1,
  },
  cyberBadge: { color: "#475569", fontSize: 11, fontWeight: "600" },
  rank: { flexShrink: 1, color: palette.mutedGold, fontSize: 11, fontWeight: "600" },

  topActionsGroup: { flexDirection: "row", gap: 6, alignItems: "center", flexShrink: 0 },
  topIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
  },
  topIconText: { fontSize: 15 },
  topIconBtnGlow: {
    backgroundColor: "#FEF3C7",
  },
  topNotificationDot: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#EF4444",
  },

  quickActionsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
    marginBottom: 4,
    width: "100%",
  },
  quickActionCard: {
    flex: 1,
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    gap: 8,
  },
  quickActionIcon: { fontSize: 18 },
  quickActionContent: { flex: 1, minWidth: 0 },
  quickActionTitle: { fontSize: 12, fontWeight: "700" },
  quickActionSub: { fontSize: 11, fontWeight: "500", color: "#64748B", marginTop: 1 },
  quickActionArrow: { fontSize: 12, fontWeight: "700", color: "#94A3B8" },

  dailyMiniPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFBEB",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
    marginBottom: 4,
    gap: 8,
  },
  dailyMiniIcon: { fontSize: 16 },
  dailyMiniText: { flex: 1, color: "#92400E", fontSize: 12, fontWeight: "600" },
  dailyMiniAction: { color: "#D97706", fontSize: 12, fontWeight: "700" },
  luckyWheelBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFF6FF",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
    marginBottom: 4,
    gap: 8,
  },
  luckyWheelIcon: { fontSize: 16 },
  luckyWheelText: { flex: 1, color: "#1E40AF", fontSize: 12, fontWeight: "600" },
  luckyWheelAction: { color: "#2563EB", fontSize: 12, fontWeight: "700" },
  missionsMiniPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ECFDF5",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
    marginBottom: 4,
    gap: 8,
  },
  missionsMiniIcon: { fontSize: 16 },
  missionsMiniText: { flex: 1, color: "#065F46", fontSize: 12, fontWeight: "600" },
  missionsMiniAction: { color: "#059669", fontSize: 12, fontWeight: "700" },
  livesHeaderPill: {
    height: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFF1F2",
    paddingHorizontal: 10,
    borderRadius: 10,
  },
  livesHeaderIcon: { width: 16, height: 16 },
  livesHeaderValue: { color: "#E11D48", fontSize: 12, fontWeight: "700" },
  livesHeaderPillInfinite: {
    backgroundColor: "#FEF3C7",
  },
  livesHeaderValueInfinite: {
    color: "#D97706",
    fontSize: 13,
    fontWeight: "700",
  },

  resourceRow: { flexDirection: "row", gap: 7, alignItems: "center", marginTop: 2 },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalIconBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 2,
    overflow: "hidden",
  },
  modalIconBadgeShield: { borderColor: palette.gemBlue },
  modalIconBadgeRadar: { borderColor: palette.emerald },
  modalIconBadgeLives: { borderColor: palette.heart },
  modalIconBadgeRotani: { borderColor: palette.gold },
  modalIconBadgeMystery: { borderColor: "#DCE1D7", backgroundColor: "rgba(56, 189, 248, 0.16)" },
  modalIconImg: { width: 64, height: 64 },
  modalKicker: {
    color: palette.gold,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  modalTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 4,
    marginBottom: 10,
  },
  modalCountPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F8F5EE",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: "#DCD5C6",
  },
  modalCountLabel: { color: palette.mutedGold, fontSize: 10, fontWeight: "800", letterSpacing: 0.5 },
  modalCountValue: { fontSize: 13, fontWeight: "900" },
  modalBody: {
    color: palette.text,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    marginBottom: 14,
  },
  modalTipBox: {
    width: "100%",
    backgroundColor: "#F4F7F2",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1.5,
    borderColor: "#D5DED0",
    marginBottom: 16,
  },
  modalTipTitle: {
    color: palette.gold,
    fontSize: 10,
    fontWeight: "900",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  modalTipText: {
    color: palette.muted,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: "600",
  },
  modalSecondaryBtn: { marginTop: 10, paddingVertical: 6, paddingHorizontal: 16 },
  modalSecondaryBtnText: { color: palette.muted, fontSize: 11, fontWeight: "800" },

  heroHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  radarRing: { position: "absolute", right: -18, top: -22, width: 120, height: 120, borderRadius: 60, borderWidth: 1.5, zIndex: 1 },
  orbit: { position: "absolute", right: -18, top: -22, width: 120, height: 120, borderRadius: 60, borderWidth: 1, borderColor: palette.bronze, justifyContent: "flex-start", alignItems: "center", zIndex: 2 },
  orbitNode: { width: 12, height: 12, borderRadius: 6, marginTop: -6, backgroundColor: palette.gold, shadowColor: palette.gold, shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
  deckEyebrow: { color: palette.gold, fontSize: 10, fontWeight: "900", letterSpacing: 0.5 },
  deckBody: { color: "#475D6D", fontSize: 14, lineHeight: 21, marginTop: 10, maxWidth: 300, fontWeight: "600" },
  xpPanel: {
    marginTop: 12,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderBottomWidth: 3,
    borderColor: "#BCD8F0",
    padding: 10,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  xpHead: { flexDirection: "row", justifyContent: "space-between" },
  xpLabel: { color: "#2C6B8D", fontSize: 10, fontWeight: "900", letterSpacing: 0.5 },
  xpValue: { color: "#16648B", fontSize: 10, fontWeight: "900" },
  track: { height: 8, marginTop: 6, borderRadius: 4, overflow: "hidden", backgroundColor: "#D8EBF9" },
  trackFill: { height: "100%", borderRadius: 4 },
  heroActions: { flexDirection: "column", gap: 8, marginTop: 14 },
  botPracticeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E2F0FD",
    borderWidth: 1.5,
    borderBottomWidth: 2.5,
    borderColor: "#B4D5F2",
    borderRadius: 14,
    paddingVertical: 9,
    paddingHorizontal: 12,
    marginTop: 8,
    gap: 8,
  },
  botPracticeIcon: { fontSize: 14 },
  botPracticeText: { color: "#1D6B94", fontSize: 11, fontWeight: "900", letterSpacing: 0.5 },
  botPracticeArrow: { color: "#18709E", fontSize: 11, fontWeight: "900" },
  signalFooter: { marginTop: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", width: "100%" },
  footerCol: { flex: 1, alignItems: "center" },
  signalLabel: { color: "#466E85", fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  signalValue: { color: palette.text, fontSize: 14, fontWeight: "900", marginTop: 2 },
  signalUnit: { color: palette.gold, fontSize: 9 },
  signalRule: { width: 1, height: 18, backgroundColor: palette.bronzeBorder },

  dailyRewardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  dailyRewardTitle: { color: palette.text, fontSize: 11, fontWeight: "900", letterSpacing: 0.5 },
  dailyRewardDayPill: { backgroundColor: "rgba(184, 134, 58, 0.28)", paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8, borderWidth: 1, borderColor: palette.bronzeBorder },
  dailyRewardDayPillText: { color: palette.gold, fontSize: 9.5, fontWeight: "900" },
  dailyStatusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10, borderWidth: 1 },
  dailyStatusBadgeReady: { backgroundColor: "#FFF9E6", borderColor: "#F0C855" },
  dailyStatusBadgeClaimed: { backgroundColor: "rgba(62, 232, 181, 0.12)", borderColor: "#DCE1D7" },
  dailyStatusBadgeText: { fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  dailyDaysRow: { flexDirection: "row", gap: 5, marginTop: 10, width: "100%" },
  dailyDayCard: {
    flex: 1,
    minHeight: 68,
    borderRadius: 14,
    backgroundColor: "#FFF0E8",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 5,
    position: "relative",
  },
  dailyDayCardActive: {
    borderColor: "#DCE1D7",
    backgroundColor: "#FFF0E8",
    borderWidth: 2,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  dailyDayCardPast: { opacity: 0.7, borderColor: "#DCE1D7", backgroundColor: "#FFF0E8" },
  dailyDayCardClaimedToday: { borderColor: "#DCE1D7", backgroundColor: "#FFF0E8" },
  dailyDayCardEpic: { borderColor: "#DCE1D7" },
  epicTag: { position: "absolute", top: -6, backgroundColor: "#ffee94", paddingHorizontal: 4, borderRadius: 5 },
  epicTagText: { color: "#293541", fontSize: 9, fontWeight: "900" },
  dailyDayLabel: { color: "#81765a", fontSize: 9.5, fontWeight: "800" },
  dailyDayIcon: { fontSize: 14, marginVertical: 2 },
  dailyDayAmount: { color: palette.text, fontSize: 9.5, fontWeight: "900" },
  dailyDayCheck: { position: "absolute", bottom: 2, right: 3, backgroundColor: "#ffe5b3", width: 12, height: 12, borderRadius: 6, alignItems: "center", justifyContent: "center" },
  dailyDayCheckText: { color: "#293541", fontSize: 9, fontWeight: "900", lineHeight: 10 },
  dailyClaimedBar: { marginTop: 10, backgroundColor: "rgba(255, 194, 74, 0.08)", borderWidth: 1, borderColor: "#DCE1D7", borderRadius: 10, paddingVertical: 7, paddingHorizontal: 10, alignItems: "center" },
  dailyClaimedBarText: { color: "#987c00", fontSize: 9.5, fontWeight: "800", letterSpacing: 0.3 },

  cardsRow: { flexDirection: "row", gap: 10, width: "100%", marginTop: 4 },
  columnCardWrap: { flex: 1 },
  columnCard: {
    flex: 1,
    minHeight: 160,
    borderRadius: 18,
    borderWidth: 1.5,
    borderBottomWidth: 3.5,
    padding: 10,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    position: "relative",
    overflow: "hidden",
  },
  cardRibbonWrap: { width: "100%", alignItems: "center" },
  cardRibbonMint: {
    alignSelf: "center",
    backgroundColor: "#C5F3DB",
    borderWidth: 1,
    borderColor: "#78D9A7",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 7,
  },
  cardRibbonAmber: {
    alignSelf: "center",
    backgroundColor: "#FFE1C4",
    borderWidth: 1,
    borderColor: "#F4AF79",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 7,
  },
  cardRibbonText: {
    color: "#0F6144",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  cardRibbonTextAmber: {
    color: "#9A4B0A",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  cardIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cardIconText: { fontSize: 16, fontWeight: "900" },
  cardKicker: {
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginTop: 12,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 3,
    letterSpacing: 0.5,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  cardBody: { color: palette.muted, fontSize: 10, lineHeight: 14, marginTop: 3 },
  cardBodyMint: { color: "#3D584D", fontSize: 10, lineHeight: 14, marginTop: 3, fontWeight: "600" },
  cardBodyAmber: { color: "#695040", fontSize: 10, lineHeight: 14, marginTop: 3, fontWeight: "600" },

  soloHorizontalSkin: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 12,
  },
  soloMetaCol: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  soloEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  soloEyebrowText: {
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  soloHeading: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 0.3,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  soloDesc: {
    color: palette.muted,
    fontSize: 9.5,
    lineHeight: 13,
    marginTop: 1,
    fontWeight: "600",
  },
  soloDescEmerald: {
    color: "#3D5949",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
    fontWeight: "600",
  },
  soloDescRuby: {
    color: "#68484E",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
    fontWeight: "600",
  },
  soloDescAmber: {
    color: "#784E20",
    fontSize: 11,
    lineHeight: 15,
    marginTop: 1,
    fontWeight: "600",
  },
  soloActionBtn: {
    minWidth: 80,
    flexShrink: 0,
  },
  soloSkin: { flexDirection: "row", alignItems: "center", padding: 12, gap: 12 },
  soloEyebrow: { color: palette.gold, fontSize: 10, fontWeight: "900", letterSpacing: 0.5 },
  soloArrow: { color: palette.gold, fontSize: 26, fontWeight: "900" },

  modeGrid: { flexDirection: "row", gap: 6, width: "100%" },
  modeNodeWrap: { flex: 1 },
  modeNode: {
    minHeight: 106,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  modeNodeHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    width: "100%",
  },
  modeSize: {
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  modeMiniDot: { width: 6, height: 6, borderRadius: 3, shadowOpacity: 0.08, shadowRadius: 4 },
  modeTitle: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 3,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  modeMetaPill: {
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginTop: 3,
  },
  modeMeta: { fontSize: 9.5, fontWeight: "800", textAlign: "center" },
  lockTrack: { width: "90%", height: 4, backgroundColor: "#E2E8F0", borderRadius: 2, marginTop: 4, overflow: "hidden" },

  streakWarningPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEEBEB",
    borderWidth: 1.5,
    borderBottomWidth: 3,
    borderColor: "#FCA5A5",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginTop: 8,
    marginBottom: 4,
    gap: 8,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  streakWarningIcon: { fontSize: 15 },
  streakWarningText: { flex: 1, color: "#8E1E2E", fontSize: 10.5, fontWeight: "900", letterSpacing: 0.3 },
  streakWarningArrow: { color: "#BA354A", fontSize: 13, fontWeight: "900" },

  milestoneBadgePill: {
    backgroundColor: palette.gold,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
    shadowColor: palette.gold,
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  milestoneBadgeText: { color: "#293541", fontSize: 10, fontWeight: "900", letterSpacing: 0.3 },

  mysteryFab: {
    position: "absolute",
    right: 16,
    bottom: 152,
    zIndex: 999,
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#EFF6FF",
    borderWidth: 2,
    borderBottomWidth: 3.5,
    borderColor: "#93C5FD",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#1E40AF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 8,
  },
  mysteryFabIcon: {
    fontSize: 22,
  },
  mysteryStripLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  mysteryIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#CFE4FA",
    borderWidth: 1.5,
    borderColor: "#A3CAF2",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mysteryIconText: {
    fontSize: 14,
  },
  mysteryStripTextCol: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  mysteryStripEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  mysteryStripEyebrow: {
    fontSize: 8,
    fontWeight: "900",
    color: "#156F9F",
    letterSpacing: 0.5,
  },
  mysteryStripDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#50B4EA",
  },
  mysteryStripReward: {
    fontSize: 8.5,
    fontWeight: "900",
    color: "#9C5F00",
    letterSpacing: 0.4,
  },
  mysteryStripDef: {
    fontSize: 11.5,
    fontStyle: "italic",
    fontWeight: "700",
    color: "#1F2F3D",
    lineHeight: 16,
    marginTop: 2,
  },
  mysteryStripInfoBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#CFE4FA",
    borderWidth: 1.5,
    borderColor: "#A3CAF2",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
    flexShrink: 0,
  },
  mysteryStripInfoIcon: {
    fontSize: 12,
    color: "#156F9F",
    fontWeight: "900",
  },

  infoMini: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    justifyContent: "center",
    alignItems: "center",
  },

  pressed: { opacity: 0.88, transform: [{ scale: 0.98 }] },
});
