import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({

  container: { flexGrow: 1, paddingHorizontal: 16, paddingTop: 4, paddingBottom: 185 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  backButton: { width: 38, height: 38, borderRadius: 14, backgroundColor: "#F0F5ED", borderWidth: 1, borderColor: "#DCE1D7", alignItems: "center", justifyContent: "center" },
  backText: { color: "#293541", fontSize: 26, lineHeight: 28 },
  headerTitleWrap: { flex: 1, marginLeft: 12, marginRight: 8 },
  headerKicker: { color: "#8c763b", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  headerTitle: { color: "#293541", fontSize: 26, fontWeight: "900", marginTop: 2, letterSpacing: 0.3, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  coinBadge: { flexDirection: "row", alignItems: "center", backgroundColor: "#F0F5ED", paddingHorizontal: 11, paddingVertical: 7, borderRadius: 14, borderWidth: 1.5, borderColor: "#DCE1D7", gap: 4, shadowColor: "#293541", shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
  coinIcon: { fontSize: 14 },
  coinText: { color: "#98732c", fontSize: 14, fontWeight: "900" },
  coinUnit: { color: "#293541", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },

  msgBanner: { backgroundColor: "#F0F5ED", padding: 12, borderRadius: 14, borderWidth: 1, borderColor: "#DCE1D7", marginBottom: 12 },
  msgBannerText: { color: "#2a9c7a", fontSize: 11, fontWeight: "800", textAlign: "center" },

  storeList: { gap: 10 },
  tabs: { flexDirection: "row", backgroundColor: "#FFFFFF", borderRadius: 14, padding: 4, marginBottom: 14, borderWidth: 1.5, borderColor: "#DCE1D7" },
  tab: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 10 },
  tabActive: { backgroundColor: "#FFD66E" },
  tabText: { color: "#293541", fontSize: 12, fontWeight: "900", letterSpacing: 0.3 },
  tabTextActive: { color: "#293541" },
  tabIntro: { padding: 14, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1.5, borderColor: "#DCE1D7" },
  tabIntroTitle: { color: "#293541", fontSize: 13, fontWeight: "900" },
  tabIntroText: { color: "#293541", fontSize: 10, marginTop: 4 },
  cosmeticGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, width: "100%" },

  /* Kompakt Grid Kartlar */
  cosmeticCard: {
    width: "31%",
    minHeight: 120,
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 10,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  cosmeticCardSelected: {
    backgroundColor: "#EBFBFA",
    borderWidth: 2,
  },
  cosmeticRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2.5,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cosmeticRingInner: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
  },
  cosmeticCornerDot: {
    position: "absolute",
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  cosmeticEffectBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  cosmeticCardName: {
    fontSize: 10.5,
    fontWeight: "900",
    textAlign: "center",
    marginVertical: 4,
  },
  cosmeticCardBadge: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },



  /* Tahta Görünümleri */
  realisticBoardWrap: {
    width: 52,
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    padding: 4,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  miniBoardGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    width: 40,
    height: 40,
    gap: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  miniCell: {
    width: 17,
    height: 17,
    borderRadius: 4,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  miniCellText: {
    fontSize: 8,
    fontWeight: "900",
  },

  cosmeticName: { color: "#293541", fontSize: 10, fontWeight: "900", textAlign: "center", marginBottom: 4 },
  cosmeticBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  badgeOwned: {
    backgroundColor: "rgba(62, 232, 181, 0.15)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  badgeCost: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  cosmeticBadgeText: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.3,
  },

  sectionHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 12, marginBottom: 2 },
  sectionTitleHeader: { color: "#293541", fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  sectionSubHeader: { color: "#293541", fontSize: 8, fontWeight: "900" },
  dailyRewardChestCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F5ED",
    padding: 14,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 4,
  },
  dailyChestIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: "rgba(255, 194, 74, 0.15)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  dailyChestKicker: {
    color: "#98732c",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  dailyChestBadge: {
    backgroundColor: "rgba(255, 194, 74, 0.25)",
    paddingHorizontal: 6,
    paddingVertical: 1.5,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  dailyChestBadgeText: {
    color: "#98732c",
    fontSize: 7.5,
    fontWeight: "900",
  },
  dailyChestTitle: {
    color: "#293541",
    fontSize: 13.5,
    fontWeight: "900",
    marginTop: 2,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  dailyChestDesc: {
    color: "#293541",
    fontSize: 10,
    marginTop: 2,
    lineHeight: 14,
  },
  dailyChestBtn: {
    backgroundColor: "#ffe5b3",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 72,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  dailyChestBtnText: {
    color: "#293541",
    fontSize: 11.5,
    fontWeight: "900",
  },

  adBannerCard: { flexDirection: "row", alignItems: "center", backgroundColor: "#FFFFFF", padding: 14, borderRadius: 20, borderWidth: 1.5, borderColor: "#DCE1D7", shadowColor: "#293541", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  adIconCircle: { width: 44, height: 44, borderRadius: 15, backgroundColor: "rgba(62, 232, 181, 0.12)", borderWidth: 1, borderColor: "#DCE1D7", alignItems: "center", justifyContent: "center", marginRight: 12 },
  adBannerKicker: { color: "#2a9c7a", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },
  adFreeBadge: { backgroundColor: "rgba(62, 232, 181, 0.2)", paddingHorizontal: 5, paddingVertical: 1, borderRadius: 6 },
  adFreeText: { color: "#2a9c7a", fontSize: 7, fontWeight: "900" },
  adBannerTitle: { color: "#293541", fontSize: 13, fontWeight: "900", marginTop: 2, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  adBannerDesc: { color: "#293541", fontSize: 10, marginTop: 2 },
  adButton: { backgroundColor: "#FFD66E", paddingHorizontal: 14, paddingVertical: 10, borderRadius: 12, alignItems: "center", justifyContent: "center", minWidth: 64 },
  adButtonText: { color: "#293541", fontSize: 12, fontWeight: "900" },

  productCard: { flexDirection: "row", alignItems: "center", backgroundColor: "#FFFFFF", padding: 14, borderRadius: 18, borderWidth: 1.5, borderColor: "#DCE1D7", shadowColor: "#293541", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  productIconWrap: { width: 46, height: 46, borderRadius: 16, backgroundColor: "#F7F5EE", borderWidth: 1.5, borderColor: "#DCE1D7", alignItems: "center", justifyContent: "center", marginRight: 12, position: "relative" },
  productEmblemDot: { position: "absolute", top: 3, right: 3, width: 6, height: 6, borderRadius: 3 },
  productIcon: { fontSize: 24 },
  productInfo: { flex: 1, marginRight: 10 },
  productName: { color: "#293541", fontSize: 13, fontWeight: "900", textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  inventoryCountBadge: {
    backgroundColor: "rgba(96, 165, 250, 0.12)",
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  inventoryCountText: {
    color: "#4a7ebf",
    fontSize: 8.5,
    fontWeight: "900",
  },
  productDesc: { color: "#293541", fontSize: 10, marginTop: 2, lineHeight: 14 },

  chipBuyButton: { backgroundColor: "#FFD66E", paddingHorizontal: 14, height: 38, borderRadius: 12, alignItems: "center", justifyContent: "center", minWidth: 76, shadowColor: "#293541", shadowOpacity: 0.08, shadowRadius: 4, elevation: 2 },
  chipBuyButtonDisabled: { backgroundColor: "#F1F3EE", borderWidth: 1, borderColor: "#DCE1D7", shadowOpacity: 0, elevation: 0 },
  chipBuyButtonOwned: { backgroundColor: "rgba(62, 232, 181, 0.12)", borderWidth: 1, borderColor: "#DCE1D7", shadowOpacity: 0, elevation: 0 },
  chipBuyButtonFull: { backgroundColor: "#F1F3EE", borderWidth: 1.5, borderColor: "#DCE1D7", shadowOpacity: 0, elevation: 0 },
  chipBuyButtonFullText: { color: "#349d5a", fontSize: 11.5, fontWeight: "900", letterSpacing: 0.5 },
  chipBuyButtonText: { color: "#293541", fontSize: 11.5, fontWeight: "900" },

  /* Satın Alma Onay Modalı Stilleri */
  confirmOverlay: {
    flex: 1,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  confirmCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: 22,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  confirmBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(62, 232, 181, 0.12)",
    borderWidth: 2,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  confirmBadgeIcon: { fontSize: 28 },
  confirmKicker: {
    color: "#8c7540",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  confirmTitle: {
    color: "#293541",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 4,
    marginBottom: 10,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  confirmCostPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255, 194, 74, 0.12)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    marginBottom: 12,
  },
  confirmCostLabel: { color: "#293541", fontSize: 9.5, fontWeight: "900", letterSpacing: 0.5 },
  confirmCostValue: { color: "#987c00", fontSize: 13, fontWeight: "900" },
  confirmDesc: {
    color: "#293541",
    fontSize: 11.5,
    lineHeight: 17,
    textAlign: "center",
    marginBottom: 14,
  },
  confirmBalanceInfo: {
    width: "100%",
    backgroundColor: "#F0F5ED",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    marginBottom: 18,
    alignItems: "center",
  },
  confirmBalanceText: {
    color: "#293541",
    fontSize: 10.5,
    fontWeight: "700",
  },
  confirmActionsRow: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  confirmCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  confirmCancelText: {
    color: "#293541",
    fontSize: 11.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  confirmAcceptBtn: {
    flex: 1.2,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: "#aef5e0",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  confirmAcceptText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
});
