import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: { flexGrow: 1, paddingBottom: 185 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingVertical: 2,
  },
  back: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  backText: { color: "#293541", fontSize: 26, lineHeight: 28, marginTop: -2 },
  headerCenter: {
    flex: 1,
    paddingHorizontal: 4,
    justifyContent: "center",
  },
  overline: {
    color: "#64748B",
    fontSize: 9,
    letterSpacing: 0.6,
    fontWeight: "900",
  },
  title: {
    color: "#293541",
    fontSize: 18,
    fontWeight: "900",
    marginTop: 1,
    letterSpacing: 0.2,
  },
  timerPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  timerIcon: { fontSize: 13 },
  timerLabel: { color: "#9b7616", fontSize: 7.5, fontWeight: "900", letterSpacing: 0.5 },
  timerValue: { color: "#293541", fontSize: 10, fontWeight: "900" },

  /* Modern Segmented Tab Controller */
  segmentedTabContainer: {
    flexDirection: "row",
    backgroundColor: "#F0F5ED",
    borderRadius: 20,
    padding: 5,
    marginTop: 16,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    gap: 4,
  },
  segmentedTabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 11,
    paddingHorizontal: 8,
    borderRadius: 15,
    position: "relative",
  },
  segmentedTabBtnActive: {
    backgroundColor: "#FFD66E",
    borderWidth: 1.5,
    borderColor: "#F0C855",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  segmentedTabIcon: {
    fontSize: 14,
  },
  segmentedTabText: {
    color: "#64748B",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    flexShrink: 1,
  },
  segmentedTabTextActive: {
    color: "#293541",
    fontWeight: "900",
  },
  onlineBadgeDot: {
    position: "absolute",
    top: 8,
    right: 10,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#a2e7bb",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
  },

  /* Compact Filter Toolbar */
  filterToolbarRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
    marginBottom: 16,
  },
  toolbarSegment: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#F0F5ED",
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    padding: 3,
    gap: 3,
  },
  toolbarPill: {
    flex: 1,
    height: 36,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    backgroundColor: "transparent",
  },
  toolbarPillText: {
    color: "#293541",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  toolbarPillTextActive: {
    color: "#293541",
    fontWeight: "900",
  },
  toolbarPillActiveLp: {
    backgroundColor: "#FFD66E",
    borderWidth: 1.5,
    borderColor: "#F0C855",
    shadowColor: "#293541",
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  toolbarPillActiveLevel: {
    backgroundColor: "#7DD3FC",
    borderWidth: 1.5,
    borderColor: "#38BDF8",
    shadowColor: "#293541",
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  toolbarPillActiveScope: {
    backgroundColor: "#6EE7B7",
    borderWidth: 1.5,
    borderColor: "#34D399",
    shadowColor: "#293541",
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },

  /* Hero Cards */
  hero: {
    marginTop: 14,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  heroKicker: { color: "#8c7446", fontSize: 8, letterSpacing: 0.5, fontWeight: "900" },
  heroTitle: { color: "#293541", fontSize: 25, fontWeight: "900", marginTop: 6, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  heroBody: { color: "#293541", fontSize: 11, marginTop: 4 },
  heroStats: {
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#DCE1D7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statLabel: { color: "#293541", fontSize: 7, fontWeight: "900", letterSpacing: 0.5 },
  statValue: { color: "#293541", fontSize: 14, fontWeight: "900", marginTop: 3, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  statRule: { width: 1, height: 27, backgroundColor: "rgba(212, 180, 90, 0.2)" },

  /* Social Hero */
  socialHero: {
    marginTop: 14,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "#EDF4FC",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  socialHeroKicker: { color: "#2a8fbc", fontSize: 8, letterSpacing: 0.5, fontWeight: "900" },
  socialHeroTitle: { color: "#293541", fontSize: 23, fontWeight: "900", marginTop: 6, textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  socialHeroBody: { color: "#293541", fontSize: 11, marginTop: 4 },

  /* Mystery Card */
  mysteryCard: {
    marginTop: 12,
    padding: 14,
    borderRadius: 20,
    backgroundColor: "#FFF0E8",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
  },
  mysteryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  mysteryKicker: { color: "#293541", fontSize: 9, fontWeight: "900", letterSpacing: 0.5 },
  mysteryReward: { color: "#2a9c7a", fontSize: 9, fontWeight: "900" },
  mysteryDef: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "700",
    fontStyle: "italic",
    lineHeight: 17,
  },
  mysteryHint: { color: "#8c7540", fontSize: 8, fontWeight: "800", marginTop: 6 },

  /* User Status Banner */
  userStatusCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 20,
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  userStatusLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  userStatusAvatarOrb: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#e8d8a4",
    borderWidth: 2,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  userStatusAvatarText: {
    color: "#293541",
    fontSize: 20,
    fontWeight: "900",
  },
  userStatusName: {
    color: "#293541",
    fontSize: 14,
    fontWeight: "900",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  userRankBadge: {
    backgroundColor: "rgba(62, 232, 181, 0.15)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  userRankBadgeText: {
    color: "#2a9c7a",
    fontSize: 8,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  userStatusSub: {
    color: "#293541",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 3,
  },
  userStatusRight: {
    marginLeft: 10,
    alignItems: "flex-end",
  },
  leaderCrownBadge: {
    backgroundColor: "rgba(255, 208, 0, 0.15)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  leaderCrownText: {
    color: "#987c00",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  diffBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  diffKicker: {
    color: "#293541",
    fontSize: 7.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  diffScore: {
    color: "#98732c",
    fontSize: 11,
    fontWeight: "900",
    marginTop: 1,
  },

  /* Vitrin Showcase Podium (Top 3) */
  podiumContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    paddingTop: 16,
    paddingHorizontal: 12,
    marginTop: 14,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  podiumVitrinHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    paddingHorizontal: 4,
  },
  podiumVitrinTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255, 214, 110, 0.2)",
    borderWidth: 1,
    borderColor: "#F0C855",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  podiumVitrinTagText: {
    color: "#98732c",
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  podiumVitrinKicker: {
    color: "#64748B",
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  podiumRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 10,
  },
  podiumColumn: {
    flex: 1,
    alignItems: "center",
  },
  podiumCol1: {
    zIndex: 3,
  },
  podiumCol2: {
    zIndex: 2,
  },
  podiumCol3: {
    zIndex: 1,
  },
  crownIcon: {
    fontSize: 22,
    marginBottom: -4,
  },
  podiumAvatarWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2.5,
    position: "relative",
    backgroundColor: "#F7F5EE",
  },
  podiumAvatarWrap1: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderColor: "#F59E0B",
    backgroundColor: "#FFFBEB",
    shadowColor: "#F59E0B",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  podiumAvatarWrap2: {
    borderColor: "#94A3B8",
    backgroundColor: "#F1F5F9",
    shadowColor: "#94A3B8",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  podiumAvatarWrap3: {
    borderColor: "#D97706",
    backgroundColor: "#FEF3C7",
    shadowColor: "#D97706",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  podiumAvatarText: {
    color: "#293541",
    fontSize: 20,
    fontWeight: "900",
  },
  podiumRankBadge: {
    position: "absolute",
    bottom: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
  },
  podiumRankBadge1: {
    backgroundColor: "#F59E0B",
    borderColor: "#FFFFFF",
  },
  podiumRankBadge2: {
    backgroundColor: "#94A3B8",
    borderColor: "#FFFFFF",
  },
  podiumRankBadge3: {
    backgroundColor: "#D97706",
    borderColor: "#FFFFFF",
  },
  podiumRankNum: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "900",
  },
  podiumName: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    marginTop: 8,
    textAlign: "center",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  tierBadge: {
    marginTop: 3,
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
  },
  tierBadgeText: {
    fontSize: 7.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  rowTierBadge: {
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    backgroundColor: "#F0F5ED",
  },
  rowTierText: {
    fontSize: 7,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  rowLpText: {
    color: "#98732c",
    fontSize: 8.5,
    fontWeight: "800",
    marginTop: 2,
  },
  podiumScore: {
    color: "#059669",
    fontSize: 10.5,
    fontWeight: "900",
    marginTop: 3,
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  podiumBar1: {
    width: "100%",
    height: 72,
    backgroundColor: "#FEF3C7",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderWidth: 1.5,
    borderColor: "#F59E0B",
    borderBottomWidth: 0,
    alignItems: "center",
    paddingTop: 8,
    marginTop: 8,
  },
  podiumBar2: {
    width: "100%",
    height: 52,
    backgroundColor: "#F1F5F9",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderWidth: 1.5,
    borderColor: "#94A3B8",
    borderBottomWidth: 0,
    alignItems: "center",
    paddingTop: 8,
    marginTop: 8,
  },
  podiumBar3: {
    width: "100%",
    height: 42,
    backgroundColor: "#FFFBEB",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    borderWidth: 1.5,
    borderColor: "#D97706",
    borderBottomWidth: 0,
    alignItems: "center",
    paddingTop: 8,
    marginTop: 8,
  },
  podiumBarLabel: {
    color: "#293541",
    fontSize: 8.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },

  /* Section Head */
  sectionHead: {
    marginTop: 16,
    marginBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { color: "#293541", fontSize: 12, fontWeight: "900", letterSpacing: 0.5 },
  sectionMeta: { color: "#293541", fontSize: 8, fontWeight: "900", letterSpacing: 0.5 },

  /* Board & Rows */
  board: {
    borderRadius: 20,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    overflow: "hidden",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  row: {
    minHeight: 54,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    borderBottomWidth: 1,
    borderBottomColor: "#DCE1D7",
  },
  rowUser: {
    backgroundColor: "rgba(62, 232, 181, 0.08)",
    borderLeftWidth: 4,
    borderLeftColor: "#DCE1D7",
  },
  userSelfTag: {
    backgroundColor: "#aef5e0",
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
  },
  userSelfTagText: {
    color: "#293541",
    fontSize: 7.5,
    fontWeight: "900",
  },
  winRateBadge: {
    paddingHorizontal: 5,
    paddingVertical: 1,
    borderRadius: 4,
  },
  winRateHigh: {
    backgroundColor: "rgba(62, 232, 181, 0.15)",
  },
  winRateNormal: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  winRateText: {
    color: "#2a9c7a",
    fontSize: 7.5,
    fontWeight: "900",
  },
  rowTop1: {
    backgroundColor: "rgba(255, 208, 0, 0.08)",
    borderLeftWidth: 4,
    borderLeftColor: "#DCE1D7",
  },
  rowTop2: {
    backgroundColor: "rgba(148, 163, 184, 0.06)",
    borderLeftWidth: 4,
    borderLeftColor: "#DCE1D7",
  },
  rowTop3: {
    backgroundColor: "rgba(251, 146, 96, 0.06)",
    borderLeftWidth: 4,
    borderLeftColor: "#DCE1D7",
  },
  position: {
    width: 23,
    height: 23,
    borderRadius: 8,
    backgroundColor: "#F0F5ED",
    alignItems: "center",
    justifyContent: "center",
  },
  positionFirst: { backgroundColor: "#ffeb94" },
  positionSecond: { backgroundColor: "#d2d8e1" },
  positionThird: { backgroundColor: "#fdd1ad" },
  positionText: { color: "#293541", fontSize: 9, fontWeight: "900" },
  playerMark: {
    width: 29,
    height: 29,
    borderRadius: 10,
    backgroundColor: "#EDF4FC",
    alignItems: "center",
    justifyContent: "center",
  },
  playerMarkText: { color: "#98732c", fontSize: 11, fontWeight: "900" },
  playerCopy: { flex: 1 },
  playerName: { color: "#293541", fontSize: 11, fontWeight: "900", textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  playerMeta: { color: "#293541", fontSize: 7, marginTop: 3, fontWeight: "800" },
  score: { color: "#389674", fontSize: 13, fontWeight: "900", textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  emptyBoard: { padding: 22, alignItems: "center" },
  emptyTitle: { color: "#293541", fontSize: 12, fontWeight: "900" },
  emptyCopy: { color: "#293541", fontSize: 10, textAlign: "center", marginTop: 5 },

  /* Add Friend Card */
  addCard: {
    marginTop: 12,
    backgroundColor: "#F0F5ED",
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  addCardLabel: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  addFriendRow: { flexDirection: "row", gap: 8 },
  addFriendInput: {
    flex: 1,
    backgroundColor: "#F0F5ED",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: "#293541",
    fontSize: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
  },
  addFriendBtn: {
    backgroundColor: "#e8d8a4",
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  addFriendBtnText: {
    color: "#293541",
    fontWeight: "900",
    fontSize: 11,
    letterSpacing: 0.5,
  },
  socialMsg: {
    color: "#2a9c7a",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 6,
  },

  /* Friends Board */
  friendsBoard: {
    gap: 10,
  },
  friendRow: {
    backgroundColor: "#F0F5ED",
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    gap: 10,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  friendRowTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  friendAvatarText: { fontSize: 24 },
  friendNameText: { color: "#293541", fontSize: 13, fontWeight: "900", textShadowColor: "transparent", textShadowOffset: { width: 0, height: 0 }, textShadowRadius: 0 },
  friendXpText: { color: "#293541", fontSize: 9.5, marginTop: 2 },
  statusWrap: { alignItems: "flex-end", gap: 3 },
  onlineDot: { width: 8, height: 8, borderRadius: 4 },
  onlineDotActive: {
    backgroundColor: "#aef5e0",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  onlineDotOffline: { backgroundColor: "#EDF4FC" },
  onlineStatusText: {
    color: "#293541",
    fontSize: 7.5,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  challengeBtn: {
    backgroundColor: "rgba(62, 232, 181, 0.12)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  challengeBtnText: {
    color: "#2a9c7a",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  removeFriendBtn: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
  },
  removeFriendText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
  },

  /* Sub Tab Container */
  subTabContainer: {
    flexDirection: "row",
    backgroundColor: "#F0F5ED",
    borderRadius: 14,
    padding: 3,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    gap: 4,
  },
  subTabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 11,
    position: "relative",
    gap: 6,
  },
  subTabBtnActive: {
    backgroundColor: "#FFD66E",
    borderWidth: 1.5,
    borderColor: "#F0C855",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  subTabText: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  subTabTextActive: {
    color: "#293541",
    fontWeight: "900",
  },
  requestBadgeDot: {
    backgroundColor: "#ffbec8",
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  requestBadgeText: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
  },

  /* Request Row */
  requestRow: {
    backgroundColor: "#F0F5ED",
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    gap: 12,
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  requestActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  acceptBtn: {
    flex: 1,
    backgroundColor: "rgba(62, 232, 181, 0.18)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    paddingVertical: 9,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  acceptBtnText: {
    color: "#2a9c7a",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  rejectBtn: {
    flex: 1,
    backgroundColor: "rgba(255, 100, 124, 0.15)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    paddingVertical: 9,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  rejectBtnText: {
    color: "#ca4f62",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.4,
  },

  /* Board Size Picker Modal */
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 340,
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: 20,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  modalKicker: {
    color: "#2a9c7a",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
  },
  modalTitle: {
    color: "#293541",
    fontSize: 18,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 4,
  },
  modalSubtitle: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 2,
    marginBottom: 16,
  },
  sizeGrid: {
    gap: 9,
    marginBottom: 16,
  },
  sizeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F0F5ED",
    borderWidth: 1.5,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  sizeBtnLabel: {
    fontSize: 14,
    fontWeight: "900",
  },
  sizeBtnDesc: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "700",
  },
  modalCancel: {
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  modalCancelText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  expandLeaderboardBtn: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "rgba(62, 232, 181, 0.12)",
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  expandLeaderboardBtnText: {
    color: "#2a9c7a",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textAlign: "center",
  },
});
