import fs from 'node:fs';
let p='components/command-center.tsx', s=fs.readFileSync(p,'utf8');
s=s.replace('GameButton, GameIcon, GemChip','GameButton, GameGlyph, GameIcon, GemChip');
s=s.replace(/<Image source=\{ICONS\.(\w+)\} style=\{styles\.\w+\} \/>/g,'<GameGlyph source={ICONS.$1} size={22} />');
s=s.replace(/  const orbit =[^\n]+\n/,'').replace(/  const shimmer =[^\n]+\n/,'');
s=s.replace(/  useEffect\(\(\) => \{\s*const orbitLoop[\s\S]*?\}, \[orbit, shimmer\]\);/,'');
s=s.replace(/  const orbitSpin =[^\n]+\n/,'');
s=s.replace(/        <Animated.View style=\{\[styles.orbit[\s\S]*?<View style=\{styles.heroHead\}>/,'        <View style={styles.heroHead}>');
s=s.replace('KELİME MACERASI · SEZON 01','BİR KELİMEYLE BAŞLA');
s=s.replace('<JewelTitle>ROTANI{"\\n"}ATEŞLE</JewelTitle>','<JewelTitle>Azıcık mola. {"\\n"}Bolca kelime.</JewelTitle>\n        <View accessible={false} style={{ flexDirection: "row", gap: 7, marginTop: 16, marginBottom: 4 }}>{["O", "Y", "N", "A"].map((letter, index) => <View key={letter} style={{ width: 42, height: 46, borderRadius: 12, borderWidth: 1, borderBottomWidth: 4, borderColor: "#D6B05B", backgroundColor: index === 3 ? "#FFAA99" : "#FFD66E", alignItems: "center", justifyContent: "center", transform: [{ rotate: index % 2 ? "5deg" : "-5deg" }] }}><Text style={{ color: palette.text, fontWeight: "900", fontSize: 24 }}>{letter}</Text></View>)}</View>');
s=s.replace('Dereceli düello seç, günün rotasını bitir veya lig merdivenine tırman.','Harfleri birleştir. Kelimeleri bul. Kendi rekorunu geç.');
s=s.replace('SİBER BOT İLE HIZLI ALIŞTIRMA YAP','Önce biraz pratik yap').replace('ROTANI ATEŞLE','HADİ OYNAYALIM').replaceAll('Siber Radar','Kelime Radarı').replaceAll('Siber Can','Can').replace('Rotanı Ateşle Nedir?','Nereden başlayayım?').replace('Rotanı Ateşle güverte kartı, oyunun ana rekabet merkezidir!','Buradan istediğin oyunu seçebilirsin.');
s=s.replace('label="DERECELİ DÜELLO"','label="Düelloya başla"').replace('label="ARKADAŞLA OYNA"','label="Arkadaşla oyna"');
s=s.replace('fontSize: 11, lineHeight: 15, marginTop: 6, maxWidth: 240','fontSize: 14, lineHeight: 21, marginTop: 10, maxWidth: 300');
s=s.replace('heroActions: { flexDirection: "row"','heroActions: { flexDirection: "column"');
s=s.replace('fontSize: 13, fontWeight: "900", letterSpacing: 0.2','fontSize: 15, fontWeight: "800", letterSpacing: 0.2');
s=s.replace('useEffect, useRef, useState','useEffect, useRef, useState').replace('Animated, Easing, Image,','Image,');
fs.writeFileSync(p,s);
p='components/game-splash-screen.tsx';s=fs.readFileSync(p,'utf8');
s=s.replace('  ImageBackground,\n','').replaceAll('Evrenin harfleri toplanıyor...','Harfler hazırlanıyor...').replaceAll('Matris şifreleri çözümleniyor...','Kelimeler yerini alıyor...').replaceAll('Harf rotaları taranıyor...','Birazdan başlıyoruz...').replaceAll('Oyuncu profili senkronize ediliyor...','Son hazırlıklar...').replaceAll('⚡ SİBER KELİME MATRİSİ','BİR KELİMEYLE BAŞLA');
s=s.replace(/<ImageBackground[\s\S]*?resizeMode="cover"\s*>/,'<View style={[styles.background, { width, height }]}><View style={{ position: "absolute", top: "30%", alignItems: "center" }}><Text style={{ fontSize: 42, fontWeight: "900", color: "#293541", letterSpacing: -1 }}>kelime<Text style={{ color: "#C5523E" }}> patlat</Text></Text><Text style={{ fontSize: 16, color: "#626F73", marginTop: 12 }}>Küçük bir mola, yeni bir rekor.</Text></View>').replace('</ImageBackground>','</View>');
fs.writeFileSync(p,s);
p='components/screen-container.tsx';s=fs.readFileSync(p,'utf8').replace('  content: {\n    flex: 1,','  content: {\n    width: "100%",\n    maxWidth: 560,\n    alignSelf: "center",\n    flex: 1,');fs.writeFileSync(p,s);
p='app.config.ts';s=fs.readFileSync(p,'utf8').replace('userInterfaceStyle: "automatic"','userInterfaceStyle: "light"').replaceAll('#06140F','#F7F5EE');fs.writeFileSync(p,s);
