import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(35,48,59,0.42)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  containerCard: {
    width: "100%",
    maxWidth: 440,
    height: "82%",
    maxHeight: "88%",
    backgroundColor: "#F0F5ED",
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "#DCE1D7",
    overflow: "hidden",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    display: "flex",
    flexDirection: "column",
  },
  topGlowBar: {
    height: 4,
    width: "100%",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#DCE1D7",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "rgba(80, 227, 194, 0.12)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  headerIcon: {
    fontSize: 22,
  },
  headerKicker: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    color: "#359580",
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "900",
    letterSpacing: 0.5,
    color: "#293541",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  closeBtnText: {
    color: "#293541",
    fontSize: 15,
    fontWeight: "900",
  },
  statsStrip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F0F5ED",
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 10,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  statBox: {
    flex: 1,
    alignItems: "center",
  },
  statLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#293541",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  statValue: {
    fontSize: 15,
    fontWeight: "900",
    color: "#293541",
    textShadowColor: "transparent",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 0,
  },
  statDivider: {
    width: 1,
    height: 20,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  tabRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 6,
    marginBottom: 8,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  tabBtnActive: {
    backgroundColor: "#FFD66E",
    borderWidth: 1.5,
    borderColor: "#F0C855",
    shadowColor: "#293541",
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  tabText: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "700",
  },
  tabTextActive: {
    color: "#293541",
    fontWeight: "900",
  },
  listScroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  listContent: {
    paddingVertical: 6,
    gap: 10,
    flexGrow: 1,
  },
  matchCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  cardModeGroup: {
    flex: 1,
    marginRight: 8,
  },
  cardModeTitle: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  cardTimeText: {
    color: "#293541",
    fontSize: 10,
    fontWeight: "600",
    marginTop: 2,
  },
  resultBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
  },
  resultBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  cardBody: {
    marginBottom: 10,
  },
  soloScoreRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F7F5EE",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  soloScoreLabel: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "700",
  },
  soloScoreValue: {
    color: "#2a8fbc",
    fontSize: 14,
    fontWeight: "900",
  },
  duelScoreRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F7F5EE",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  scoreSide: {
    flex: 1,
  },
  scoreSideLabel: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "700",
    marginBottom: 2,
  },
  scoreSideValue: {
    fontSize: 17,
    fontWeight: "900",
  },
  vsBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
  },
  vsText: {
    color: "#95781d",
    fontSize: 11,
    fontWeight: "900",
  },
  cardFooter: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    paddingTop: 4,
    borderTopWidth: 1,
    borderTopColor: "#DCE1D7",
  },
  rewardChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  lpPositiveChip: {
    backgroundColor: "rgba(52, 211, 153, 0.12)",
    borderColor: "#DCE1D7",
  },
  lpNegativeChip: {
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    borderColor: "#DCE1D7",
  },
  friendChip: {
    backgroundColor: "rgba(168, 85, 247, 0.12)",
    borderColor: "#DCE1D7",
  },
  friendChipText: {
    color: "#8a5fb6",
    fontSize: 10,
    fontWeight: "800",
  },
  xpChip: {
    backgroundColor: "rgba(56, 189, 248, 0.12)",
    borderColor: "#DCE1D7",
  },
  coinChip: {
    backgroundColor: "rgba(251, 191, 36, 0.12)",
    borderColor: "#DCE1D7",
  },
  wordChip: {
    backgroundColor: "#F0F5ED",
    borderColor: "#DCE1D7",
  },
  rewardChipText: {
    fontSize: 10,
    fontWeight: "900",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    fontSize: 44,
    marginBottom: 12,
    opacity: 0.8,
  },
  emptyTitle: {
    color: "#293541",
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 6,
    textAlign: "center",
  },
  emptySub: {
    color: "#293541",
    fontSize: 12,
    textAlign: "center",
    lineHeight: 18,
    maxWidth: 280,
    marginBottom: 18,
  },
  playNowBtn: {
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 12,
    backgroundColor: "#F0F5ED",
    shadowColor: "#293541",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  playNowBtnText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  modalBottomBar: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#DCE1D7",
  },
  bottomCloseBtn: {
    width: "100%",
    paddingVertical: 11,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomCloseBtnText: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  pressed: {
    opacity: 0.75,
    transform: [{ scale: 0.98 }],
  },
});
