import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 40,
  },
  subHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    justifyContent: "center",
    alignItems: "center",
  },
  backText: {
    color: "#293541",
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 28,
  },
  headerTitles: {
    flex: 1,
  },
  subHeaderKicker: {
    color: "#293541",
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  subHeaderTitle: {
    color: "#293541",
    fontSize: 20,
    fontWeight: "900",
    marginTop: 2,
    letterSpacing: 0.5,
  },
  modeIntro: {
    color: "#293541",
    fontSize: 13,
    lineHeight: 19,
    marginTop: 14,
    marginBottom: 14,
  },
  sectionLabel: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  sizeRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 18,
  },
  sizeCard: {
    flex: 1,
    backgroundColor: "#F0F5ED",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  sizeCardSelected: {
    borderColor: "#F0C855",
    borderWidth: 2,
    backgroundColor: "#FFF9E6",
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  sizeValue: {
    color: "#293541",
    fontSize: 18,
    fontWeight: "900",
  },
  sizeValueSelected: {
    color: "#293541",
  },
  sizeCaption: {
    color: "#293541",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 4,
    textAlign: "center",
  },
  sizeDetail: {
    color: "#718096",
    fontSize: 8,
    marginTop: 2,
    textAlign: "center",
  },
  primaryButton: {
    backgroundColor: "#aef5e0",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 16,
    paddingVertical: 14,
    shadowColor: "#293541",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  primaryButtonText: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  primaryButtonArrow: {
    color: "#293541",
    fontSize: 14,
    fontWeight: "900",
  },
  joinCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    padding: 16,
    marginTop: 14,
  },
  joinTitle: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  joinRow: {
    flexDirection: "row",
    gap: 8,
  },
  codeInput: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#293541",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 2,
  },
  joinButton: {
    backgroundColor: "#aef5e0",
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  joinButtonDisabled: {
    opacity: 0.45,
  },
  joinButtonText: {
    color: "#293541",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  friendsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 10,
  },
  friendsHeaderTitle: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  findFriendsLink: {
    color: "#2a9c7a",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  emptyFriendsCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    padding: 24,
    alignItems: "center",
  },
  emptyFriendsTitle: {
    color: "#293541",
    fontSize: 14,
    fontWeight: "900",
    marginBottom: 4,
  },
  emptyFriendsText: {
    color: "#718096",
    fontSize: 11,
    textAlign: "center",
    lineHeight: 16,
    marginBottom: 14,
  },
  emptyFriendsButton: {
    backgroundColor: "rgba(62, 232, 181, 0.15)",
    borderWidth: 1,
    borderColor: "#DCE1D7",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  emptyFriendsButtonText: {
    color: "#2a9c7a",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  friendDuelCard: {
    backgroundColor: "#F0F5ED",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#DCE1D7",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  friendDuelLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  friendAvatarWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(35,48,59,0.06)",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  friendOnlineDot: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: "#F0F5ED",
  },
  friendDuelInfo: {
    flex: 1,
  },
  friendDuelName: {
    color: "#293541",
    fontSize: 13,
    fontWeight: "900",
  },
  friendDuelTag: {
    fontSize: 9,
    fontWeight: "800",
    color: "#8c7540",
    backgroundColor: "rgba(212, 180, 90, 0.15)",
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
  },
  friendDuelMeta: {
    color: "#718096",
    fontSize: 10,
    marginTop: 2,
  },
  friendDuelButton: {
    backgroundColor: "#aef5e0",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  friendDuelButtonText: {
    color: "#293541",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  notice: {
    color: "#718096",
    fontSize: 11,
    textAlign: "center",
    marginTop: 12,
    lineHeight: 16,
  },
  pressed: {
    opacity: 0.8,
  },
});
